<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\AccountsReceivable;

/**
 * Builder for model AccountsReceivable
 *
 * @see AccountsReceivable
 */
class AccountsReceivableBuilder
{
    /**
     * @var AccountsReceivable
     */
    private $instance;

    private function __construct(AccountsReceivable $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Accounts Receivable Builder object.
     */
    public static function init(): self
    {
        return new self(new AccountsReceivable());
    }

    /**
     * Sets Outstanding field.
     *
     * @param float|null $value
     */
    public function outstanding(?float $value): self
    {
        $this->instance->setOutstanding($value);
        return $this;
    }

    /**
     * Sets Overdue field.
     *
     * @param float|null $value
     */
    public function overdue(?float $value): self
    {
        $this->instance->setOverdue($value);
        return $this;
    }

    /**
     * Initializes a new Accounts Receivable object.
     */
    public function build(): AccountsReceivable
    {
        return CoreHelper::clone($this->instance);
    }
}
