<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\Account;
use XeroAccountingAPILib\Models\ValidationError;

/**
 * Builder for model Account
 *
 * @see Account
 */
class AccountBuilder
{
    /**
     * @var Account
     */
    private $instance;

    private function __construct(Account $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Account Builder object.
     */
    public static function init(): self
    {
        return new self(new Account());
    }

    /**
     * Sets Account ID field.
     *
     * @param string|null $value
     */
    public function accountID(?string $value): self
    {
        $this->instance->setAccountID($value);
        return $this;
    }

    /**
     * Sets Add To Watchlist field.
     *
     * @param bool|null $value
     */
    public function addToWatchlist(?bool $value): self
    {
        $this->instance->setAddToWatchlist($value);
        return $this;
    }

    /**
     * Sets Bank Account Number field.
     *
     * @param string|null $value
     */
    public function bankAccountNumber(?string $value): self
    {
        $this->instance->setBankAccountNumber($value);
        return $this;
    }

    /**
     * Sets Bank Account Type field.
     *
     * @param string|null $value
     */
    public function bankAccountType(?string $value): self
    {
        $this->instance->setBankAccountType($value);
        return $this;
    }

    /**
     * Sets Class field.
     *
     * @param string|null $value
     */
    public function class(?string $value): self
    {
        $this->instance->setClass($value);
        return $this;
    }

    /**
     * Sets Code field.
     *
     * @param string|null $value
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets Currency Code field.
     *
     * @param string|null $value
     */
    public function currencyCode(?string $value): self
    {
        $this->instance->setCurrencyCode($value);
        return $this;
    }

    /**
     * Sets Description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets Enable Payments To Account field.
     *
     * @param bool|null $value
     */
    public function enablePaymentsToAccount(?bool $value): self
    {
        $this->instance->setEnablePaymentsToAccount($value);
        return $this;
    }

    /**
     * Sets Has Attachments field.
     *
     * @param bool|null $value
     */
    public function hasAttachments(?bool $value): self
    {
        $this->instance->setHasAttachments($value);
        return $this;
    }

    /**
     * Sets Name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets Reporting Code field.
     *
     * @param string|null $value
     */
    public function reportingCode(?string $value): self
    {
        $this->instance->setReportingCode($value);
        return $this;
    }

    /**
     * Sets Reporting Code Name field.
     *
     * @param string|null $value
     */
    public function reportingCodeName(?string $value): self
    {
        $this->instance->setReportingCodeName($value);
        return $this;
    }

    /**
     * Sets Show In Expense Claims field.
     *
     * @param bool|null $value
     */
    public function showInExpenseClaims(?bool $value): self
    {
        $this->instance->setShowInExpenseClaims($value);
        return $this;
    }

    /**
     * Sets Status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets System Account field.
     *
     * @param string|null $value
     */
    public function systemAccount(?string $value): self
    {
        $this->instance->setSystemAccount($value);
        return $this;
    }

    /**
     * Sets Tax Type field.
     *
     * @param string|null $value
     */
    public function taxType(?string $value): self
    {
        $this->instance->setTaxType($value);
        return $this;
    }

    /**
     * Sets Type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets Updated Date UTC field.
     *
     * @param string|null $value
     */
    public function updatedDateUTC(?string $value): self
    {
        $this->instance->setUpdatedDateUTC($value);
        return $this;
    }

    /**
     * Sets Validation Errors field.
     *
     * @param ValidationError[]|null $value
     */
    public function validationErrors(?array $value): self
    {
        $this->instance->setValidationErrors($value);
        return $this;
    }

    /**
     * Initializes a new Account object.
     */
    public function build(): Account
    {
        return CoreHelper::clone($this->instance);
    }
}
