<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\Action;
use XeroAccountingAPILib\Models\Actions;

/**
 * Builder for model Actions
 *
 * @see Actions
 */
class ActionsBuilder
{
    /**
     * @var Actions
     */
    private $instance;

    private function __construct(Actions $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Actions Builder object.
     */
    public static function init(): self
    {
        return new self(new Actions());
    }

    /**
     * Sets Actions field.
     *
     * @param Action[]|null $value
     */
    public function actions(?array $value): self
    {
        $this->instance->setActions($value);
        return $this;
    }

    /**
     * Initializes a new Actions object.
     */
    public function build(): Actions
    {
        return CoreHelper::clone($this->instance);
    }
}
