<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\AddressForOrganisation;

/**
 * Builder for model AddressForOrganisation
 *
 * @see AddressForOrganisation
 */
class AddressForOrganisationBuilder
{
    /**
     * @var AddressForOrganisation
     */
    private $instance;

    private function __construct(AddressForOrganisation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Address For Organisation Builder object.
     */
    public static function init(): self
    {
        return new self(new AddressForOrganisation());
    }

    /**
     * Sets Address Line 1 field.
     *
     * @param string|null $value
     */
    public function addressLine1(?string $value): self
    {
        $this->instance->setAddressLine1($value);
        return $this;
    }

    /**
     * Sets Address Line 2 field.
     *
     * @param string|null $value
     */
    public function addressLine2(?string $value): self
    {
        $this->instance->setAddressLine2($value);
        return $this;
    }

    /**
     * Sets Address Line 3 field.
     *
     * @param string|null $value
     */
    public function addressLine3(?string $value): self
    {
        $this->instance->setAddressLine3($value);
        return $this;
    }

    /**
     * Sets Address Line 4 field.
     *
     * @param string|null $value
     */
    public function addressLine4(?string $value): self
    {
        $this->instance->setAddressLine4($value);
        return $this;
    }

    /**
     * Sets Address Type field.
     *
     * @param string|null $value
     */
    public function addressType(?string $value): self
    {
        $this->instance->setAddressType($value);
        return $this;
    }

    /**
     * Sets Attention To field.
     *
     * @param string|null $value
     */
    public function attentionTo(?string $value): self
    {
        $this->instance->setAttentionTo($value);
        return $this;
    }

    /**
     * Sets City field.
     *
     * @param string|null $value
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets Country field.
     *
     * @param string|null $value
     */
    public function country(?string $value): self
    {
        $this->instance->setCountry($value);
        return $this;
    }

    /**
     * Sets Postal Code field.
     *
     * @param string|null $value
     */
    public function postalCode(?string $value): self
    {
        $this->instance->setPostalCode($value);
        return $this;
    }

    /**
     * Sets Region field.
     *
     * @param string|null $value
     */
    public function region(?string $value): self
    {
        $this->instance->setRegion($value);
        return $this;
    }

    /**
     * Initializes a new Address For Organisation object.
     */
    public function build(): AddressForOrganisation
    {
        return CoreHelper::clone($this->instance);
    }
}
