<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\Allocation;
use XeroAccountingAPILib\Models\Allocations;

/**
 * Builder for model Allocations
 *
 * @see Allocations
 */
class AllocationsBuilder
{
    /**
     * @var Allocations
     */
    private $instance;

    private function __construct(Allocations $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Allocations Builder object.
     */
    public static function init(): self
    {
        return new self(new Allocations());
    }

    /**
     * Sets Allocations field.
     *
     * @param Allocation[]|null $value
     */
    public function allocations(?array $value): self
    {
        $this->instance->setAllocations($value);
        return $this;
    }

    /**
     * Initializes a new Allocations object.
     */
    public function build(): Allocations
    {
        return CoreHelper::clone($this->instance);
    }
}
