<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\AccountsPayable;
use XeroAccountingAPILib\Models\AccountsReceivable;
use XeroAccountingAPILib\Models\Balances;

/**
 * Builder for model Balances
 *
 * @see Balances
 */
class BalancesBuilder
{
    /**
     * @var Balances
     */
    private $instance;

    private function __construct(Balances $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Balances Builder object.
     */
    public static function init(): self
    {
        return new self(new Balances());
    }

    /**
     * Sets Accounts Payable field.
     *
     * @param AccountsPayable|null $value
     */
    public function accountsPayable(?AccountsPayable $value): self
    {
        $this->instance->setAccountsPayable($value);
        return $this;
    }

    /**
     * Sets Accounts Receivable field.
     *
     * @param AccountsReceivable|null $value
     */
    public function accountsReceivable(?AccountsReceivable $value): self
    {
        $this->instance->setAccountsReceivable($value);
        return $this;
    }

    /**
     * Initializes a new Balances object.
     */
    public function build(): Balances
    {
        return CoreHelper::clone($this->instance);
    }
}
