<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\BalanceDetails;

/**
 * Builder for model BalanceDetails
 *
 * @see BalanceDetails
 */
class BalanceDetailsBuilder
{
    /**
     * @var BalanceDetails
     */
    private $instance;

    private function __construct(BalanceDetails $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Balance Details Builder object.
     */
    public static function init(): self
    {
        return new self(new BalanceDetails());
    }

    /**
     * Sets Balance field.
     *
     * @param float|null $value
     */
    public function balance(?float $value): self
    {
        $this->instance->setBalance($value);
        return $this;
    }

    /**
     * Sets Currency Code field.
     *
     * @param string|null $value
     */
    public function currencyCode(?string $value): self
    {
        $this->instance->setCurrencyCode($value);
        return $this;
    }

    /**
     * Sets Currency Rate field.
     *
     * @param float|null $value
     */
    public function currencyRate(?float $value): self
    {
        $this->instance->setCurrencyRate($value);
        return $this;
    }

    /**
     * Initializes a new Balance Details object.
     */
    public function build(): BalanceDetails
    {
        return CoreHelper::clone($this->instance);
    }
}
