<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\Account;
use XeroAccountingAPILib\Models\BankTransaction;
use XeroAccountingAPILib\Models\Contact;
use XeroAccountingAPILib\Models\LineItem;
use XeroAccountingAPILib\Models\ValidationError;

/**
 * Builder for model BankTransaction
 *
 * @see BankTransaction
 */
class BankTransactionBuilder
{
    /**
     * @var BankTransaction
     */
    private $instance;

    private function __construct(BankTransaction $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Bank Transaction Builder object.
     *
     * @param Account $bankAccount
     * @param LineItem[] $lineItems
     * @param string $type
     */
    public static function init(Account $bankAccount, array $lineItems, string $type): self
    {
        return new self(new BankTransaction($bankAccount, $lineItems, $type));
    }

    /**
     * Sets Bank Transaction ID field.
     *
     * @param string|null $value
     */
    public function bankTransactionID(?string $value): self
    {
        $this->instance->setBankTransactionID($value);
        return $this;
    }

    /**
     * Sets Contact field.
     *
     * @param Contact|null $value
     */
    public function contact(?Contact $value): self
    {
        $this->instance->setContact($value);
        return $this;
    }

    /**
     * Sets Currency Code field.
     *
     * @param string|null $value
     */
    public function currencyCode(?string $value): self
    {
        $this->instance->setCurrencyCode($value);
        return $this;
    }

    /**
     * Sets Currency Rate field.
     *
     * @param float|null $value
     */
    public function currencyRate(?float $value): self
    {
        $this->instance->setCurrencyRate($value);
        return $this;
    }

    /**
     * Sets Date field.
     *
     * @param string|null $value
     */
    public function date(?string $value): self
    {
        $this->instance->setDate($value);
        return $this;
    }

    /**
     * Sets Has Attachments field.
     *
     * @param bool|null $value
     */
    public function hasAttachments(?bool $value): self
    {
        $this->instance->setHasAttachments($value);
        return $this;
    }

    /**
     * Sets Is Reconciled field.
     *
     * @param bool|null $value
     */
    public function isReconciled(?bool $value): self
    {
        $this->instance->setIsReconciled($value);
        return $this;
    }

    /**
     * Sets Line Amount Types field.
     *
     * @param string|null $value
     */
    public function lineAmountTypes(?string $value): self
    {
        $this->instance->setLineAmountTypes($value);
        return $this;
    }

    /**
     * Sets Overpayment ID field.
     *
     * @param string|null $value
     */
    public function overpaymentID(?string $value): self
    {
        $this->instance->setOverpaymentID($value);
        return $this;
    }

    /**
     * Sets Prepayment ID field.
     *
     * @param string|null $value
     */
    public function prepaymentID(?string $value): self
    {
        $this->instance->setPrepaymentID($value);
        return $this;
    }

    /**
     * Sets Reference field.
     *
     * @param string|null $value
     */
    public function reference(?string $value): self
    {
        $this->instance->setReference($value);
        return $this;
    }

    /**
     * Sets Status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets Status Attribute String field.
     *
     * @param string|null $value
     */
    public function statusAttributeString(?string $value): self
    {
        $this->instance->setStatusAttributeString($value);
        return $this;
    }

    /**
     * Sets Sub Total field.
     *
     * @param float|null $value
     */
    public function subTotal(?float $value): self
    {
        $this->instance->setSubTotal($value);
        return $this;
    }

    /**
     * Sets Total field.
     *
     * @param float|null $value
     */
    public function total(?float $value): self
    {
        $this->instance->setTotal($value);
        return $this;
    }

    /**
     * Sets Total Tax field.
     *
     * @param float|null $value
     */
    public function totalTax(?float $value): self
    {
        $this->instance->setTotalTax($value);
        return $this;
    }

    /**
     * Sets Updated Date UTC field.
     *
     * @param string|null $value
     */
    public function updatedDateUTC(?string $value): self
    {
        $this->instance->setUpdatedDateUTC($value);
        return $this;
    }

    /**
     * Sets Url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Sets Validation Errors field.
     *
     * @param ValidationError[]|null $value
     */
    public function validationErrors(?array $value): self
    {
        $this->instance->setValidationErrors($value);
        return $this;
    }

    /**
     * Initializes a new Bank Transaction object.
     */
    public function build(): BankTransaction
    {
        return CoreHelper::clone($this->instance);
    }
}
