<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\BankTransaction;
use XeroAccountingAPILib\Models\BankTransactions;

/**
 * Builder for model BankTransactions
 *
 * @see BankTransactions
 */
class BankTransactionsBuilder
{
    /**
     * @var BankTransactions
     */
    private $instance;

    private function __construct(BankTransactions $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Bank Transactions Builder object.
     */
    public static function init(): self
    {
        return new self(new BankTransactions());
    }

    /**
     * Sets Bank Transactions field.
     *
     * @param BankTransaction[]|null $value
     */
    public function bankTransactions(?array $value): self
    {
        $this->instance->setBankTransactions($value);
        return $this;
    }

    /**
     * Initializes a new Bank Transactions object.
     */
    public function build(): BankTransactions
    {
        return CoreHelper::clone($this->instance);
    }
}
