<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\Account;
use XeroAccountingAPILib\Models\BankTransfer;
use XeroAccountingAPILib\Models\ValidationError;

/**
 * Builder for model BankTransfer
 *
 * @see BankTransfer
 */
class BankTransferBuilder
{
    /**
     * @var BankTransfer
     */
    private $instance;

    private function __construct(BankTransfer $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Bank Transfer Builder object.
     *
     * @param float $amount
     * @param Account $fromBankAccount
     * @param Account $toBankAccount
     */
    public static function init(float $amount, Account $fromBankAccount, Account $toBankAccount): self
    {
        return new self(new BankTransfer($amount, $fromBankAccount, $toBankAccount));
    }

    /**
     * Sets Bank Transfer ID field.
     *
     * @param string|null $value
     */
    public function bankTransferID(?string $value): self
    {
        $this->instance->setBankTransferID($value);
        return $this;
    }

    /**
     * Sets Created Date UTC field.
     *
     * @param string|null $value
     */
    public function createdDateUTC(?string $value): self
    {
        $this->instance->setCreatedDateUTC($value);
        return $this;
    }

    /**
     * Sets Currency Rate field.
     *
     * @param float|null $value
     */
    public function currencyRate(?float $value): self
    {
        $this->instance->setCurrencyRate($value);
        return $this;
    }

    /**
     * Sets Date field.
     *
     * @param string|null $value
     */
    public function date(?string $value): self
    {
        $this->instance->setDate($value);
        return $this;
    }

    /**
     * Sets From Bank Transaction ID field.
     *
     * @param string|null $value
     */
    public function fromBankTransactionID(?string $value): self
    {
        $this->instance->setFromBankTransactionID($value);
        return $this;
    }

    /**
     * Sets Has Attachments field.
     *
     * @param bool|null $value
     */
    public function hasAttachments(?bool $value): self
    {
        $this->instance->setHasAttachments($value);
        return $this;
    }

    /**
     * Sets To Bank Transaction ID field.
     *
     * @param string|null $value
     */
    public function toBankTransactionID(?string $value): self
    {
        $this->instance->setToBankTransactionID($value);
        return $this;
    }

    /**
     * Sets Validation Errors field.
     *
     * @param ValidationError[]|null $value
     */
    public function validationErrors(?array $value): self
    {
        $this->instance->setValidationErrors($value);
        return $this;
    }

    /**
     * Initializes a new Bank Transfer object.
     */
    public function build(): BankTransfer
    {
        return CoreHelper::clone($this->instance);
    }
}
