<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\BrandingTheme;
use XeroAccountingAPILib\Models\BrandingThemes;

/**
 * Builder for model BrandingThemes
 *
 * @see BrandingThemes
 */
class BrandingThemesBuilder
{
    /**
     * @var BrandingThemes
     */
    private $instance;

    private function __construct(BrandingThemes $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Branding Themes Builder object.
     */
    public static function init(): self
    {
        return new self(new BrandingThemes());
    }

    /**
     * Sets Branding Themes field.
     *
     * @param BrandingTheme[]|null $value
     */
    public function brandingThemes(?array $value): self
    {
        $this->instance->setBrandingThemes($value);
        return $this;
    }

    /**
     * Initializes a new Branding Themes object.
     */
    public function build(): BrandingThemes
    {
        return CoreHelper::clone($this->instance);
    }
}
