<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\CISSetting;
use XeroAccountingAPILib\Models\CISSettings;

/**
 * Builder for model CISSettings
 *
 * @see CISSettings
 */
class CISSettingsBuilder
{
    /**
     * @var CISSettings
     */
    private $instance;

    private function __construct(CISSettings $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new CIS Settings Builder object.
     */
    public static function init(): self
    {
        return new self(new CISSettings());
    }

    /**
     * Sets CIS Settings field.
     *
     * @param CISSetting[]|null $value
     */
    public function cISSettings(?array $value): self
    {
        $this->instance->setCISSettings($value);
        return $this;
    }

    /**
     * Initializes a new CIS Settings object.
     */
    public function build(): CISSettings
    {
        return CoreHelper::clone($this->instance);
    }
}
