<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\ContactGroup;
use XeroAccountingAPILib\Models\ContactGroups;

/**
 * Builder for model ContactGroups
 *
 * @see ContactGroups
 */
class ContactGroupsBuilder
{
    /**
     * @var ContactGroups
     */
    private $instance;

    private function __construct(ContactGroups $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Contact Groups Builder object.
     */
    public static function init(): self
    {
        return new self(new ContactGroups());
    }

    /**
     * Sets Contact Groups field.
     *
     * @param ContactGroup[]|null $value
     */
    public function contactGroups(?array $value): self
    {
        $this->instance->setContactGroups($value);
        return $this;
    }

    /**
     * Initializes a new Contact Groups object.
     */
    public function build(): ContactGroups
    {
        return CoreHelper::clone($this->instance);
    }
}
