<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\Address;
use XeroAccountingAPILib\Models\Attachment;
use XeroAccountingAPILib\Models\Balances;
use XeroAccountingAPILib\Models\BatchPaymentDetails;
use XeroAccountingAPILib\Models\BrandingTheme;
use XeroAccountingAPILib\Models\Contact;
use XeroAccountingAPILib\Models\ContactGroup;
use XeroAccountingAPILib\Models\ContactPerson;
use XeroAccountingAPILib\Models\PaymentTerm;
use XeroAccountingAPILib\Models\Phone;
use XeroAccountingAPILib\Models\SalesTrackingCategory;
use XeroAccountingAPILib\Models\ValidationError;

/**
 * Builder for model Contact
 *
 * @see Contact
 */
class ContactBuilder
{
    /**
     * @var Contact
     */
    private $instance;

    private function __construct(Contact $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Contact Builder object.
     */
    public static function init(): self
    {
        return new self(new Contact());
    }

    /**
     * Sets Account Number field.
     *
     * @param string|null $value
     */
    public function accountNumber(?string $value): self
    {
        $this->instance->setAccountNumber($value);
        return $this;
    }

    /**
     * Sets Accounts Payable Tax Type field.
     *
     * @param string|null $value
     */
    public function accountsPayableTaxType(?string $value): self
    {
        $this->instance->setAccountsPayableTaxType($value);
        return $this;
    }

    /**
     * Sets Accounts Receivable Tax Type field.
     *
     * @param string|null $value
     */
    public function accountsReceivableTaxType(?string $value): self
    {
        $this->instance->setAccountsReceivableTaxType($value);
        return $this;
    }

    /**
     * Sets Addresses field.
     *
     * @param Address[]|null $value
     */
    public function addresses(?array $value): self
    {
        $this->instance->setAddresses($value);
        return $this;
    }

    /**
     * Sets Attachments field.
     *
     * @param Attachment[]|null $value
     */
    public function attachments(?array $value): self
    {
        $this->instance->setAttachments($value);
        return $this;
    }

    /**
     * Sets Balances field.
     *
     * @param Balances|null $value
     */
    public function balances(?Balances $value): self
    {
        $this->instance->setBalances($value);
        return $this;
    }

    /**
     * Sets Bank Account Details field.
     *
     * @param string|null $value
     */
    public function bankAccountDetails(?string $value): self
    {
        $this->instance->setBankAccountDetails($value);
        return $this;
    }

    /**
     * Sets Batch Payments field.
     *
     * @param BatchPaymentDetails|null $value
     */
    public function batchPayments(?BatchPaymentDetails $value): self
    {
        $this->instance->setBatchPayments($value);
        return $this;
    }

    /**
     * Sets Branding Theme field.
     *
     * @param BrandingTheme|null $value
     */
    public function brandingTheme(?BrandingTheme $value): self
    {
        $this->instance->setBrandingTheme($value);
        return $this;
    }

    /**
     * Sets Contact Groups field.
     *
     * @param ContactGroup[]|null $value
     */
    public function contactGroups(?array $value): self
    {
        $this->instance->setContactGroups($value);
        return $this;
    }

    /**
     * Sets Contact ID field.
     *
     * @param string|null $value
     */
    public function contactID(?string $value): self
    {
        $this->instance->setContactID($value);
        return $this;
    }

    /**
     * Sets Contact Number field.
     *
     * @param string|null $value
     */
    public function contactNumber(?string $value): self
    {
        $this->instance->setContactNumber($value);
        return $this;
    }

    /**
     * Sets Contact Persons field.
     *
     * @param ContactPerson[]|null $value
     */
    public function contactPersons(?array $value): self
    {
        $this->instance->setContactPersons($value);
        return $this;
    }

    /**
     * Sets Contact Status field.
     *
     * @param string|null $value
     */
    public function contactStatus(?string $value): self
    {
        $this->instance->setContactStatus($value);
        return $this;
    }

    /**
     * Sets Default Currency field.
     *
     * @param string|null $value
     */
    public function defaultCurrency(?string $value): self
    {
        $this->instance->setDefaultCurrency($value);
        return $this;
    }

    /**
     * Sets Discount field.
     *
     * @param float|null $value
     */
    public function discount(?float $value): self
    {
        $this->instance->setDiscount($value);
        return $this;
    }

    /**
     * Sets Email Address field.
     *
     * @param string|null $value
     */
    public function emailAddress(?string $value): self
    {
        $this->instance->setEmailAddress($value);
        return $this;
    }

    /**
     * Sets First Name field.
     *
     * @param string|null $value
     */
    public function firstName(?string $value): self
    {
        $this->instance->setFirstName($value);
        return $this;
    }

    /**
     * Sets Has Attachments field.
     *
     * @param bool|null $value
     */
    public function hasAttachments(?bool $value): self
    {
        $this->instance->setHasAttachments($value);
        return $this;
    }

    /**
     * Sets Has Validation Errors field.
     *
     * @param bool|null $value
     */
    public function hasValidationErrors(?bool $value): self
    {
        $this->instance->setHasValidationErrors($value);
        return $this;
    }

    /**
     * Sets Is Customer field.
     *
     * @param bool|null $value
     */
    public function isCustomer(?bool $value): self
    {
        $this->instance->setIsCustomer($value);
        return $this;
    }

    /**
     * Sets Is Supplier field.
     *
     * @param bool|null $value
     */
    public function isSupplier(?bool $value): self
    {
        $this->instance->setIsSupplier($value);
        return $this;
    }

    /**
     * Sets Last Name field.
     *
     * @param string|null $value
     */
    public function lastName(?string $value): self
    {
        $this->instance->setLastName($value);
        return $this;
    }

    /**
     * Sets Name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets Payment Terms field.
     *
     * @param PaymentTerm|null $value
     */
    public function paymentTerms(?PaymentTerm $value): self
    {
        $this->instance->setPaymentTerms($value);
        return $this;
    }

    /**
     * Sets Phones field.
     *
     * @param Phone[]|null $value
     */
    public function phones(?array $value): self
    {
        $this->instance->setPhones($value);
        return $this;
    }

    /**
     * Sets Purchases Default Account Code field.
     *
     * @param string|null $value
     */
    public function purchasesDefaultAccountCode(?string $value): self
    {
        $this->instance->setPurchasesDefaultAccountCode($value);
        return $this;
    }

    /**
     * Sets Purchases Tracking Categories field.
     *
     * @param SalesTrackingCategory[]|null $value
     */
    public function purchasesTrackingCategories(?array $value): self
    {
        $this->instance->setPurchasesTrackingCategories($value);
        return $this;
    }

    /**
     * Sets Sales Default Account Code field.
     *
     * @param string|null $value
     */
    public function salesDefaultAccountCode(?string $value): self
    {
        $this->instance->setSalesDefaultAccountCode($value);
        return $this;
    }

    /**
     * Sets Sales Tracking Categories field.
     *
     * @param SalesTrackingCategory[]|null $value
     */
    public function salesTrackingCategories(?array $value): self
    {
        $this->instance->setSalesTrackingCategories($value);
        return $this;
    }

    /**
     * Sets Skype User Name field.
     *
     * @param string|null $value
     */
    public function skypeUserName(?string $value): self
    {
        $this->instance->setSkypeUserName($value);
        return $this;
    }

    /**
     * Sets Status Attribute String field.
     *
     * @param string|null $value
     */
    public function statusAttributeString(?string $value): self
    {
        $this->instance->setStatusAttributeString($value);
        return $this;
    }

    /**
     * Sets Tax Number field.
     *
     * @param string|null $value
     */
    public function taxNumber(?string $value): self
    {
        $this->instance->setTaxNumber($value);
        return $this;
    }

    /**
     * Sets Tracking Category Name field.
     *
     * @param string|null $value
     */
    public function trackingCategoryName(?string $value): self
    {
        $this->instance->setTrackingCategoryName($value);
        return $this;
    }

    /**
     * Sets Tracking Category Option field.
     *
     * @param string|null $value
     */
    public function trackingCategoryOption(?string $value): self
    {
        $this->instance->setTrackingCategoryOption($value);
        return $this;
    }

    /**
     * Sets Updated Date UTC field.
     *
     * @param string|null $value
     */
    public function updatedDateUTC(?string $value): self
    {
        $this->instance->setUpdatedDateUTC($value);
        return $this;
    }

    /**
     * Sets Validation Errors field.
     *
     * @param ValidationError[]|null $value
     */
    public function validationErrors(?array $value): self
    {
        $this->instance->setValidationErrors($value);
        return $this;
    }

    /**
     * Sets Website field.
     *
     * @param string|null $value
     */
    public function website(?string $value): self
    {
        $this->instance->setWebsite($value);
        return $this;
    }

    /**
     * Sets Xero Network Key field.
     *
     * @param string|null $value
     */
    public function xeroNetworkKey(?string $value): self
    {
        $this->instance->setXeroNetworkKey($value);
        return $this;
    }

    /**
     * Initializes a new Contact object.
     */
    public function build(): Contact
    {
        return CoreHelper::clone($this->instance);
    }
}
