<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\Contact;
use XeroAccountingAPILib\Models\ContactGroup;

/**
 * Builder for model ContactGroup
 *
 * @see ContactGroup
 */
class ContactGroupBuilder
{
    /**
     * @var ContactGroup
     */
    private $instance;

    private function __construct(ContactGroup $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Contact Group Builder object.
     */
    public static function init(): self
    {
        return new self(new ContactGroup());
    }

    /**
     * Sets Contact Group ID field.
     *
     * @param string|null $value
     */
    public function contactGroupID(?string $value): self
    {
        $this->instance->setContactGroupID($value);
        return $this;
    }

    /**
     * Sets Contacts field.
     *
     * @param Contact[]|null $value
     */
    public function contacts(?array $value): self
    {
        $this->instance->setContacts($value);
        return $this;
    }

    /**
     * Sets Name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets Status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Initializes a new Contact Group object.
     */
    public function build(): ContactGroup
    {
        return CoreHelper::clone($this->instance);
    }
}
