<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\Allocation;
use XeroAccountingAPILib\Models\Contact;
use XeroAccountingAPILib\Models\CreditNote;
use XeroAccountingAPILib\Models\LineItem;
use XeroAccountingAPILib\Models\Payment;
use XeroAccountingAPILib\Models\ValidationError;

/**
 * Builder for model CreditNote
 *
 * @see CreditNote
 */
class CreditNoteBuilder
{
    /**
     * @var CreditNote
     */
    private $instance;

    private function __construct(CreditNote $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Credit Note Builder object.
     */
    public static function init(): self
    {
        return new self(new CreditNote());
    }

    /**
     * Sets Allocations field.
     *
     * @param Allocation[]|null $value
     */
    public function allocations(?array $value): self
    {
        $this->instance->setAllocations($value);
        return $this;
    }

    /**
     * Sets Applied Amount field.
     *
     * @param float|null $value
     */
    public function appliedAmount(?float $value): self
    {
        $this->instance->setAppliedAmount($value);
        return $this;
    }

    /**
     * Sets Branding Theme ID field.
     *
     * @param string|null $value
     */
    public function brandingThemeID(?string $value): self
    {
        $this->instance->setBrandingThemeID($value);
        return $this;
    }

    /**
     * Sets CIS Deduction field.
     *
     * @param float|null $value
     */
    public function cISDeduction(?float $value): self
    {
        $this->instance->setCISDeduction($value);
        return $this;
    }

    /**
     * Sets CIS Rate field.
     *
     * @param float|null $value
     */
    public function cISRate(?float $value): self
    {
        $this->instance->setCISRate($value);
        return $this;
    }

    /**
     * Sets Contact field.
     *
     * @param Contact|null $value
     */
    public function contact(?Contact $value): self
    {
        $this->instance->setContact($value);
        return $this;
    }

    /**
     * Sets Credit Note ID field.
     *
     * @param string|null $value
     */
    public function creditNoteID(?string $value): self
    {
        $this->instance->setCreditNoteID($value);
        return $this;
    }

    /**
     * Sets Credit Note Number field.
     *
     * @param string|null $value
     */
    public function creditNoteNumber(?string $value): self
    {
        $this->instance->setCreditNoteNumber($value);
        return $this;
    }

    /**
     * Sets Currency Code field.
     *
     * @param string|null $value
     */
    public function currencyCode(?string $value): self
    {
        $this->instance->setCurrencyCode($value);
        return $this;
    }

    /**
     * Sets Currency Rate field.
     *
     * @param float|null $value
     */
    public function currencyRate(?float $value): self
    {
        $this->instance->setCurrencyRate($value);
        return $this;
    }

    /**
     * Sets Date field.
     *
     * @param string|null $value
     */
    public function date(?string $value): self
    {
        $this->instance->setDate($value);
        return $this;
    }

    /**
     * Sets Due Date field.
     *
     * @param string|null $value
     */
    public function dueDate(?string $value): self
    {
        $this->instance->setDueDate($value);
        return $this;
    }

    /**
     * Sets Fully Paid On Date field.
     *
     * @param string|null $value
     */
    public function fullyPaidOnDate(?string $value): self
    {
        $this->instance->setFullyPaidOnDate($value);
        return $this;
    }

    /**
     * Sets Has Attachments field.
     *
     * @param bool|null $value
     */
    public function hasAttachments(?bool $value): self
    {
        $this->instance->setHasAttachments($value);
        return $this;
    }

    /**
     * Sets Has Errors field.
     *
     * @param bool|null $value
     */
    public function hasErrors(?bool $value): self
    {
        $this->instance->setHasErrors($value);
        return $this;
    }

    /**
     * Sets Line Amount Types field.
     *
     * @param string|null $value
     */
    public function lineAmountTypes(?string $value): self
    {
        $this->instance->setLineAmountTypes($value);
        return $this;
    }

    /**
     * Sets Line Items field.
     *
     * @param LineItem[]|null $value
     */
    public function lineItems(?array $value): self
    {
        $this->instance->setLineItems($value);
        return $this;
    }

    /**
     * Sets Payments field.
     *
     * @param Payment[]|null $value
     */
    public function payments(?array $value): self
    {
        $this->instance->setPayments($value);
        return $this;
    }

    /**
     * Sets Reference field.
     *
     * @param string|null $value
     */
    public function reference(?string $value): self
    {
        $this->instance->setReference($value);
        return $this;
    }

    /**
     * Sets Remaining Credit field.
     *
     * @param float|null $value
     */
    public function remainingCredit(?float $value): self
    {
        $this->instance->setRemainingCredit($value);
        return $this;
    }

    /**
     * Sets Sent To Contact field.
     *
     * @param bool|null $value
     */
    public function sentToContact(?bool $value): self
    {
        $this->instance->setSentToContact($value);
        return $this;
    }

    /**
     * Sets Status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets Status Attribute String field.
     *
     * @param string|null $value
     */
    public function statusAttributeString(?string $value): self
    {
        $this->instance->setStatusAttributeString($value);
        return $this;
    }

    /**
     * Sets Sub Total field.
     *
     * @param float|null $value
     */
    public function subTotal(?float $value): self
    {
        $this->instance->setSubTotal($value);
        return $this;
    }

    /**
     * Sets Total field.
     *
     * @param float|null $value
     */
    public function total(?float $value): self
    {
        $this->instance->setTotal($value);
        return $this;
    }

    /**
     * Sets Total Tax field.
     *
     * @param float|null $value
     */
    public function totalTax(?float $value): self
    {
        $this->instance->setTotalTax($value);
        return $this;
    }

    /**
     * Sets Type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets Updated Date UTC field.
     *
     * @param string|null $value
     */
    public function updatedDateUTC(?string $value): self
    {
        $this->instance->setUpdatedDateUTC($value);
        return $this;
    }

    /**
     * Sets Validation Errors field.
     *
     * @param ValidationError[]|null $value
     */
    public function validationErrors(?array $value): self
    {
        $this->instance->setValidationErrors($value);
        return $this;
    }

    /**
     * Sets Warnings field.
     *
     * @param ValidationError[]|null $value
     */
    public function warnings(?array $value): self
    {
        $this->instance->setWarnings($value);
        return $this;
    }

    /**
     * Initializes a new Credit Note object.
     */
    public function build(): CreditNote
    {
        return CoreHelper::clone($this->instance);
    }
}
