<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\Element;
use XeroAccountingAPILib\Models\ValidationError;

/**
 * Builder for model Element
 *
 * @see Element
 */
class ElementBuilder
{
    /**
     * @var Element
     */
    private $instance;

    private function __construct(Element $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Element Builder object.
     */
    public static function init(): self
    {
        return new self(new Element());
    }

    /**
     * Sets Bank Transaction ID field.
     *
     * @param string|null $value
     */
    public function bankTransactionID(?string $value): self
    {
        $this->instance->setBankTransactionID($value);
        return $this;
    }

    /**
     * Sets Batch Payment ID field.
     *
     * @param string|null $value
     */
    public function batchPaymentID(?string $value): self
    {
        $this->instance->setBatchPaymentID($value);
        return $this;
    }

    /**
     * Sets Contact ID field.
     *
     * @param string|null $value
     */
    public function contactID(?string $value): self
    {
        $this->instance->setContactID($value);
        return $this;
    }

    /**
     * Sets Credit Note ID field.
     *
     * @param string|null $value
     */
    public function creditNoteID(?string $value): self
    {
        $this->instance->setCreditNoteID($value);
        return $this;
    }

    /**
     * Sets Invoice ID field.
     *
     * @param string|null $value
     */
    public function invoiceID(?string $value): self
    {
        $this->instance->setInvoiceID($value);
        return $this;
    }

    /**
     * Sets Item ID field.
     *
     * @param string|null $value
     */
    public function itemID(?string $value): self
    {
        $this->instance->setItemID($value);
        return $this;
    }

    /**
     * Sets Purchase Order ID field.
     *
     * @param string|null $value
     */
    public function purchaseOrderID(?string $value): self
    {
        $this->instance->setPurchaseOrderID($value);
        return $this;
    }

    /**
     * Sets Validation Errors field.
     *
     * @param ValidationError[]|null $value
     */
    public function validationErrors(?array $value): self
    {
        $this->instance->setValidationErrors($value);
        return $this;
    }

    /**
     * Initializes a new Element object.
     */
    public function build(): Element
    {
        return CoreHelper::clone($this->instance);
    }
}
