<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\Employee;
use XeroAccountingAPILib\Models\Employees;

/**
 * Builder for model Employees
 *
 * @see Employees
 */
class EmployeesBuilder
{
    /**
     * @var Employees
     */
    private $instance;

    private function __construct(Employees $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Employees Builder object.
     */
    public static function init(): self
    {
        return new self(new Employees());
    }

    /**
     * Sets Employees field.
     *
     * @param Employee[]|null $value
     */
    public function employees(?array $value): self
    {
        $this->instance->setEmployees($value);
        return $this;
    }

    /**
     * Initializes a new Employees object.
     */
    public function build(): Employees
    {
        return CoreHelper::clone($this->instance);
    }
}
