<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\ExpenseClaim;
use XeroAccountingAPILib\Models\ExpenseClaims;

/**
 * Builder for model ExpenseClaims
 *
 * @see ExpenseClaims
 */
class ExpenseClaimsBuilder
{
    /**
     * @var ExpenseClaims
     */
    private $instance;

    private function __construct(ExpenseClaims $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Expense Claims Builder object.
     */
    public static function init(): self
    {
        return new self(new ExpenseClaims());
    }

    /**
     * Sets Expense Claims field.
     *
     * @param ExpenseClaim[]|null $value
     */
    public function expenseClaims(?array $value): self
    {
        $this->instance->setExpenseClaims($value);
        return $this;
    }

    /**
     * Initializes a new Expense Claims object.
     */
    public function build(): ExpenseClaims
    {
        return CoreHelper::clone($this->instance);
    }
}
