<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\ExternalLink;

/**
 * Builder for model ExternalLink
 *
 * @see ExternalLink
 */
class ExternalLinkBuilder
{
    /**
     * @var ExternalLink
     */
    private $instance;

    private function __construct(ExternalLink $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new External Link Builder object.
     */
    public static function init(): self
    {
        return new self(new ExternalLink());
    }

    /**
     * Sets Description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets Link Type field.
     *
     * @param string|null $value
     */
    public function linkType(?string $value): self
    {
        $this->instance->setLinkType($value);
        return $this;
    }

    /**
     * Sets Url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Initializes a new External Link object.
     */
    public function build(): ExternalLink
    {
        return CoreHelper::clone($this->instance);
    }
}
