<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\HistoryRecord;

/**
 * Builder for model HistoryRecord
 *
 * @see HistoryRecord
 */
class HistoryRecordBuilder
{
    /**
     * @var HistoryRecord
     */
    private $instance;

    private function __construct(HistoryRecord $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new History Record Builder object.
     */
    public static function init(): self
    {
        return new self(new HistoryRecord());
    }

    /**
     * Sets Changes field.
     *
     * @param string|null $value
     */
    public function changes(?string $value): self
    {
        $this->instance->setChanges($value);
        return $this;
    }

    /**
     * Sets Date UTC field.
     *
     * @param string|null $value
     */
    public function dateUTC(?string $value): self
    {
        $this->instance->setDateUTC($value);
        return $this;
    }

    /**
     * Sets Details field.
     *
     * @param string|null $value
     */
    public function details(?string $value): self
    {
        $this->instance->setDetails($value);
        return $this;
    }

    /**
     * Sets User field.
     *
     * @param string|null $value
     */
    public function user(?string $value): self
    {
        $this->instance->setUser($value);
        return $this;
    }

    /**
     * Initializes a new History Record object.
     */
    public function build(): HistoryRecord
    {
        return CoreHelper::clone($this->instance);
    }
}
