<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\HistoryRecord;
use XeroAccountingAPILib\Models\HistoryRecords;

/**
 * Builder for model HistoryRecords
 *
 * @see HistoryRecords
 */
class HistoryRecordsBuilder
{
    /**
     * @var HistoryRecords
     */
    private $instance;

    private function __construct(HistoryRecords $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new History Records Builder object.
     */
    public static function init(): self
    {
        return new self(new HistoryRecords());
    }

    /**
     * Sets History Records field.
     *
     * @param HistoryRecord[]|null $value
     */
    public function historyRecords(?array $value): self
    {
        $this->instance->setHistoryRecords($value);
        return $this;
    }

    /**
     * Initializes a new History Records object.
     */
    public function build(): HistoryRecords
    {
        return CoreHelper::clone($this->instance);
    }
}
