<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\ImportSummaryAccounts;

/**
 * Builder for model ImportSummaryAccounts
 *
 * @see ImportSummaryAccounts
 */
class ImportSummaryAccountsBuilder
{
    /**
     * @var ImportSummaryAccounts
     */
    private $instance;

    private function __construct(ImportSummaryAccounts $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Import Summary Accounts Builder object.
     */
    public static function init(): self
    {
        return new self(new ImportSummaryAccounts());
    }

    /**
     * Sets Deleted field.
     *
     * @param float|null $value
     */
    public function deleted(?float $value): self
    {
        $this->instance->setDeleted($value);
        return $this;
    }

    /**
     * Sets Errored field.
     *
     * @param float|null $value
     */
    public function errored(?float $value): self
    {
        $this->instance->setErrored($value);
        return $this;
    }

    /**
     * Sets Locked field.
     *
     * @param float|null $value
     */
    public function locked(?float $value): self
    {
        $this->instance->setLocked($value);
        return $this;
    }

    /**
     * Sets New field.
     *
     * @param float|null $value
     */
    public function new(?float $value): self
    {
        $this->instance->setNew($value);
        return $this;
    }

    /**
     * Sets New Or Updated field.
     *
     * @param float|null $value
     */
    public function newOrUpdated(?float $value): self
    {
        $this->instance->setNewOrUpdated($value);
        return $this;
    }

    /**
     * Sets Present field.
     *
     * @param bool|null $value
     */
    public function present(?bool $value): self
    {
        $this->instance->setPresent($value);
        return $this;
    }

    /**
     * Sets System field.
     *
     * @param float|null $value
     */
    public function system(?float $value): self
    {
        $this->instance->setSystem($value);
        return $this;
    }

    /**
     * Sets Total field.
     *
     * @param float|null $value
     */
    public function total(?float $value): self
    {
        $this->instance->setTotal($value);
        return $this;
    }

    /**
     * Sets Updated field.
     *
     * @param float|null $value
     */
    public function updated(?float $value): self
    {
        $this->instance->setUpdated($value);
        return $this;
    }

    /**
     * Initializes a new Import Summary Accounts object.
     */
    public function build(): ImportSummaryAccounts
    {
        return CoreHelper::clone($this->instance);
    }
}
