<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\ImportSummaryOrganisation;

/**
 * Builder for model ImportSummaryOrganisation
 *
 * @see ImportSummaryOrganisation
 */
class ImportSummaryOrganisationBuilder
{
    /**
     * @var ImportSummaryOrganisation
     */
    private $instance;

    private function __construct(ImportSummaryOrganisation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Import Summary Organisation Builder object.
     */
    public static function init(): self
    {
        return new self(new ImportSummaryOrganisation());
    }

    /**
     * Sets Present field.
     *
     * @param bool|null $value
     */
    public function present(?bool $value): self
    {
        $this->instance->setPresent($value);
        return $this;
    }

    /**
     * Initializes a new Import Summary Organisation object.
     */
    public function build(): ImportSummaryOrganisation
    {
        return CoreHelper::clone($this->instance);
    }
}
