<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\ImportSummary;
use XeroAccountingAPILib\Models\ImportSummaryObject;

/**
 * Builder for model ImportSummaryObject
 *
 * @see ImportSummaryObject
 */
class ImportSummaryObjectBuilder
{
    /**
     * @var ImportSummaryObject
     */
    private $instance;

    private function __construct(ImportSummaryObject $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Import Summary Object Builder object.
     */
    public static function init(): self
    {
        return new self(new ImportSummaryObject());
    }

    /**
     * Sets Import Summary field.
     *
     * @param ImportSummary|null $value
     */
    public function importSummary(?ImportSummary $value): self
    {
        $this->instance->setImportSummary($value);
        return $this;
    }

    /**
     * Initializes a new Import Summary Object object.
     */
    public function build(): ImportSummaryObject
    {
        return CoreHelper::clone($this->instance);
    }
}
