<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\InvoiceReminder;

/**
 * Builder for model InvoiceReminder
 *
 * @see InvoiceReminder
 */
class InvoiceReminderBuilder
{
    /**
     * @var InvoiceReminder
     */
    private $instance;

    private function __construct(InvoiceReminder $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Invoice Reminder Builder object.
     */
    public static function init(): self
    {
        return new self(new InvoiceReminder());
    }

    /**
     * Sets Enabled field.
     *
     * @param bool|null $value
     */
    public function enabled(?bool $value): self
    {
        $this->instance->setEnabled($value);
        return $this;
    }

    /**
     * Initializes a new Invoice Reminder object.
     */
    public function build(): InvoiceReminder
    {
        return CoreHelper::clone($this->instance);
    }
}
