<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\Invoice;
use XeroAccountingAPILib\Models\Invoices;

/**
 * Builder for model Invoices
 *
 * @see Invoices
 */
class InvoicesBuilder
{
    /**
     * @var Invoices
     */
    private $instance;

    private function __construct(Invoices $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Invoices Builder object.
     */
    public static function init(): self
    {
        return new self(new Invoices());
    }

    /**
     * Sets Invoices field.
     *
     * @param Invoice[]|null $value
     */
    public function invoices(?array $value): self
    {
        $this->instance->setInvoices($value);
        return $this;
    }

    /**
     * Initializes a new Invoices object.
     */
    public function build(): Invoices
    {
        return CoreHelper::clone($this->instance);
    }
}
