<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\Journal;
use XeroAccountingAPILib\Models\JournalLine;

/**
 * Builder for model Journal
 *
 * @see Journal
 */
class JournalBuilder
{
    /**
     * @var Journal
     */
    private $instance;

    private function __construct(Journal $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Journal Builder object.
     */
    public static function init(): self
    {
        return new self(new Journal());
    }

    /**
     * Sets Created Date UTC field.
     *
     * @param string|null $value
     */
    public function createdDateUTC(?string $value): self
    {
        $this->instance->setCreatedDateUTC($value);
        return $this;
    }

    /**
     * Sets Journal Date field.
     *
     * @param string|null $value
     */
    public function journalDate(?string $value): self
    {
        $this->instance->setJournalDate($value);
        return $this;
    }

    /**
     * Sets Journal ID field.
     *
     * @param string|null $value
     */
    public function journalID(?string $value): self
    {
        $this->instance->setJournalID($value);
        return $this;
    }

    /**
     * Sets Journal Lines field.
     *
     * @param JournalLine[]|null $value
     */
    public function journalLines(?array $value): self
    {
        $this->instance->setJournalLines($value);
        return $this;
    }

    /**
     * Sets Journal Number field.
     *
     * @param int|null $value
     */
    public function journalNumber(?int $value): self
    {
        $this->instance->setJournalNumber($value);
        return $this;
    }

    /**
     * Sets Reference field.
     *
     * @param string|null $value
     */
    public function reference(?string $value): self
    {
        $this->instance->setReference($value);
        return $this;
    }

    /**
     * Sets Source ID field.
     *
     * @param string|null $value
     */
    public function sourceID(?string $value): self
    {
        $this->instance->setSourceID($value);
        return $this;
    }

    /**
     * Sets Source Type field.
     *
     * @param string|null $value
     */
    public function sourceType(?string $value): self
    {
        $this->instance->setSourceType($value);
        return $this;
    }

    /**
     * Initializes a new Journal object.
     */
    public function build(): Journal
    {
        return CoreHelper::clone($this->instance);
    }
}
