<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\LineItem;
use XeroAccountingAPILib\Models\LineItemTracking;

/**
 * Builder for model LineItem
 *
 * @see LineItem
 */
class LineItemBuilder
{
    /**
     * @var LineItem
     */
    private $instance;

    private function __construct(LineItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Line Item Builder object.
     */
    public static function init(): self
    {
        return new self(new LineItem());
    }

    /**
     * Sets Account Code field.
     *
     * @param string|null $value
     */
    public function accountCode(?string $value): self
    {
        $this->instance->setAccountCode($value);
        return $this;
    }

    /**
     * Sets Description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets Discount Amount field.
     *
     * @param float|null $value
     */
    public function discountAmount(?float $value): self
    {
        $this->instance->setDiscountAmount($value);
        return $this;
    }

    /**
     * Sets Discount Rate field.
     *
     * @param float|null $value
     */
    public function discountRate(?float $value): self
    {
        $this->instance->setDiscountRate($value);
        return $this;
    }

    /**
     * Sets Item Code field.
     *
     * @param string|null $value
     */
    public function itemCode(?string $value): self
    {
        $this->instance->setItemCode($value);
        return $this;
    }

    /**
     * Sets Line Amount field.
     *
     * @param float|null $value
     */
    public function lineAmount(?float $value): self
    {
        $this->instance->setLineAmount($value);
        return $this;
    }

    /**
     * Sets Line Item ID field.
     *
     * @param string|null $value
     */
    public function lineItemID(?string $value): self
    {
        $this->instance->setLineItemID($value);
        return $this;
    }

    /**
     * Sets Quantity field.
     *
     * @param float|null $value
     */
    public function quantity(?float $value): self
    {
        $this->instance->setQuantity($value);
        return $this;
    }

    /**
     * Sets Repeating Invoice ID field.
     *
     * @param string|null $value
     */
    public function repeatingInvoiceID(?string $value): self
    {
        $this->instance->setRepeatingInvoiceID($value);
        return $this;
    }

    /**
     * Sets Tax Amount field.
     *
     * @param float|null $value
     */
    public function taxAmount(?float $value): self
    {
        $this->instance->setTaxAmount($value);
        return $this;
    }

    /**
     * Sets Tax Type field.
     *
     * @param string|null $value
     */
    public function taxType(?string $value): self
    {
        $this->instance->setTaxType($value);
        return $this;
    }

    /**
     * Sets Tracking field.
     *
     * @param LineItemTracking[]|null $value
     */
    public function tracking(?array $value): self
    {
        $this->instance->setTracking($value);
        return $this;
    }

    /**
     * Sets Unit Amount field.
     *
     * @param float|null $value
     */
    public function unitAmount(?float $value): self
    {
        $this->instance->setUnitAmount($value);
        return $this;
    }

    /**
     * Initializes a new Line Item object.
     */
    public function build(): LineItem
    {
        return CoreHelper::clone($this->instance);
    }
}
