<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\LinkedTransaction;
use XeroAccountingAPILib\Models\ValidationError;

/**
 * Builder for model LinkedTransaction
 *
 * @see LinkedTransaction
 */
class LinkedTransactionBuilder
{
    /**
     * @var LinkedTransaction
     */
    private $instance;

    private function __construct(LinkedTransaction $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Linked Transaction Builder object.
     */
    public static function init(): self
    {
        return new self(new LinkedTransaction());
    }

    /**
     * Sets Contact ID field.
     *
     * @param string|null $value
     */
    public function contactID(?string $value): self
    {
        $this->instance->setContactID($value);
        return $this;
    }

    /**
     * Sets Linked Transaction ID field.
     *
     * @param string|null $value
     */
    public function linkedTransactionID(?string $value): self
    {
        $this->instance->setLinkedTransactionID($value);
        return $this;
    }

    /**
     * Sets Source Line Item ID field.
     *
     * @param string|null $value
     */
    public function sourceLineItemID(?string $value): self
    {
        $this->instance->setSourceLineItemID($value);
        return $this;
    }

    /**
     * Sets Source Transaction ID field.
     *
     * @param string|null $value
     */
    public function sourceTransactionID(?string $value): self
    {
        $this->instance->setSourceTransactionID($value);
        return $this;
    }

    /**
     * Sets Source Transaction Type Code field.
     *
     * @param string|null $value
     */
    public function sourceTransactionTypeCode(?string $value): self
    {
        $this->instance->setSourceTransactionTypeCode($value);
        return $this;
    }

    /**
     * Sets Status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets Target Line Item ID field.
     *
     * @param string|null $value
     */
    public function targetLineItemID(?string $value): self
    {
        $this->instance->setTargetLineItemID($value);
        return $this;
    }

    /**
     * Sets Target Transaction ID field.
     *
     * @param string|null $value
     */
    public function targetTransactionID(?string $value): self
    {
        $this->instance->setTargetTransactionID($value);
        return $this;
    }

    /**
     * Sets Type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets Updated Date UTC field.
     *
     * @param string|null $value
     */
    public function updatedDateUTC(?string $value): self
    {
        $this->instance->setUpdatedDateUTC($value);
        return $this;
    }

    /**
     * Sets Validation Errors field.
     *
     * @param ValidationError[]|null $value
     */
    public function validationErrors(?array $value): self
    {
        $this->instance->setValidationErrors($value);
        return $this;
    }

    /**
     * Initializes a new Linked Transaction object.
     */
    public function build(): LinkedTransaction
    {
        return CoreHelper::clone($this->instance);
    }
}
