<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\ManualJournal;
use XeroAccountingAPILib\Models\ManualJournals;

/**
 * Builder for model ManualJournals
 *
 * @see ManualJournals
 */
class ManualJournalsBuilder
{
    /**
     * @var ManualJournals
     */
    private $instance;

    private function __construct(ManualJournals $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Manual Journals Builder object.
     */
    public static function init(): self
    {
        return new self(new ManualJournals());
    }

    /**
     * Sets Manual Journals field.
     *
     * @param ManualJournal[]|null $value
     */
    public function manualJournals(?array $value): self
    {
        $this->instance->setManualJournals($value);
        return $this;
    }

    /**
     * Initializes a new Manual Journals object.
     */
    public function build(): ManualJournals
    {
        return CoreHelper::clone($this->instance);
    }
}
