<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\OnlineInvoice;
use XeroAccountingAPILib\Models\OnlineInvoices;

/**
 * Builder for model OnlineInvoices
 *
 * @see OnlineInvoices
 */
class OnlineInvoicesBuilder
{
    /**
     * @var OnlineInvoices
     */
    private $instance;

    private function __construct(OnlineInvoices $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Online Invoices Builder object.
     */
    public static function init(): self
    {
        return new self(new OnlineInvoices());
    }

    /**
     * Sets Online Invoices field.
     *
     * @param OnlineInvoice[]|null $value
     */
    public function onlineInvoices(?array $value): self
    {
        $this->instance->setOnlineInvoices($value);
        return $this;
    }

    /**
     * Initializes a new Online Invoices object.
     */
    public function build(): OnlineInvoices
    {
        return CoreHelper::clone($this->instance);
    }
}
