<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\OnlineInvoice;

/**
 * Builder for model OnlineInvoice
 *
 * @see OnlineInvoice
 */
class OnlineInvoiceBuilder
{
    /**
     * @var OnlineInvoice
     */
    private $instance;

    private function __construct(OnlineInvoice $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Online Invoice Builder object.
     */
    public static function init(): self
    {
        return new self(new OnlineInvoice());
    }

    /**
     * Sets Online Invoice Url field.
     *
     * @param string|null $value
     */
    public function onlineInvoiceUrl(?string $value): self
    {
        $this->instance->setOnlineInvoiceUrl($value);
        return $this;
    }

    /**
     * Initializes a new Online Invoice object.
     */
    public function build(): OnlineInvoice
    {
        return CoreHelper::clone($this->instance);
    }
}
