<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\Organisation;
use XeroAccountingAPILib\Models\Organisations;

/**
 * Builder for model Organisations
 *
 * @see Organisations
 */
class OrganisationsBuilder
{
    /**
     * @var Organisations
     */
    private $instance;

    private function __construct(Organisations $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Organisations Builder object.
     */
    public static function init(): self
    {
        return new self(new Organisations());
    }

    /**
     * Sets Organisations field.
     *
     * @param Organisation[]|null $value
     */
    public function organisations(?array $value): self
    {
        $this->instance->setOrganisations($value);
        return $this;
    }

    /**
     * Initializes a new Organisations object.
     */
    public function build(): Organisations
    {
        return CoreHelper::clone($this->instance);
    }
}
