<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\Payment;
use XeroAccountingAPILib\Models\Payments;

/**
 * Builder for model Payments
 *
 * @see Payments
 */
class PaymentsBuilder
{
    /**
     * @var Payments
     */
    private $instance;

    private function __construct(Payments $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payments Builder object.
     */
    public static function init(): self
    {
        return new self(new Payments());
    }

    /**
     * Sets Payments field.
     *
     * @param Payment[]|null $value
     */
    public function payments(?array $value): self
    {
        $this->instance->setPayments($value);
        return $this;
    }

    /**
     * Initializes a new Payments object.
     */
    public function build(): Payments
    {
        return CoreHelper::clone($this->instance);
    }
}
