<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\Account;
use XeroAccountingAPILib\Models\CreditNote;
use XeroAccountingAPILib\Models\Invoice;
use XeroAccountingAPILib\Models\Overpayment;
use XeroAccountingAPILib\Models\Payment;
use XeroAccountingAPILib\Models\Prepayment;
use XeroAccountingAPILib\Models\ValidationError;

/**
 * Builder for model Payment
 *
 * @see Payment
 */
class PaymentBuilder
{
    /**
     * @var Payment
     */
    private $instance;

    private function __construct(Payment $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Builder object.
     */
    public static function init(): self
    {
        return new self(new Payment());
    }

    /**
     * Sets Account field.
     *
     * @param Account|null $value
     */
    public function account(?Account $value): self
    {
        $this->instance->setAccount($value);
        return $this;
    }

    /**
     * Sets Amount field.
     *
     * @param float|null $value
     */
    public function amount(?float $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Sets Bank Account Number field.
     *
     * @param string|null $value
     */
    public function bankAccountNumber(?string $value): self
    {
        $this->instance->setBankAccountNumber($value);
        return $this;
    }

    /**
     * Sets Batch Payment ID field.
     *
     * @param string|null $value
     */
    public function batchPaymentID(?string $value): self
    {
        $this->instance->setBatchPaymentID($value);
        return $this;
    }

    /**
     * Sets Code field.
     *
     * @param string|null $value
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets Credit Note field.
     *
     * @param CreditNote|null $value
     */
    public function creditNote(?CreditNote $value): self
    {
        $this->instance->setCreditNote($value);
        return $this;
    }

    /**
     * Sets Credit Note Number field.
     *
     * @param string|null $value
     */
    public function creditNoteNumber(?string $value): self
    {
        $this->instance->setCreditNoteNumber($value);
        return $this;
    }

    /**
     * Sets Currency Rate field.
     *
     * @param float|null $value
     */
    public function currencyRate(?float $value): self
    {
        $this->instance->setCurrencyRate($value);
        return $this;
    }

    /**
     * Sets Date field.
     *
     * @param string|null $value
     */
    public function date(?string $value): self
    {
        $this->instance->setDate($value);
        return $this;
    }

    /**
     * Sets Details field.
     *
     * @param string|null $value
     */
    public function details(?string $value): self
    {
        $this->instance->setDetails($value);
        return $this;
    }

    /**
     * Sets Has Account field.
     *
     * @param bool|null $value
     */
    public function hasAccount(?bool $value): self
    {
        $this->instance->setHasAccount($value);
        return $this;
    }

    /**
     * Sets Has Validation Errors field.
     *
     * @param bool|null $value
     */
    public function hasValidationErrors(?bool $value): self
    {
        $this->instance->setHasValidationErrors($value);
        return $this;
    }

    /**
     * Sets Invoice field.
     *
     * @param Invoice|null $value
     */
    public function invoice(?Invoice $value): self
    {
        $this->instance->setInvoice($value);
        return $this;
    }

    /**
     * Sets Invoice Number field.
     *
     * @param string|null $value
     */
    public function invoiceNumber(?string $value): self
    {
        $this->instance->setInvoiceNumber($value);
        return $this;
    }

    /**
     * Sets Is Reconciled field.
     *
     * @param bool|null $value
     */
    public function isReconciled(?bool $value): self
    {
        $this->instance->setIsReconciled($value);
        return $this;
    }

    /**
     * Sets Overpayment field.
     *
     * @param Overpayment|null $value
     */
    public function overpayment(?Overpayment $value): self
    {
        $this->instance->setOverpayment($value);
        return $this;
    }

    /**
     * Sets Particulars field.
     *
     * @param string|null $value
     */
    public function particulars(?string $value): self
    {
        $this->instance->setParticulars($value);
        return $this;
    }

    /**
     * Sets Payment ID field.
     *
     * @param string|null $value
     */
    public function paymentID(?string $value): self
    {
        $this->instance->setPaymentID($value);
        return $this;
    }

    /**
     * Sets Payment Type field.
     *
     * @param string|null $value
     */
    public function paymentType(?string $value): self
    {
        $this->instance->setPaymentType($value);
        return $this;
    }

    /**
     * Sets Prepayment field.
     *
     * @param Prepayment|null $value
     */
    public function prepayment(?Prepayment $value): self
    {
        $this->instance->setPrepayment($value);
        return $this;
    }

    /**
     * Sets Reference field.
     *
     * @param string|null $value
     */
    public function reference(?string $value): self
    {
        $this->instance->setReference($value);
        return $this;
    }

    /**
     * Sets Status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets Status Attribute String field.
     *
     * @param string|null $value
     */
    public function statusAttributeString(?string $value): self
    {
        $this->instance->setStatusAttributeString($value);
        return $this;
    }

    /**
     * Sets Updated Date UTC field.
     *
     * @param string|null $value
     */
    public function updatedDateUTC(?string $value): self
    {
        $this->instance->setUpdatedDateUTC($value);
        return $this;
    }

    /**
     * Sets Validation Errors field.
     *
     * @param ValidationError[]|null $value
     */
    public function validationErrors(?array $value): self
    {
        $this->instance->setValidationErrors($value);
        return $this;
    }

    /**
     * Initializes a new Payment object.
     */
    public function build(): Payment
    {
        return CoreHelper::clone($this->instance);
    }
}
