<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\Phone;

/**
 * Builder for model Phone
 *
 * @see Phone
 */
class PhoneBuilder
{
    /**
     * @var Phone
     */
    private $instance;

    private function __construct(Phone $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Phone Builder object.
     */
    public static function init(): self
    {
        return new self(new Phone());
    }

    /**
     * Sets Phone Area Code field.
     *
     * @param string|null $value
     */
    public function phoneAreaCode(?string $value): self
    {
        $this->instance->setPhoneAreaCode($value);
        return $this;
    }

    /**
     * Sets Phone Country Code field.
     *
     * @param string|null $value
     */
    public function phoneCountryCode(?string $value): self
    {
        $this->instance->setPhoneCountryCode($value);
        return $this;
    }

    /**
     * Sets Phone Number field.
     *
     * @param string|null $value
     */
    public function phoneNumber(?string $value): self
    {
        $this->instance->setPhoneNumber($value);
        return $this;
    }

    /**
     * Sets Phone Type field.
     *
     * @param string|null $value
     */
    public function phoneType(?string $value): self
    {
        $this->instance->setPhoneType($value);
        return $this;
    }

    /**
     * Initializes a new Phone object.
     */
    public function build(): Phone
    {
        return CoreHelper::clone($this->instance);
    }
}
