<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\PurchaseOrder;
use XeroAccountingAPILib\Models\PurchaseOrders;

/**
 * Builder for model PurchaseOrders
 *
 * @see PurchaseOrders
 */
class PurchaseOrdersBuilder
{
    /**
     * @var PurchaseOrders
     */
    private $instance;

    private function __construct(PurchaseOrders $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Purchase Orders Builder object.
     */
    public static function init(): self
    {
        return new self(new PurchaseOrders());
    }

    /**
     * Sets Purchase Orders field.
     *
     * @param PurchaseOrder[]|null $value
     */
    public function purchaseOrders(?array $value): self
    {
        $this->instance->setPurchaseOrders($value);
        return $this;
    }

    /**
     * Initializes a new Purchase Orders object.
     */
    public function build(): PurchaseOrders
    {
        return CoreHelper::clone($this->instance);
    }
}
