<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\Quote;
use XeroAccountingAPILib\Models\Quotes;

/**
 * Builder for model Quotes
 *
 * @see Quotes
 */
class QuotesBuilder
{
    /**
     * @var Quotes
     */
    private $instance;

    private function __construct(Quotes $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Quotes Builder object.
     */
    public static function init(): self
    {
        return new self(new Quotes());
    }

    /**
     * Sets Quotes field.
     *
     * @param Quote[]|null $value
     */
    public function quotes(?array $value): self
    {
        $this->instance->setQuotes($value);
        return $this;
    }

    /**
     * Initializes a new Quotes object.
     */
    public function build(): Quotes
    {
        return CoreHelper::clone($this->instance);
    }
}
