<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\ReportCell;
use XeroAccountingAPILib\Models\ReportRow;
use XeroAccountingAPILib\Models\ReportRows;

/**
 * Builder for model ReportRows
 *
 * @see ReportRows
 */
class ReportRowsBuilder
{
    /**
     * @var ReportRows
     */
    private $instance;

    private function __construct(ReportRows $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Report Rows Builder object.
     */
    public static function init(): self
    {
        return new self(new ReportRows());
    }

    /**
     * Sets Cells field.
     *
     * @param ReportCell[]|null $value
     */
    public function cells(?array $value): self
    {
        $this->instance->setCells($value);
        return $this;
    }

    /**
     * Sets Row Type field.
     *
     * @param string|null $value
     */
    public function rowType(?string $value): self
    {
        $this->instance->setRowType($value);
        return $this;
    }

    /**
     * Sets Rows field.
     *
     * @param ReportRow[]|null $value
     */
    public function rows(?array $value): self
    {
        $this->instance->setRows($value);
        return $this;
    }

    /**
     * Sets Title field.
     *
     * @param string|null $value
     */
    public function title(?string $value): self
    {
        $this->instance->setTitle($value);
        return $this;
    }

    /**
     * Initializes a new Report Rows object.
     */
    public function build(): ReportRows
    {
        return CoreHelper::clone($this->instance);
    }
}
