<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\ReportFields;
use XeroAccountingAPILib\Models\ReportRows;
use XeroAccountingAPILib\Models\ReportWithRow;

/**
 * Builder for model ReportWithRow
 *
 * @see ReportWithRow
 */
class ReportWithRowBuilder
{
    /**
     * @var ReportWithRow
     */
    private $instance;

    private function __construct(ReportWithRow $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Report With Row Builder object.
     */
    public static function init(): self
    {
        return new self(new ReportWithRow());
    }

    /**
     * Sets Fields field.
     *
     * @param ReportFields[]|null $value
     */
    public function fields(?array $value): self
    {
        $this->instance->setFields($value);
        return $this;
    }

    /**
     * Sets Report Date field.
     *
     * @param string|null $value
     */
    public function reportDate(?string $value): self
    {
        $this->instance->setReportDate($value);
        return $this;
    }

    /**
     * Sets Report ID field.
     *
     * @param string|null $value
     */
    public function reportID(?string $value): self
    {
        $this->instance->setReportID($value);
        return $this;
    }

    /**
     * Sets Report Name field.
     *
     * @param string|null $value
     */
    public function reportName(?string $value): self
    {
        $this->instance->setReportName($value);
        return $this;
    }

    /**
     * Sets Report Title field.
     *
     * @param string|null $value
     */
    public function reportTitle(?string $value): self
    {
        $this->instance->setReportTitle($value);
        return $this;
    }

    /**
     * Sets Report Titles field.
     *
     * @param string[]|null $value
     */
    public function reportTitles(?array $value): self
    {
        $this->instance->setReportTitles($value);
        return $this;
    }

    /**
     * Sets Report Type field.
     *
     * @param string|null $value
     */
    public function reportType(?string $value): self
    {
        $this->instance->setReportType($value);
        return $this;
    }

    /**
     * Sets Rows field.
     *
     * @param ReportRows[]|null $value
     */
    public function rows(?array $value): self
    {
        $this->instance->setRows($value);
        return $this;
    }

    /**
     * Sets Updated Date UTC field.
     *
     * @param string|null $value
     */
    public function updatedDateUTC(?string $value): self
    {
        $this->instance->setUpdatedDateUTC($value);
        return $this;
    }

    /**
     * Initializes a new Report With Row object.
     */
    public function build(): ReportWithRow
    {
        return CoreHelper::clone($this->instance);
    }
}
