<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\ReportAttribute;
use XeroAccountingAPILib\Models\ReportCell;

/**
 * Builder for model ReportCell
 *
 * @see ReportCell
 */
class ReportCellBuilder
{
    /**
     * @var ReportCell
     */
    private $instance;

    private function __construct(ReportCell $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Report Cell Builder object.
     */
    public static function init(): self
    {
        return new self(new ReportCell());
    }

    /**
     * Sets Attributes field.
     *
     * @param ReportAttribute[]|null $value
     */
    public function attributes(?array $value): self
    {
        $this->instance->setAttributes($value);
        return $this;
    }

    /**
     * Sets Value field.
     *
     * @param string|null $value
     */
    public function value(?string $value): self
    {
        $this->instance->setValue($value);
        return $this;
    }

    /**
     * Initializes a new Report Cell object.
     */
    public function build(): ReportCell
    {
        return CoreHelper::clone($this->instance);
    }
}
