<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\RequestEmpty;

/**
 * Builder for model RequestEmpty
 *
 * @see RequestEmpty
 */
class RequestEmptyBuilder
{
    /**
     * @var RequestEmpty
     */
    private $instance;

    private function __construct(RequestEmpty $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Request Empty Builder object.
     */
    public static function init(): self
    {
        return new self(new RequestEmpty());
    }

    /**
     * Sets Status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Initializes a new Request Empty object.
     */
    public function build(): RequestEmpty
    {
        return CoreHelper::clone($this->instance);
    }
}
