<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\TaxRate;
use XeroAccountingAPILib\Models\TaxRates;

/**
 * Builder for model TaxRates
 *
 * @see TaxRates
 */
class TaxRatesBuilder
{
    /**
     * @var TaxRates
     */
    private $instance;

    private function __construct(TaxRates $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Tax Rates Builder object.
     */
    public static function init(): self
    {
        return new self(new TaxRates());
    }

    /**
     * Sets Tax Rates field.
     *
     * @param TaxRate[]|null $value
     */
    public function taxRates(?array $value): self
    {
        $this->instance->setTaxRates($value);
        return $this;
    }

    /**
     * Initializes a new Tax Rates object.
     */
    public function build(): TaxRates
    {
        return CoreHelper::clone($this->instance);
    }
}
