<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\TenNinetyNineContact;

/**
 * Builder for model TenNinetyNineContact
 *
 * @see TenNinetyNineContact
 */
class TenNinetyNineContactBuilder
{
    /**
     * @var TenNinetyNineContact
     */
    private $instance;

    private function __construct(TenNinetyNineContact $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Ten Ninety Nine Contact Builder object.
     */
    public static function init(): self
    {
        return new self(new TenNinetyNineContact());
    }

    /**
     * Sets Box 1 field.
     *
     * @param float|null $value
     */
    public function box1(?float $value): self
    {
        $this->instance->setBox1($value);
        return $this;
    }

    /**
     * Sets Box 10 field.
     *
     * @param float|null $value
     */
    public function box10(?float $value): self
    {
        $this->instance->setBox10($value);
        return $this;
    }

    /**
     * Sets Box 11 field.
     *
     * @param float|null $value
     */
    public function box11(?float $value): self
    {
        $this->instance->setBox11($value);
        return $this;
    }

    /**
     * Sets Box 13 field.
     *
     * @param float|null $value
     */
    public function box13(?float $value): self
    {
        $this->instance->setBox13($value);
        return $this;
    }

    /**
     * Sets Box 14 field.
     *
     * @param float|null $value
     */
    public function box14(?float $value): self
    {
        $this->instance->setBox14($value);
        return $this;
    }

    /**
     * Sets Box 2 field.
     *
     * @param float|null $value
     */
    public function box2(?float $value): self
    {
        $this->instance->setBox2($value);
        return $this;
    }

    /**
     * Sets Box 3 field.
     *
     * @param float|null $value
     */
    public function box3(?float $value): self
    {
        $this->instance->setBox3($value);
        return $this;
    }

    /**
     * Sets Box 4 field.
     *
     * @param float|null $value
     */
    public function box4(?float $value): self
    {
        $this->instance->setBox4($value);
        return $this;
    }

    /**
     * Sets Box 5 field.
     *
     * @param float|null $value
     */
    public function box5(?float $value): self
    {
        $this->instance->setBox5($value);
        return $this;
    }

    /**
     * Sets Box 6 field.
     *
     * @param float|null $value
     */
    public function box6(?float $value): self
    {
        $this->instance->setBox6($value);
        return $this;
    }

    /**
     * Sets Box 7 field.
     *
     * @param float|null $value
     */
    public function box7(?float $value): self
    {
        $this->instance->setBox7($value);
        return $this;
    }

    /**
     * Sets Box 8 field.
     *
     * @param float|null $value
     */
    public function box8(?float $value): self
    {
        $this->instance->setBox8($value);
        return $this;
    }

    /**
     * Sets Box 9 field.
     *
     * @param float|null $value
     */
    public function box9(?float $value): self
    {
        $this->instance->setBox9($value);
        return $this;
    }

    /**
     * Sets City field.
     *
     * @param string|null $value
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets Contact Id field.
     *
     * @param string|null $value
     */
    public function contactId(?string $value): self
    {
        $this->instance->setContactId($value);
        return $this;
    }

    /**
     * Sets Email field.
     *
     * @param string|null $value
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Sets Federal Tax ID Type field.
     *
     * @param string|null $value
     */
    public function federalTaxIDType(?string $value): self
    {
        $this->instance->setFederalTaxIDType($value);
        return $this;
    }

    /**
     * Sets Name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets State field.
     *
     * @param string|null $value
     */
    public function state(?string $value): self
    {
        $this->instance->setState($value);
        return $this;
    }

    /**
     * Sets Street Address field.
     *
     * @param string|null $value
     */
    public function streetAddress(?string $value): self
    {
        $this->instance->setStreetAddress($value);
        return $this;
    }

    /**
     * Sets Tax ID field.
     *
     * @param string|null $value
     */
    public function taxID(?string $value): self
    {
        $this->instance->setTaxID($value);
        return $this;
    }

    /**
     * Sets Zip field.
     *
     * @param string|null $value
     */
    public function zip(?string $value): self
    {
        $this->instance->setZip($value);
        return $this;
    }

    /**
     * Initializes a new Ten Ninety Nine Contact object.
     */
    public function build(): TenNinetyNineContact
    {
        return CoreHelper::clone($this->instance);
    }
}
