<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\TrackingCategory;
use XeroAccountingAPILib\Models\TrackingOption;

/**
 * Builder for model TrackingCategory
 *
 * @see TrackingCategory
 */
class TrackingCategoryBuilder
{
    /**
     * @var TrackingCategory
     */
    private $instance;

    private function __construct(TrackingCategory $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Tracking Category Builder object.
     */
    public static function init(): self
    {
        return new self(new TrackingCategory());
    }

    /**
     * Sets Name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets Option field.
     *
     * @param string|null $value
     */
    public function option(?string $value): self
    {
        $this->instance->setOption($value);
        return $this;
    }

    /**
     * Sets Options field.
     *
     * @param TrackingOption[]|null $value
     */
    public function options(?array $value): self
    {
        $this->instance->setOptions($value);
        return $this;
    }

    /**
     * Sets Status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets Tracking Category ID field.
     *
     * @param string|null $value
     */
    public function trackingCategoryID(?string $value): self
    {
        $this->instance->setTrackingCategoryID($value);
        return $this;
    }

    /**
     * Sets Tracking Option ID field.
     *
     * @param string|null $value
     */
    public function trackingOptionID(?string $value): self
    {
        $this->instance->setTrackingOptionID($value);
        return $this;
    }

    /**
     * Initializes a new Tracking Category object.
     */
    public function build(): TrackingCategory
    {
        return CoreHelper::clone($this->instance);
    }
}
