<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use XeroAccountingAPILib\Models\User;

/**
 * Builder for model User
 *
 * @see User
 */
class UserBuilder
{
    /**
     * @var User
     */
    private $instance;

    private function __construct(User $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new User Builder object.
     */
    public static function init(): self
    {
        return new self(new User());
    }

    /**
     * Sets Email Address field.
     *
     * @param string|null $value
     */
    public function emailAddress(?string $value): self
    {
        $this->instance->setEmailAddress($value);
        return $this;
    }

    /**
     * Sets First Name field.
     *
     * @param string|null $value
     */
    public function firstName(?string $value): self
    {
        $this->instance->setFirstName($value);
        return $this;
    }

    /**
     * Sets Is Subscriber field.
     *
     * @param bool|null $value
     */
    public function isSubscriber(?bool $value): self
    {
        $this->instance->setIsSubscriber($value);
        return $this;
    }

    /**
     * Sets Last Name field.
     *
     * @param string|null $value
     */
    public function lastName(?string $value): self
    {
        $this->instance->setLastName($value);
        return $this;
    }

    /**
     * Sets Organisation Role field.
     *
     * @param string|null $value
     */
    public function organisationRole(?string $value): self
    {
        $this->instance->setOrganisationRole($value);
        return $this;
    }

    /**
     * Sets Updated Date UTC field.
     *
     * @param string|null $value
     */
    public function updatedDateUTC(?string $value): self
    {
        $this->instance->setUpdatedDateUTC($value);
        return $this;
    }

    /**
     * Sets User ID field.
     *
     * @param string|null $value
     */
    public function userID(?string $value): self
    {
        $this->instance->setUserID($value);
        return $this;
    }

    /**
     * Initializes a new User object.
     */
    public function build(): User
    {
        return CoreHelper::clone($this->instance);
    }
}
