<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * See Account Types
 */
class AccountTypeEnum
{
    public const BANK = 'BANK';

    public const CURRENT = 'CURRENT';

    public const CURRLIAB = 'CURRLIAB';

    public const DEPRECIATN = 'DEPRECIATN';

    public const DIRECTCOSTS = 'DIRECTCOSTS';

    public const EQUITY = 'EQUITY';

    public const EXPENSE = 'EXPENSE';

    public const FIXED = 'FIXED';

    public const INVENTORY = 'INVENTORY';

    public const LIABILITY = 'LIABILITY';

    public const NONCURRENT = 'NONCURRENT';

    public const OTHERINCOME = 'OTHERINCOME';

    public const OVERHEADS = 'OVERHEADS';

    public const PREPAYMENT = 'PREPAYMENT';

    public const REVENUE = 'REVENUE';

    public const SALES = 'SALES';

    public const TERMLIAB = 'TERMLIAB';

    public const PAYGLIABILITY = 'PAYGLIABILITY';

    public const PAYG = 'PAYG';

    public const SUPERANNUATIONEXPENSE = 'SUPERANNUATIONEXPENSE';

    public const SUPERANNUATIONLIABILITY = 'SUPERANNUATIONLIABILITY';

    public const WAGESEXPENSE = 'WAGESEXPENSE';

    private const _ALL_VALUES = [
        self::BANK,
        self::CURRENT,
        self::CURRLIAB,
        self::DEPRECIATN,
        self::DIRECTCOSTS,
        self::EQUITY,
        self::EXPENSE,
        self::FIXED,
        self::INVENTORY,
        self::LIABILITY,
        self::NONCURRENT,
        self::OTHERINCOME,
        self::OVERHEADS,
        self::PREPAYMENT,
        self::REVENUE,
        self::SALES,
        self::TERMLIAB,
        self::PAYGLIABILITY,
        self::PAYG,
        self::SUPERANNUATIONEXPENSE,
        self::SUPERANNUATIONLIABILITY,
        self::WAGESEXPENSE
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for AccountTypeEnum.");
    }
}
