<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class AddressForOrganisation implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $addressLine1;

    /**
     * @var string|null
     */
    private $addressLine2;

    /**
     * @var string|null
     */
    private $addressLine3;

    /**
     * @var string|null
     */
    private $addressLine4;

    /**
     * @var string|null
     */
    private $addressType;

    /**
     * @var string|null
     */
    private $attentionTo;

    /**
     * @var string|null
     */
    private $city;

    /**
     * @var string|null
     */
    private $country;

    /**
     * @var string|null
     */
    private $postalCode;

    /**
     * @var string|null
     */
    private $region;

    /**
     * Returns Address Line 1.
     * max length = 500
     */
    public function getAddressLine1(): ?string
    {
        return $this->addressLine1;
    }

    /**
     * Sets Address Line 1.
     * max length = 500
     *
     * @maps AddressLine1
     */
    public function setAddressLine1(?string $addressLine1): void
    {
        $this->addressLine1 = $addressLine1;
    }

    /**
     * Returns Address Line 2.
     * max length = 500
     */
    public function getAddressLine2(): ?string
    {
        return $this->addressLine2;
    }

    /**
     * Sets Address Line 2.
     * max length = 500
     *
     * @maps AddressLine2
     */
    public function setAddressLine2(?string $addressLine2): void
    {
        $this->addressLine2 = $addressLine2;
    }

    /**
     * Returns Address Line 3.
     * max length = 500
     */
    public function getAddressLine3(): ?string
    {
        return $this->addressLine3;
    }

    /**
     * Sets Address Line 3.
     * max length = 500
     *
     * @maps AddressLine3
     */
    public function setAddressLine3(?string $addressLine3): void
    {
        $this->addressLine3 = $addressLine3;
    }

    /**
     * Returns Address Line 4.
     * max length = 500
     */
    public function getAddressLine4(): ?string
    {
        return $this->addressLine4;
    }

    /**
     * Sets Address Line 4.
     * max length = 500
     *
     * @maps AddressLine4
     */
    public function setAddressLine4(?string $addressLine4): void
    {
        $this->addressLine4 = $addressLine4;
    }

    /**
     * Returns Address Type.
     * define the type of address
     */
    public function getAddressType(): ?string
    {
        return $this->addressType;
    }

    /**
     * Sets Address Type.
     * define the type of address
     *
     * @maps AddressType
     * @factory \XeroAccountingAPILib\Models\AddressType1Enum::checkValue
     */
    public function setAddressType(?string $addressType): void
    {
        $this->addressType = $addressType;
    }

    /**
     * Returns Attention To.
     * max length = 255
     */
    public function getAttentionTo(): ?string
    {
        return $this->attentionTo;
    }

    /**
     * Sets Attention To.
     * max length = 255
     *
     * @maps AttentionTo
     */
    public function setAttentionTo(?string $attentionTo): void
    {
        $this->attentionTo = $attentionTo;
    }

    /**
     * Returns City.
     * max length = 255
     */
    public function getCity(): ?string
    {
        return $this->city;
    }

    /**
     * Sets City.
     * max length = 255
     *
     * @maps City
     */
    public function setCity(?string $city): void
    {
        $this->city = $city;
    }

    /**
     * Returns Country.
     * max length = 50, [A-Z], [a-z] only
     */
    public function getCountry(): ?string
    {
        return $this->country;
    }

    /**
     * Sets Country.
     * max length = 50, [A-Z], [a-z] only
     *
     * @maps Country
     */
    public function setCountry(?string $country): void
    {
        $this->country = $country;
    }

    /**
     * Returns Postal Code.
     * max length = 50
     */
    public function getPostalCode(): ?string
    {
        return $this->postalCode;
    }

    /**
     * Sets Postal Code.
     * max length = 50
     *
     * @maps PostalCode
     */
    public function setPostalCode(?string $postalCode): void
    {
        $this->postalCode = $postalCode;
    }

    /**
     * Returns Region.
     * max length = 255
     */
    public function getRegion(): ?string
    {
        return $this->region;
    }

    /**
     * Sets Region.
     * max length = 255
     *
     * @maps Region
     */
    public function setRegion(?string $region): void
    {
        $this->region = $region;
    }

    /**
     * Converts the AddressForOrganisation object to a human-readable string representation.
     *
     * @return string The string representation of the AddressForOrganisation object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AddressForOrganisation',
            [
                'addressLine1' => $this->addressLine1,
                'addressLine2' => $this->addressLine2,
                'addressLine3' => $this->addressLine3,
                'addressLine4' => $this->addressLine4,
                'addressType' => $this->addressType,
                'attentionTo' => $this->attentionTo,
                'city' => $this->city,
                'country' => $this->country,
                'postalCode' => $this->postalCode,
                'region' => $this->region
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->addressLine1)) {
            $json['AddressLine1'] = $this->addressLine1;
        }
        if (isset($this->addressLine2)) {
            $json['AddressLine2'] = $this->addressLine2;
        }
        if (isset($this->addressLine3)) {
            $json['AddressLine3'] = $this->addressLine3;
        }
        if (isset($this->addressLine4)) {
            $json['AddressLine4'] = $this->addressLine4;
        }
        if (isset($this->addressType)) {
            $json['AddressType']  = AddressType1Enum::checkValue($this->addressType);
        }
        if (isset($this->attentionTo)) {
            $json['AttentionTo']  = $this->attentionTo;
        }
        if (isset($this->city)) {
            $json['City']         = $this->city;
        }
        if (isset($this->country)) {
            $json['Country']      = $this->country;
        }
        if (isset($this->postalCode)) {
            $json['PostalCode']   = $this->postalCode;
        }
        if (isset($this->region)) {
            $json['Region']       = $this->region;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
