<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

/**
 * The raw AccountsReceivable(sales invoices) and AccountsPayable(bills) outstanding and overdue
 * amounts, not converted to base currency (read only)
 */
class Balances implements \JsonSerializable
{
    /**
     * @var AccountsPayable|null
     */
    private $accountsPayable;

    /**
     * @var AccountsReceivable|null
     */
    private $accountsReceivable;

    /**
     * Returns Accounts Payable.
     */
    public function getAccountsPayable(): ?AccountsPayable
    {
        return $this->accountsPayable;
    }

    /**
     * Sets Accounts Payable.
     *
     * @maps AccountsPayable
     */
    public function setAccountsPayable(?AccountsPayable $accountsPayable): void
    {
        $this->accountsPayable = $accountsPayable;
    }

    /**
     * Returns Accounts Receivable.
     */
    public function getAccountsReceivable(): ?AccountsReceivable
    {
        return $this->accountsReceivable;
    }

    /**
     * Sets Accounts Receivable.
     *
     * @maps AccountsReceivable
     */
    public function setAccountsReceivable(?AccountsReceivable $accountsReceivable): void
    {
        $this->accountsReceivable = $accountsReceivable;
    }

    /**
     * Converts the Balances object to a human-readable string representation.
     *
     * @return string The string representation of the Balances object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Balances',
            ['accountsPayable' => $this->accountsPayable, 'accountsReceivable' => $this->accountsReceivable]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->accountsPayable)) {
            $json['AccountsPayable']    = $this->accountsPayable;
        }
        if (isset($this->accountsReceivable)) {
            $json['AccountsReceivable'] = $this->accountsReceivable;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
