<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

/**
 * An array to specify multiple currency balances of an account
 */
class BalanceDetails implements \JsonSerializable
{
    /**
     * @var float|null
     */
    private $balance;

    /**
     * @var string|null
     */
    private $currencyCode;

    /**
     * @var float|null
     */
    private $currencyRate;

    /**
     * Returns Balance.
     * The opening balances of the account. Debits are positive, credits are negative values
     */
    public function getBalance(): ?float
    {
        return $this->balance;
    }

    /**
     * Sets Balance.
     * The opening balances of the account. Debits are positive, credits are negative values
     *
     * @maps Balance
     */
    public function setBalance(?float $balance): void
    {
        $this->balance = $balance;
    }

    /**
     * Returns Currency Code.
     * The currency of the balance (Not required for base currency)
     */
    public function getCurrencyCode(): ?string
    {
        return $this->currencyCode;
    }

    /**
     * Sets Currency Code.
     * The currency of the balance (Not required for base currency)
     *
     * @maps CurrencyCode
     */
    public function setCurrencyCode(?string $currencyCode): void
    {
        $this->currencyCode = $currencyCode;
    }

    /**
     * Returns Currency Rate.
     * (Optional) Exchange rate to base currency when money is spent or received. If not specified, XE rate
     * for the day is applied
     */
    public function getCurrencyRate(): ?float
    {
        return $this->currencyRate;
    }

    /**
     * Sets Currency Rate.
     * (Optional) Exchange rate to base currency when money is spent or received. If not specified, XE rate
     * for the day is applied
     *
     * @maps CurrencyRate
     */
    public function setCurrencyRate(?float $currencyRate): void
    {
        $this->currencyRate = $currencyRate;
    }

    /**
     * Converts the BalanceDetails object to a human-readable string representation.
     *
     * @return string The string representation of the BalanceDetails object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'BalanceDetails',
            [
                'balance' => $this->balance,
                'currencyCode' => $this->currencyCode,
                'currencyRate' => $this->currencyRate
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->balance)) {
            $json['Balance']      = $this->balance;
        }
        if (isset($this->currencyCode)) {
            $json['CurrencyCode'] = $this->currencyCode;
        }
        if (isset($this->currencyRate)) {
            $json['CurrencyRate'] = $this->currencyRate;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
