<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class BankTransactions implements \JsonSerializable
{
    /**
     * @var BankTransaction[]|null
     */
    private $bankTransactions;

    /**
     * Returns Bank Transactions.
     *
     * @return BankTransaction[]|null
     */
    public function getBankTransactions(): ?array
    {
        return $this->bankTransactions;
    }

    /**
     * Sets Bank Transactions.
     *
     * @maps BankTransactions
     *
     * @param BankTransaction[]|null $bankTransactions
     */
    public function setBankTransactions(?array $bankTransactions): void
    {
        $this->bankTransactions = $bankTransactions;
    }

    /**
     * Converts the BankTransactions object to a human-readable string representation.
     *
     * @return string The string representation of the BankTransactions object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('BankTransactions', ['bankTransactions' => $this->bankTransactions]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->bankTransactions)) {
            $json['BankTransactions'] = $this->bankTransactions;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
