<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class BankTransaction implements \JsonSerializable
{
    /**
     * @var Account
     */
    private $bankAccount;

    /**
     * @var string|null
     */
    private $bankTransactionID;

    /**
     * @var Contact|null
     */
    private $contact;

    /**
     * @var string|null
     */
    private $currencyCode;

    /**
     * @var float|null
     */
    private $currencyRate;

    /**
     * @var string|null
     */
    private $date;

    /**
     * @var bool|null
     */
    private $hasAttachments = false;

    /**
     * @var bool|null
     */
    private $isReconciled;

    /**
     * @var string|null
     */
    private $lineAmountTypes;

    /**
     * @var LineItem[]
     */
    private $lineItems;

    /**
     * @var string|null
     */
    private $overpaymentID;

    /**
     * @var string|null
     */
    private $prepaymentID;

    /**
     * @var string|null
     */
    private $reference;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $statusAttributeString;

    /**
     * @var float|null
     */
    private $subTotal;

    /**
     * @var float|null
     */
    private $total;

    /**
     * @var float|null
     */
    private $totalTax;

    /**
     * @var string
     */
    private $type;

    /**
     * @var string|null
     */
    private $updatedDateUTC;

    /**
     * @var string|null
     */
    private $url;

    /**
     * @var ValidationError[]|null
     */
    private $validationErrors;

    /**
     * @param Account $bankAccount
     * @param LineItem[] $lineItems
     * @param string $type
     */
    public function __construct(Account $bankAccount, array $lineItems, string $type)
    {
        $this->bankAccount = $bankAccount;
        $this->lineItems = $lineItems;
        $this->type = $type;
    }

    /**
     * Returns Bank Account.
     */
    public function getBankAccount(): Account
    {
        return $this->bankAccount;
    }

    /**
     * Sets Bank Account.
     *
     * @required
     * @maps BankAccount
     */
    public function setBankAccount(Account $bankAccount): void
    {
        $this->bankAccount = $bankAccount;
    }

    /**
     * Returns Bank Transaction ID.
     * Xero generated unique identifier for bank transaction
     */
    public function getBankTransactionID(): ?string
    {
        return $this->bankTransactionID;
    }

    /**
     * Sets Bank Transaction ID.
     * Xero generated unique identifier for bank transaction
     *
     * @maps BankTransactionID
     */
    public function setBankTransactionID(?string $bankTransactionID): void
    {
        $this->bankTransactionID = $bankTransactionID;
    }

    /**
     * Returns Contact.
     */
    public function getContact(): ?Contact
    {
        return $this->contact;
    }

    /**
     * Sets Contact.
     *
     * @maps Contact
     */
    public function setContact(?Contact $contact): void
    {
        $this->contact = $contact;
    }

    /**
     * Returns Currency Code.
     * 3 letter alpha code for the currency – see list of currency codes
     */
    public function getCurrencyCode(): ?string
    {
        return $this->currencyCode;
    }

    /**
     * Sets Currency Code.
     * 3 letter alpha code for the currency – see list of currency codes
     *
     * @maps CurrencyCode
     * @factory \XeroAccountingAPILib\Models\CurrencyCodeEnum::checkValue
     */
    public function setCurrencyCode(?string $currencyCode): void
    {
        $this->currencyCode = $currencyCode;
    }

    /**
     * Returns Currency Rate.
     * Exchange rate to base currency when money is spent or received. e.g.0.7500 Only used for bank
     * transactions in non base currency. If this isn’t specified for non base currency accounts then
     * either the user-defined rate (preference) or the XE.com day rate will be used. Setting currency is
     * only supported on overpayments.
     */
    public function getCurrencyRate(): ?float
    {
        return $this->currencyRate;
    }

    /**
     * Sets Currency Rate.
     * Exchange rate to base currency when money is spent or received. e.g.0.7500 Only used for bank
     * transactions in non base currency. If this isn’t specified for non base currency accounts then
     * either the user-defined rate (preference) or the XE.com day rate will be used. Setting currency is
     * only supported on overpayments.
     *
     * @maps CurrencyRate
     */
    public function setCurrencyRate(?float $currencyRate): void
    {
        $this->currencyRate = $currencyRate;
    }

    /**
     * Returns Date.
     * Date of transaction – YYYY-MM-DD
     */
    public function getDate(): ?string
    {
        return $this->date;
    }

    /**
     * Sets Date.
     * Date of transaction – YYYY-MM-DD
     *
     * @maps Date
     */
    public function setDate(?string $date): void
    {
        $this->date = $date;
    }

    /**
     * Returns Has Attachments.
     * Boolean to indicate if a bank transaction has an attachment
     */
    public function getHasAttachments(): ?bool
    {
        return $this->hasAttachments;
    }

    /**
     * Sets Has Attachments.
     * Boolean to indicate if a bank transaction has an attachment
     *
     * @maps HasAttachments
     */
    public function setHasAttachments(?bool $hasAttachments): void
    {
        $this->hasAttachments = $hasAttachments;
    }

    /**
     * Returns Is Reconciled.
     * Boolean to show if transaction is reconciled
     */
    public function getIsReconciled(): ?bool
    {
        return $this->isReconciled;
    }

    /**
     * Sets Is Reconciled.
     * Boolean to show if transaction is reconciled
     *
     * @maps IsReconciled
     */
    public function setIsReconciled(?bool $isReconciled): void
    {
        $this->isReconciled = $isReconciled;
    }

    /**
     * Returns Line Amount Types.
     * Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount
     * Types
     */
    public function getLineAmountTypes(): ?string
    {
        return $this->lineAmountTypes;
    }

    /**
     * Sets Line Amount Types.
     * Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount
     * Types
     *
     * @maps LineAmountTypes
     * @factory \XeroAccountingAPILib\Models\LineAmountTypesEnum::checkValue
     */
    public function setLineAmountTypes(?string $lineAmountTypes): void
    {
        $this->lineAmountTypes = $lineAmountTypes;
    }

    /**
     * Returns Line Items.
     * See LineItems
     *
     * @return LineItem[]
     */
    public function getLineItems(): array
    {
        return $this->lineItems;
    }

    /**
     * Sets Line Items.
     * See LineItems
     *
     * @required
     * @maps LineItems
     *
     * @param LineItem[] $lineItems
     */
    public function setLineItems(array $lineItems): void
    {
        $this->lineItems = $lineItems;
    }

    /**
     * Returns Overpayment ID.
     * Xero generated unique identifier for an Overpayment. This will be returned on BankTransactions with
     * a Type of SPEND-OVERPAYMENT or RECEIVE-OVERPAYMENT
     */
    public function getOverpaymentID(): ?string
    {
        return $this->overpaymentID;
    }

    /**
     * Sets Overpayment ID.
     * Xero generated unique identifier for an Overpayment. This will be returned on BankTransactions with
     * a Type of SPEND-OVERPAYMENT or RECEIVE-OVERPAYMENT
     *
     * @maps OverpaymentID
     */
    public function setOverpaymentID(?string $overpaymentID): void
    {
        $this->overpaymentID = $overpaymentID;
    }

    /**
     * Returns Prepayment ID.
     * Xero generated unique identifier for a Prepayment. This will be returned on BankTransactions with a
     * Type of SPEND-PREPAYMENT or RECEIVE-PREPAYMENT
     */
    public function getPrepaymentID(): ?string
    {
        return $this->prepaymentID;
    }

    /**
     * Sets Prepayment ID.
     * Xero generated unique identifier for a Prepayment. This will be returned on BankTransactions with a
     * Type of SPEND-PREPAYMENT or RECEIVE-PREPAYMENT
     *
     * @maps PrepaymentID
     */
    public function setPrepaymentID(?string $prepaymentID): void
    {
        $this->prepaymentID = $prepaymentID;
    }

    /**
     * Returns Reference.
     * Reference for the transaction. Only supported for SPEND and RECEIVE transactions.
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     * Reference for the transaction. Only supported for SPEND and RECEIVE transactions.
     *
     * @maps Reference
     */
    public function setReference(?string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Returns Status.
     * See Bank Transaction Status Codes
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * See Bank Transaction Status Codes
     *
     * @maps Status
     * @factory \XeroAccountingAPILib\Models\Status8Enum::checkValue
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Status Attribute String.
     * A string to indicate if a invoice status
     */
    public function getStatusAttributeString(): ?string
    {
        return $this->statusAttributeString;
    }

    /**
     * Sets Status Attribute String.
     * A string to indicate if a invoice status
     *
     * @maps StatusAttributeString
     */
    public function setStatusAttributeString(?string $statusAttributeString): void
    {
        $this->statusAttributeString = $statusAttributeString;
    }

    /**
     * Returns Sub Total.
     * Total of bank transaction excluding taxes
     */
    public function getSubTotal(): ?float
    {
        return $this->subTotal;
    }

    /**
     * Sets Sub Total.
     * Total of bank transaction excluding taxes
     *
     * @maps SubTotal
     */
    public function setSubTotal(?float $subTotal): void
    {
        $this->subTotal = $subTotal;
    }

    /**
     * Returns Total.
     * Total of bank transaction tax inclusive
     */
    public function getTotal(): ?float
    {
        return $this->total;
    }

    /**
     * Sets Total.
     * Total of bank transaction tax inclusive
     *
     * @maps Total
     */
    public function setTotal(?float $total): void
    {
        $this->total = $total;
    }

    /**
     * Returns Total Tax.
     * Total tax on bank transaction
     */
    public function getTotalTax(): ?float
    {
        return $this->totalTax;
    }

    /**
     * Sets Total Tax.
     * Total tax on bank transaction
     *
     * @maps TotalTax
     */
    public function setTotalTax(?float $totalTax): void
    {
        $this->totalTax = $totalTax;
    }

    /**
     * Returns Type.
     * See Bank Transaction Types
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * See Bank Transaction Types
     *
     * @required
     * @maps Type
     * @factory \XeroAccountingAPILib\Models\Type5Enum::checkValue
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Updated Date UTC.
     * Last modified date UTC format
     */
    public function getUpdatedDateUTC(): ?string
    {
        return $this->updatedDateUTC;
    }

    /**
     * Sets Updated Date UTC.
     * Last modified date UTC format
     *
     * @maps UpdatedDateUTC
     */
    public function setUpdatedDateUTC(?string $updatedDateUTC): void
    {
        $this->updatedDateUTC = $updatedDateUTC;
    }

    /**
     * Returns Url.
     * URL link to a source document – shown as “Go to App Name”
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * Sets Url.
     * URL link to a source document – shown as “Go to App Name”
     *
     * @maps Url
     */
    public function setUrl(?string $url): void
    {
        $this->url = $url;
    }

    /**
     * Returns Validation Errors.
     * Displays array of validation error messages from the API
     *
     * @return ValidationError[]|null
     */
    public function getValidationErrors(): ?array
    {
        return $this->validationErrors;
    }

    /**
     * Sets Validation Errors.
     * Displays array of validation error messages from the API
     *
     * @maps ValidationErrors
     *
     * @param ValidationError[]|null $validationErrors
     */
    public function setValidationErrors(?array $validationErrors): void
    {
        $this->validationErrors = $validationErrors;
    }

    /**
     * Converts the BankTransaction object to a human-readable string representation.
     *
     * @return string The string representation of the BankTransaction object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'BankTransaction',
            [
                'bankAccount' => $this->bankAccount,
                'bankTransactionID' => $this->bankTransactionID,
                'contact' => $this->contact,
                'currencyCode' => $this->currencyCode,
                'currencyRate' => $this->currencyRate,
                'date' => $this->date,
                'hasAttachments' => $this->hasAttachments,
                'isReconciled' => $this->isReconciled,
                'lineAmountTypes' => $this->lineAmountTypes,
                'lineItems' => $this->lineItems,
                'overpaymentID' => $this->overpaymentID,
                'prepaymentID' => $this->prepaymentID,
                'reference' => $this->reference,
                'status' => $this->status,
                'statusAttributeString' => $this->statusAttributeString,
                'subTotal' => $this->subTotal,
                'total' => $this->total,
                'totalTax' => $this->totalTax,
                'type' => $this->type,
                'updatedDateUTC' => $this->updatedDateUTC,
                'url' => $this->url,
                'validationErrors' => $this->validationErrors
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['BankAccount']               = $this->bankAccount;
        if (isset($this->bankTransactionID)) {
            $json['BankTransactionID']     = $this->bankTransactionID;
        }
        if (isset($this->contact)) {
            $json['Contact']               = $this->contact;
        }
        if (isset($this->currencyCode)) {
            $json['CurrencyCode']          = CurrencyCodeEnum::checkValue($this->currencyCode);
        }
        if (isset($this->currencyRate)) {
            $json['CurrencyRate']          = $this->currencyRate;
        }
        if (isset($this->date)) {
            $json['Date']                  = $this->date;
        }
        if (isset($this->hasAttachments)) {
            $json['HasAttachments']        = $this->hasAttachments;
        }
        if (isset($this->isReconciled)) {
            $json['IsReconciled']          = $this->isReconciled;
        }
        if (isset($this->lineAmountTypes)) {
            $json['LineAmountTypes']       = LineAmountTypesEnum::checkValue($this->lineAmountTypes);
        }
        $json['LineItems']                 = $this->lineItems;
        if (isset($this->overpaymentID)) {
            $json['OverpaymentID']         = $this->overpaymentID;
        }
        if (isset($this->prepaymentID)) {
            $json['PrepaymentID']          = $this->prepaymentID;
        }
        if (isset($this->reference)) {
            $json['Reference']             = $this->reference;
        }
        if (isset($this->status)) {
            $json['Status']                = Status8Enum::checkValue($this->status);
        }
        if (isset($this->statusAttributeString)) {
            $json['StatusAttributeString'] = $this->statusAttributeString;
        }
        if (isset($this->subTotal)) {
            $json['SubTotal']              = $this->subTotal;
        }
        if (isset($this->total)) {
            $json['Total']                 = $this->total;
        }
        if (isset($this->totalTax)) {
            $json['TotalTax']              = $this->totalTax;
        }
        $json['Type']                      = Type5Enum::checkValue($this->type);
        if (isset($this->updatedDateUTC)) {
            $json['UpdatedDateUTC']        = $this->updatedDateUTC;
        }
        if (isset($this->url)) {
            $json['Url']                   = $this->url;
        }
        if (isset($this->validationErrors)) {
            $json['ValidationErrors']      = $this->validationErrors;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
