<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class BankTransfers implements \JsonSerializable
{
    /**
     * @var BankTransfer[]|null
     */
    private $bankTransfers;

    /**
     * Returns Bank Transfers.
     *
     * @return BankTransfer[]|null
     */
    public function getBankTransfers(): ?array
    {
        return $this->bankTransfers;
    }

    /**
     * Sets Bank Transfers.
     *
     * @maps BankTransfers
     *
     * @param BankTransfer[]|null $bankTransfers
     */
    public function setBankTransfers(?array $bankTransfers): void
    {
        $this->bankTransfers = $bankTransfers;
    }

    /**
     * Converts the BankTransfers object to a human-readable string representation.
     *
     * @return string The string representation of the BankTransfers object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('BankTransfers', ['bankTransfers' => $this->bankTransfers]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->bankTransfers)) {
            $json['BankTransfers'] = $this->bankTransfers;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
