<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class BatchPayments implements \JsonSerializable
{
    /**
     * @var BatchPayment[]|null
     */
    private $batchPayments;

    /**
     * Returns Batch Payments.
     *
     * @return BatchPayment[]|null
     */
    public function getBatchPayments(): ?array
    {
        return $this->batchPayments;
    }

    /**
     * Sets Batch Payments.
     *
     * @maps BatchPayments
     *
     * @param BatchPayment[]|null $batchPayments
     */
    public function setBatchPayments(?array $batchPayments): void
    {
        $this->batchPayments = $batchPayments;
    }

    /**
     * Converts the BatchPayments object to a human-readable string representation.
     *
     * @return string The string representation of the BatchPayments object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('BatchPayments', ['batchPayments' => $this->batchPayments]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->batchPayments)) {
            $json['BatchPayments'] = $this->batchPayments;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
