<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class BrandingTheme implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $brandingThemeID;

    /**
     * @var string|null
     */
    private $createdDateUTC;

    /**
     * @var string|null
     */
    private $logoUrl;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var int|null
     */
    private $sortOrder;

    /**
     * @var string|null
     */
    private $type;

    /**
     * Returns Branding Theme ID.
     * Xero identifier
     */
    public function getBrandingThemeID(): ?string
    {
        return $this->brandingThemeID;
    }

    /**
     * Sets Branding Theme ID.
     * Xero identifier
     *
     * @maps BrandingThemeID
     */
    public function setBrandingThemeID(?string $brandingThemeID): void
    {
        $this->brandingThemeID = $brandingThemeID;
    }

    /**
     * Returns Created Date UTC.
     * UTC timestamp of creation date of branding theme
     */
    public function getCreatedDateUTC(): ?string
    {
        return $this->createdDateUTC;
    }

    /**
     * Sets Created Date UTC.
     * UTC timestamp of creation date of branding theme
     *
     * @maps CreatedDateUTC
     */
    public function setCreatedDateUTC(?string $createdDateUTC): void
    {
        $this->createdDateUTC = $createdDateUTC;
    }

    /**
     * Returns Logo Url.
     * The location of the image file used as the logo on this branding theme
     */
    public function getLogoUrl(): ?string
    {
        return $this->logoUrl;
    }

    /**
     * Sets Logo Url.
     * The location of the image file used as the logo on this branding theme
     *
     * @maps LogoUrl
     */
    public function setLogoUrl(?string $logoUrl): void
    {
        $this->logoUrl = $logoUrl;
    }

    /**
     * Returns Name.
     * Name of branding theme
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * Name of branding theme
     *
     * @maps Name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Sort Order.
     * Integer – ranked order of branding theme. The default branding theme has a value of 0
     */
    public function getSortOrder(): ?int
    {
        return $this->sortOrder;
    }

    /**
     * Sets Sort Order.
     * Integer – ranked order of branding theme. The default branding theme has a value of 0
     *
     * @maps SortOrder
     */
    public function setSortOrder(?int $sortOrder): void
    {
        $this->sortOrder = $sortOrder;
    }

    /**
     * Returns Type.
     * Always INVOICE
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * Always INVOICE
     *
     * @maps Type
     * @factory \XeroAccountingAPILib\Models\TypeEnum::checkValue
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Converts the BrandingTheme object to a human-readable string representation.
     *
     * @return string The string representation of the BrandingTheme object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'BrandingTheme',
            [
                'brandingThemeID' => $this->brandingThemeID,
                'createdDateUTC' => $this->createdDateUTC,
                'logoUrl' => $this->logoUrl,
                'name' => $this->name,
                'sortOrder' => $this->sortOrder,
                'type' => $this->type
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->brandingThemeID)) {
            $json['BrandingThemeID'] = $this->brandingThemeID;
        }
        if (isset($this->createdDateUTC)) {
            $json['CreatedDateUTC']  = $this->createdDateUTC;
        }
        if (isset($this->logoUrl)) {
            $json['LogoUrl']         = $this->logoUrl;
        }
        if (isset($this->name)) {
            $json['Name']            = $this->name;
        }
        if (isset($this->sortOrder)) {
            $json['SortOrder']       = $this->sortOrder;
        }
        if (isset($this->type)) {
            $json['Type']            = TypeEnum::checkValue($this->type);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
