<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class CISOrgSettings implements \JsonSerializable
{
    /**
     * @var CISOrgSetting[]|null
     */
    private $cISSettings;

    /**
     * Returns C IS Settings.
     *
     * @return CISOrgSetting[]|null
     */
    public function getCISSettings(): ?array
    {
        return $this->cISSettings;
    }

    /**
     * Sets C IS Settings.
     *
     * @maps CISSettings
     *
     * @param CISOrgSetting[]|null $cISSettings
     */
    public function setCISSettings(?array $cISSettings): void
    {
        $this->cISSettings = $cISSettings;
    }

    /**
     * Converts the CISOrgSettings object to a human-readable string representation.
     *
     * @return string The string representation of the CISOrgSettings object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('CISOrgSettings', ['cISSettings' => $this->cISSettings]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->cISSettings)) {
            $json['CISSettings'] = $this->cISSettings;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
