<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class CISSetting implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $cISEnabled;

    /**
     * @var float|null
     */
    private $rate;

    /**
     * Returns C IS Enabled.
     * Boolean that describes if the contact is a CIS Subcontractor
     */
    public function getCISEnabled(): ?bool
    {
        return $this->cISEnabled;
    }

    /**
     * Sets C IS Enabled.
     * Boolean that describes if the contact is a CIS Subcontractor
     *
     * @maps CISEnabled
     */
    public function setCISEnabled(?bool $cISEnabled): void
    {
        $this->cISEnabled = $cISEnabled;
    }

    /**
     * Returns Rate.
     * CIS Deduction rate for the contact if he is a subcontractor. If the contact is not CISEnabled, then
     * the rate is not returned
     */
    public function getRate(): ?float
    {
        return $this->rate;
    }

    /**
     * Sets Rate.
     * CIS Deduction rate for the contact if he is a subcontractor. If the contact is not CISEnabled, then
     * the rate is not returned
     *
     * @maps Rate
     */
    public function setRate(?float $rate): void
    {
        $this->rate = $rate;
    }

    /**
     * Converts the CISSetting object to a human-readable string representation.
     *
     * @return string The string representation of the CISSetting object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('CISSetting', ['cISEnabled' => $this->cISEnabled, 'rate' => $this->rate]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->cISEnabled)) {
            $json['CISEnabled'] = $this->cISEnabled;
        }
        if (isset($this->rate)) {
            $json['Rate']       = $this->rate;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
