<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class Contact implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $accountNumber;

    /**
     * @var string|null
     */
    private $accountsPayableTaxType;

    /**
     * @var string|null
     */
    private $accountsReceivableTaxType;

    /**
     * @var Address[]|null
     */
    private $addresses;

    /**
     * @var Attachment[]|null
     */
    private $attachments;

    /**
     * @var Balances|null
     */
    private $balances;

    /**
     * @var string|null
     */
    private $bankAccountDetails;

    /**
     * @var BatchPaymentDetails|null
     */
    private $batchPayments;

    /**
     * @var BrandingTheme|null
     */
    private $brandingTheme;

    /**
     * @var ContactGroup[]|null
     */
    private $contactGroups;

    /**
     * @var string|null
     */
    private $contactID;

    /**
     * @var string|null
     */
    private $contactNumber;

    /**
     * @var ContactPerson[]|null
     */
    private $contactPersons;

    /**
     * @var string|null
     */
    private $contactStatus;

    /**
     * @var string|null
     */
    private $defaultCurrency;

    /**
     * @var float|null
     */
    private $discount;

    /**
     * @var string|null
     */
    private $emailAddress;

    /**
     * @var string|null
     */
    private $firstName;

    /**
     * @var bool|null
     */
    private $hasAttachments = false;

    /**
     * @var bool|null
     */
    private $hasValidationErrors = false;

    /**
     * @var bool|null
     */
    private $isCustomer;

    /**
     * @var bool|null
     */
    private $isSupplier;

    /**
     * @var string|null
     */
    private $lastName;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var PaymentTerm|null
     */
    private $paymentTerms;

    /**
     * @var Phone[]|null
     */
    private $phones;

    /**
     * @var string|null
     */
    private $purchasesDefaultAccountCode;

    /**
     * @var SalesTrackingCategory[]|null
     */
    private $purchasesTrackingCategories;

    /**
     * @var string|null
     */
    private $salesDefaultAccountCode;

    /**
     * @var SalesTrackingCategory[]|null
     */
    private $salesTrackingCategories;

    /**
     * @var string|null
     */
    private $skypeUserName;

    /**
     * @var string|null
     */
    private $statusAttributeString;

    /**
     * @var string|null
     */
    private $taxNumber;

    /**
     * @var string|null
     */
    private $trackingCategoryName;

    /**
     * @var string|null
     */
    private $trackingCategoryOption;

    /**
     * @var string|null
     */
    private $updatedDateUTC;

    /**
     * @var ValidationError[]|null
     */
    private $validationErrors;

    /**
     * @var string|null
     */
    private $website;

    /**
     * @var string|null
     */
    private $xeroNetworkKey;

    /**
     * Returns Account Number.
     * A user defined account number. This can be updated via the API and the Xero UI (max length = 50)
     */
    public function getAccountNumber(): ?string
    {
        return $this->accountNumber;
    }

    /**
     * Sets Account Number.
     * A user defined account number. This can be updated via the API and the Xero UI (max length = 50)
     *
     * @maps AccountNumber
     */
    public function setAccountNumber(?string $accountNumber): void
    {
        $this->accountNumber = $accountNumber;
    }

    /**
     * Returns Accounts Payable Tax Type.
     * The tax type from TaxRates
     */
    public function getAccountsPayableTaxType(): ?string
    {
        return $this->accountsPayableTaxType;
    }

    /**
     * Sets Accounts Payable Tax Type.
     * The tax type from TaxRates
     *
     * @maps AccountsPayableTaxType
     */
    public function setAccountsPayableTaxType(?string $accountsPayableTaxType): void
    {
        $this->accountsPayableTaxType = $accountsPayableTaxType;
    }

    /**
     * Returns Accounts Receivable Tax Type.
     * The tax type from TaxRates
     */
    public function getAccountsReceivableTaxType(): ?string
    {
        return $this->accountsReceivableTaxType;
    }

    /**
     * Sets Accounts Receivable Tax Type.
     * The tax type from TaxRates
     *
     * @maps AccountsReceivableTaxType
     */
    public function setAccountsReceivableTaxType(?string $accountsReceivableTaxType): void
    {
        $this->accountsReceivableTaxType = $accountsReceivableTaxType;
    }

    /**
     * Returns Addresses.
     * Store certain address types for a contact – see address types
     *
     * @return Address[]|null
     */
    public function getAddresses(): ?array
    {
        return $this->addresses;
    }

    /**
     * Sets Addresses.
     * Store certain address types for a contact – see address types
     *
     * @maps Addresses
     *
     * @param Address[]|null $addresses
     */
    public function setAddresses(?array $addresses): void
    {
        $this->addresses = $addresses;
    }

    /**
     * Returns Attachments.
     * Displays array of attachments from the API
     *
     * @return Attachment[]|null
     */
    public function getAttachments(): ?array
    {
        return $this->attachments;
    }

    /**
     * Sets Attachments.
     * Displays array of attachments from the API
     *
     * @maps Attachments
     *
     * @param Attachment[]|null $attachments
     */
    public function setAttachments(?array $attachments): void
    {
        $this->attachments = $attachments;
    }

    /**
     * Returns Balances.
     * The raw AccountsReceivable(sales invoices) and AccountsPayable(bills) outstanding and overdue
     * amounts, not converted to base currency (read only)
     */
    public function getBalances(): ?Balances
    {
        return $this->balances;
    }

    /**
     * Sets Balances.
     * The raw AccountsReceivable(sales invoices) and AccountsPayable(bills) outstanding and overdue
     * amounts, not converted to base currency (read only)
     *
     * @maps Balances
     */
    public function setBalances(?Balances $balances): void
    {
        $this->balances = $balances;
    }

    /**
     * Returns Bank Account Details.
     * Bank account number of contact
     */
    public function getBankAccountDetails(): ?string
    {
        return $this->bankAccountDetails;
    }

    /**
     * Sets Bank Account Details.
     * Bank account number of contact
     *
     * @maps BankAccountDetails
     */
    public function setBankAccountDetails(?string $bankAccountDetails): void
    {
        $this->bankAccountDetails = $bankAccountDetails;
    }

    /**
     * Returns Batch Payments.
     * Bank details for use on a batch payment stored with each contact
     */
    public function getBatchPayments(): ?BatchPaymentDetails
    {
        return $this->batchPayments;
    }

    /**
     * Sets Batch Payments.
     * Bank details for use on a batch payment stored with each contact
     *
     * @maps BatchPayments
     */
    public function setBatchPayments(?BatchPaymentDetails $batchPayments): void
    {
        $this->batchPayments = $batchPayments;
    }

    /**
     * Returns Branding Theme.
     */
    public function getBrandingTheme(): ?BrandingTheme
    {
        return $this->brandingTheme;
    }

    /**
     * Sets Branding Theme.
     *
     * @maps BrandingTheme
     */
    public function setBrandingTheme(?BrandingTheme $brandingTheme): void
    {
        $this->brandingTheme = $brandingTheme;
    }

    /**
     * Returns Contact Groups.
     * Displays which contact groups a contact is included in
     *
     * @return ContactGroup[]|null
     */
    public function getContactGroups(): ?array
    {
        return $this->contactGroups;
    }

    /**
     * Sets Contact Groups.
     * Displays which contact groups a contact is included in
     *
     * @maps ContactGroups
     *
     * @param ContactGroup[]|null $contactGroups
     */
    public function setContactGroups(?array $contactGroups): void
    {
        $this->contactGroups = $contactGroups;
    }

    /**
     * Returns Contact ID.
     * Xero identifier
     */
    public function getContactID(): ?string
    {
        return $this->contactID;
    }

    /**
     * Sets Contact ID.
     * Xero identifier
     *
     * @maps ContactID
     */
    public function setContactID(?string $contactID): void
    {
        $this->contactID = $contactID;
    }

    /**
     * Returns Contact Number.
     * This can be updated via the API only i.e. This field is read only on the Xero contact screen, used
     * to identify contacts in external systems (max length = 50). If the Contact Number is used, this is
     * displayed as Contact Code in the Contacts UI in Xero.
     */
    public function getContactNumber(): ?string
    {
        return $this->contactNumber;
    }

    /**
     * Sets Contact Number.
     * This can be updated via the API only i.e. This field is read only on the Xero contact screen, used
     * to identify contacts in external systems (max length = 50). If the Contact Number is used, this is
     * displayed as Contact Code in the Contacts UI in Xero.
     *
     * @maps ContactNumber
     */
    public function setContactNumber(?string $contactNumber): void
    {
        $this->contactNumber = $contactNumber;
    }

    /**
     * Returns Contact Persons.
     * See contact persons
     *
     * @return ContactPerson[]|null
     */
    public function getContactPersons(): ?array
    {
        return $this->contactPersons;
    }

    /**
     * Sets Contact Persons.
     * See contact persons
     *
     * @maps ContactPersons
     *
     * @param ContactPerson[]|null $contactPersons
     */
    public function setContactPersons(?array $contactPersons): void
    {
        $this->contactPersons = $contactPersons;
    }

    /**
     * Returns Contact Status.
     * Current status of a contact – see contact status types
     */
    public function getContactStatus(): ?string
    {
        return $this->contactStatus;
    }

    /**
     * Sets Contact Status.
     * Current status of a contact – see contact status types
     *
     * @maps ContactStatus
     * @factory \XeroAccountingAPILib\Models\ContactStatusEnum::checkValue
     */
    public function setContactStatus(?string $contactStatus): void
    {
        $this->contactStatus = $contactStatus;
    }

    /**
     * Returns Default Currency.
     * 3 letter alpha code for the currency – see list of currency codes
     */
    public function getDefaultCurrency(): ?string
    {
        return $this->defaultCurrency;
    }

    /**
     * Sets Default Currency.
     * 3 letter alpha code for the currency – see list of currency codes
     *
     * @maps DefaultCurrency
     * @factory \XeroAccountingAPILib\Models\CurrencyCodeEnum::checkValue
     */
    public function setDefaultCurrency(?string $defaultCurrency): void
    {
        $this->defaultCurrency = $defaultCurrency;
    }

    /**
     * Returns Discount.
     * The default discount rate for the contact (read only)
     */
    public function getDiscount(): ?float
    {
        return $this->discount;
    }

    /**
     * Sets Discount.
     * The default discount rate for the contact (read only)
     *
     * @maps Discount
     */
    public function setDiscount(?float $discount): void
    {
        $this->discount = $discount;
    }

    /**
     * Returns Email Address.
     * Email address of contact person (umlauts not supported) (max length  = 255)
     */
    public function getEmailAddress(): ?string
    {
        return $this->emailAddress;
    }

    /**
     * Sets Email Address.
     * Email address of contact person (umlauts not supported) (max length  = 255)
     *
     * @maps EmailAddress
     */
    public function setEmailAddress(?string $emailAddress): void
    {
        $this->emailAddress = $emailAddress;
    }

    /**
     * Returns First Name.
     * First name of contact person (max length = 255)
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * Sets First Name.
     * First name of contact person (max length = 255)
     *
     * @maps FirstName
     */
    public function setFirstName(?string $firstName): void
    {
        $this->firstName = $firstName;
    }

    /**
     * Returns Has Attachments.
     * A boolean to indicate if a contact has an attachment
     */
    public function getHasAttachments(): ?bool
    {
        return $this->hasAttachments;
    }

    /**
     * Sets Has Attachments.
     * A boolean to indicate if a contact has an attachment
     *
     * @maps HasAttachments
     */
    public function setHasAttachments(?bool $hasAttachments): void
    {
        $this->hasAttachments = $hasAttachments;
    }

    /**
     * Returns Has Validation Errors.
     * A boolean to indicate if a contact has an validation errors
     */
    public function getHasValidationErrors(): ?bool
    {
        return $this->hasValidationErrors;
    }

    /**
     * Sets Has Validation Errors.
     * A boolean to indicate if a contact has an validation errors
     *
     * @maps HasValidationErrors
     */
    public function setHasValidationErrors(?bool $hasValidationErrors): void
    {
        $this->hasValidationErrors = $hasValidationErrors;
    }

    /**
     * Returns Is Customer.
     * true or false – Boolean that describes if a contact has any AR invoices entered against them. Cannot
     * be set via PUT or POST – it is automatically set when an accounts receivable invoice is generated
     * against this contact.
     */
    public function getIsCustomer(): ?bool
    {
        return $this->isCustomer;
    }

    /**
     * Sets Is Customer.
     * true or false – Boolean that describes if a contact has any AR invoices entered against them. Cannot
     * be set via PUT or POST – it is automatically set when an accounts receivable invoice is generated
     * against this contact.
     *
     * @maps IsCustomer
     */
    public function setIsCustomer(?bool $isCustomer): void
    {
        $this->isCustomer = $isCustomer;
    }

    /**
     * Returns Is Supplier.
     * true or false – Boolean that describes if a contact that has any AP  invoices entered against them.
     * Cannot be set via PUT or POST – it is automatically set when an accounts payable invoice is
     * generated against this contact.
     */
    public function getIsSupplier(): ?bool
    {
        return $this->isSupplier;
    }

    /**
     * Sets Is Supplier.
     * true or false – Boolean that describes if a contact that has any AP  invoices entered against them.
     * Cannot be set via PUT or POST – it is automatically set when an accounts payable invoice is
     * generated against this contact.
     *
     * @maps IsSupplier
     */
    public function setIsSupplier(?bool $isSupplier): void
    {
        $this->isSupplier = $isSupplier;
    }

    /**
     * Returns Last Name.
     * Last name of contact person (max length = 255)
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
     * Sets Last Name.
     * Last name of contact person (max length = 255)
     *
     * @maps LastName
     */
    public function setLastName(?string $lastName): void
    {
        $this->lastName = $lastName;
    }

    /**
     * Returns Name.
     * Full name of contact/organisation (max length = 255)
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * Full name of contact/organisation (max length = 255)
     *
     * @maps Name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Payment Terms.
     */
    public function getPaymentTerms(): ?PaymentTerm
    {
        return $this->paymentTerms;
    }

    /**
     * Sets Payment Terms.
     *
     * @maps PaymentTerms
     */
    public function setPaymentTerms(?PaymentTerm $paymentTerms): void
    {
        $this->paymentTerms = $paymentTerms;
    }

    /**
     * Returns Phones.
     * Store certain phone types for a contact – see phone types
     *
     * @return Phone[]|null
     */
    public function getPhones(): ?array
    {
        return $this->phones;
    }

    /**
     * Sets Phones.
     * Store certain phone types for a contact – see phone types
     *
     * @maps Phones
     *
     * @param Phone[]|null $phones
     */
    public function setPhones(?array $phones): void
    {
        $this->phones = $phones;
    }

    /**
     * Returns Purchases Default Account Code.
     * The default purchases account code for contacts
     */
    public function getPurchasesDefaultAccountCode(): ?string
    {
        return $this->purchasesDefaultAccountCode;
    }

    /**
     * Sets Purchases Default Account Code.
     * The default purchases account code for contacts
     *
     * @maps PurchasesDefaultAccountCode
     */
    public function setPurchasesDefaultAccountCode(?string $purchasesDefaultAccountCode): void
    {
        $this->purchasesDefaultAccountCode = $purchasesDefaultAccountCode;
    }

    /**
     * Returns Purchases Tracking Categories.
     * The default purchases tracking categories for contacts
     *
     * @return SalesTrackingCategory[]|null
     */
    public function getPurchasesTrackingCategories(): ?array
    {
        return $this->purchasesTrackingCategories;
    }

    /**
     * Sets Purchases Tracking Categories.
     * The default purchases tracking categories for contacts
     *
     * @maps PurchasesTrackingCategories
     *
     * @param SalesTrackingCategory[]|null $purchasesTrackingCategories
     */
    public function setPurchasesTrackingCategories(?array $purchasesTrackingCategories): void
    {
        $this->purchasesTrackingCategories = $purchasesTrackingCategories;
    }

    /**
     * Returns Sales Default Account Code.
     * The default sales account code for contacts
     */
    public function getSalesDefaultAccountCode(): ?string
    {
        return $this->salesDefaultAccountCode;
    }

    /**
     * Sets Sales Default Account Code.
     * The default sales account code for contacts
     *
     * @maps SalesDefaultAccountCode
     */
    public function setSalesDefaultAccountCode(?string $salesDefaultAccountCode): void
    {
        $this->salesDefaultAccountCode = $salesDefaultAccountCode;
    }

    /**
     * Returns Sales Tracking Categories.
     * The default sales tracking categories for contacts
     *
     * @return SalesTrackingCategory[]|null
     */
    public function getSalesTrackingCategories(): ?array
    {
        return $this->salesTrackingCategories;
    }

    /**
     * Sets Sales Tracking Categories.
     * The default sales tracking categories for contacts
     *
     * @maps SalesTrackingCategories
     *
     * @param SalesTrackingCategory[]|null $salesTrackingCategories
     */
    public function setSalesTrackingCategories(?array $salesTrackingCategories): void
    {
        $this->salesTrackingCategories = $salesTrackingCategories;
    }

    /**
     * Returns Skype User Name.
     * Skype user name of contact
     */
    public function getSkypeUserName(): ?string
    {
        return $this->skypeUserName;
    }

    /**
     * Sets Skype User Name.
     * Skype user name of contact
     *
     * @maps SkypeUserName
     */
    public function setSkypeUserName(?string $skypeUserName): void
    {
        $this->skypeUserName = $skypeUserName;
    }

    /**
     * Returns Status Attribute String.
     * Status of object
     */
    public function getStatusAttributeString(): ?string
    {
        return $this->statusAttributeString;
    }

    /**
     * Sets Status Attribute String.
     * Status of object
     *
     * @maps StatusAttributeString
     */
    public function setStatusAttributeString(?string $statusAttributeString): void
    {
        $this->statusAttributeString = $statusAttributeString;
    }

    /**
     * Returns Tax Number.
     * Tax number of contact – this is also known as the ABN (Australia), GST Number (New Zealand), VAT
     * Number (UK) or Tax ID Number (US and global) in the Xero UI depending on which regionalized version
     * of Xero you are using (max length = 50)
     */
    public function getTaxNumber(): ?string
    {
        return $this->taxNumber;
    }

    /**
     * Sets Tax Number.
     * Tax number of contact – this is also known as the ABN (Australia), GST Number (New Zealand), VAT
     * Number (UK) or Tax ID Number (US and global) in the Xero UI depending on which regionalized version
     * of Xero you are using (max length = 50)
     *
     * @maps TaxNumber
     */
    public function setTaxNumber(?string $taxNumber): void
    {
        $this->taxNumber = $taxNumber;
    }

    /**
     * Returns Tracking Category Name.
     * The name of the Tracking Category assigned to the contact under SalesTrackingCategories and
     * PurchasesTrackingCategories
     */
    public function getTrackingCategoryName(): ?string
    {
        return $this->trackingCategoryName;
    }

    /**
     * Sets Tracking Category Name.
     * The name of the Tracking Category assigned to the contact under SalesTrackingCategories and
     * PurchasesTrackingCategories
     *
     * @maps TrackingCategoryName
     */
    public function setTrackingCategoryName(?string $trackingCategoryName): void
    {
        $this->trackingCategoryName = $trackingCategoryName;
    }

    /**
     * Returns Tracking Category Option.
     * The name of the Tracking Option assigned to the contact under SalesTrackingCategories and
     * PurchasesTrackingCategories
     */
    public function getTrackingCategoryOption(): ?string
    {
        return $this->trackingCategoryOption;
    }

    /**
     * Sets Tracking Category Option.
     * The name of the Tracking Option assigned to the contact under SalesTrackingCategories and
     * PurchasesTrackingCategories
     *
     * @maps TrackingCategoryOption
     */
    public function setTrackingCategoryOption(?string $trackingCategoryOption): void
    {
        $this->trackingCategoryOption = $trackingCategoryOption;
    }

    /**
     * Returns Updated Date UTC.
     * UTC timestamp of last update to contact
     */
    public function getUpdatedDateUTC(): ?string
    {
        return $this->updatedDateUTC;
    }

    /**
     * Sets Updated Date UTC.
     * UTC timestamp of last update to contact
     *
     * @maps UpdatedDateUTC
     */
    public function setUpdatedDateUTC(?string $updatedDateUTC): void
    {
        $this->updatedDateUTC = $updatedDateUTC;
    }

    /**
     * Returns Validation Errors.
     * Displays validation errors returned from the API
     *
     * @return ValidationError[]|null
     */
    public function getValidationErrors(): ?array
    {
        return $this->validationErrors;
    }

    /**
     * Sets Validation Errors.
     * Displays validation errors returned from the API
     *
     * @maps ValidationErrors
     *
     * @param ValidationError[]|null $validationErrors
     */
    public function setValidationErrors(?array $validationErrors): void
    {
        $this->validationErrors = $validationErrors;
    }

    /**
     * Returns Website.
     * Website address for contact (read only)
     */
    public function getWebsite(): ?string
    {
        return $this->website;
    }

    /**
     * Sets Website.
     * Website address for contact (read only)
     *
     * @maps Website
     */
    public function setWebsite(?string $website): void
    {
        $this->website = $website;
    }

    /**
     * Returns Xero Network Key.
     * Store XeroNetworkKey for contacts.
     */
    public function getXeroNetworkKey(): ?string
    {
        return $this->xeroNetworkKey;
    }

    /**
     * Sets Xero Network Key.
     * Store XeroNetworkKey for contacts.
     *
     * @maps XeroNetworkKey
     */
    public function setXeroNetworkKey(?string $xeroNetworkKey): void
    {
        $this->xeroNetworkKey = $xeroNetworkKey;
    }

    /**
     * Converts the Contact object to a human-readable string representation.
     *
     * @return string The string representation of the Contact object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Contact',
            [
                'accountNumber' => $this->accountNumber,
                'accountsPayableTaxType' => $this->accountsPayableTaxType,
                'accountsReceivableTaxType' => $this->accountsReceivableTaxType,
                'addresses' => $this->addresses,
                'attachments' => $this->attachments,
                'balances' => $this->balances,
                'bankAccountDetails' => $this->bankAccountDetails,
                'batchPayments' => $this->batchPayments,
                'brandingTheme' => $this->brandingTheme,
                'contactGroups' => $this->contactGroups,
                'contactID' => $this->contactID,
                'contactNumber' => $this->contactNumber,
                'contactPersons' => $this->contactPersons,
                'contactStatus' => $this->contactStatus,
                'defaultCurrency' => $this->defaultCurrency,
                'discount' => $this->discount,
                'emailAddress' => $this->emailAddress,
                'firstName' => $this->firstName,
                'hasAttachments' => $this->hasAttachments,
                'hasValidationErrors' => $this->hasValidationErrors,
                'isCustomer' => $this->isCustomer,
                'isSupplier' => $this->isSupplier,
                'lastName' => $this->lastName,
                'name' => $this->name,
                'paymentTerms' => $this->paymentTerms,
                'phones' => $this->phones,
                'purchasesDefaultAccountCode' => $this->purchasesDefaultAccountCode,
                'purchasesTrackingCategories' => $this->purchasesTrackingCategories,
                'salesDefaultAccountCode' => $this->salesDefaultAccountCode,
                'salesTrackingCategories' => $this->salesTrackingCategories,
                'skypeUserName' => $this->skypeUserName,
                'statusAttributeString' => $this->statusAttributeString,
                'taxNumber' => $this->taxNumber,
                'trackingCategoryName' => $this->trackingCategoryName,
                'trackingCategoryOption' => $this->trackingCategoryOption,
                'updatedDateUTC' => $this->updatedDateUTC,
                'validationErrors' => $this->validationErrors,
                'website' => $this->website,
                'xeroNetworkKey' => $this->xeroNetworkKey
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->accountNumber)) {
            $json['AccountNumber']               = $this->accountNumber;
        }
        if (isset($this->accountsPayableTaxType)) {
            $json['AccountsPayableTaxType']      = $this->accountsPayableTaxType;
        }
        if (isset($this->accountsReceivableTaxType)) {
            $json['AccountsReceivableTaxType']   = $this->accountsReceivableTaxType;
        }
        if (isset($this->addresses)) {
            $json['Addresses']                   = $this->addresses;
        }
        if (isset($this->attachments)) {
            $json['Attachments']                 = $this->attachments;
        }
        if (isset($this->balances)) {
            $json['Balances']                    = $this->balances;
        }
        if (isset($this->bankAccountDetails)) {
            $json['BankAccountDetails']          = $this->bankAccountDetails;
        }
        if (isset($this->batchPayments)) {
            $json['BatchPayments']               = $this->batchPayments;
        }
        if (isset($this->brandingTheme)) {
            $json['BrandingTheme']               = $this->brandingTheme;
        }
        if (isset($this->contactGroups)) {
            $json['ContactGroups']               = $this->contactGroups;
        }
        if (isset($this->contactID)) {
            $json['ContactID']                   = $this->contactID;
        }
        if (isset($this->contactNumber)) {
            $json['ContactNumber']               = $this->contactNumber;
        }
        if (isset($this->contactPersons)) {
            $json['ContactPersons']              = $this->contactPersons;
        }
        if (isset($this->contactStatus)) {
            $json['ContactStatus']               = ContactStatusEnum::checkValue($this->contactStatus);
        }
        if (isset($this->defaultCurrency)) {
            $json['DefaultCurrency']             = CurrencyCodeEnum::checkValue($this->defaultCurrency);
        }
        if (isset($this->discount)) {
            $json['Discount']                    = $this->discount;
        }
        if (isset($this->emailAddress)) {
            $json['EmailAddress']                = $this->emailAddress;
        }
        if (isset($this->firstName)) {
            $json['FirstName']                   = $this->firstName;
        }
        if (isset($this->hasAttachments)) {
            $json['HasAttachments']              = $this->hasAttachments;
        }
        if (isset($this->hasValidationErrors)) {
            $json['HasValidationErrors']         = $this->hasValidationErrors;
        }
        if (isset($this->isCustomer)) {
            $json['IsCustomer']                  = $this->isCustomer;
        }
        if (isset($this->isSupplier)) {
            $json['IsSupplier']                  = $this->isSupplier;
        }
        if (isset($this->lastName)) {
            $json['LastName']                    = $this->lastName;
        }
        if (isset($this->name)) {
            $json['Name']                        = $this->name;
        }
        if (isset($this->paymentTerms)) {
            $json['PaymentTerms']                = $this->paymentTerms;
        }
        if (isset($this->phones)) {
            $json['Phones']                      = $this->phones;
        }
        if (isset($this->purchasesDefaultAccountCode)) {
            $json['PurchasesDefaultAccountCode'] = $this->purchasesDefaultAccountCode;
        }
        if (isset($this->purchasesTrackingCategories)) {
            $json['PurchasesTrackingCategories'] = $this->purchasesTrackingCategories;
        }
        if (isset($this->salesDefaultAccountCode)) {
            $json['SalesDefaultAccountCode']     = $this->salesDefaultAccountCode;
        }
        if (isset($this->salesTrackingCategories)) {
            $json['SalesTrackingCategories']     = $this->salesTrackingCategories;
        }
        if (isset($this->skypeUserName)) {
            $json['SkypeUserName']               = $this->skypeUserName;
        }
        if (isset($this->statusAttributeString)) {
            $json['StatusAttributeString']       = $this->statusAttributeString;
        }
        if (isset($this->taxNumber)) {
            $json['TaxNumber']                   = $this->taxNumber;
        }
        if (isset($this->trackingCategoryName)) {
            $json['TrackingCategoryName']        = $this->trackingCategoryName;
        }
        if (isset($this->trackingCategoryOption)) {
            $json['TrackingCategoryOption']      = $this->trackingCategoryOption;
        }
        if (isset($this->updatedDateUTC)) {
            $json['UpdatedDateUTC']              = $this->updatedDateUTC;
        }
        if (isset($this->validationErrors)) {
            $json['ValidationErrors']            = $this->validationErrors;
        }
        if (isset($this->website)) {
            $json['Website']                     = $this->website;
        }
        if (isset($this->xeroNetworkKey)) {
            $json['XeroNetworkKey']              = $this->xeroNetworkKey;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
