<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class ContactPerson implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $emailAddress;

    /**
     * @var string|null
     */
    private $firstName;

    /**
     * @var bool|null
     */
    private $includeInEmails;

    /**
     * @var string|null
     */
    private $lastName;

    /**
     * Returns Email Address.
     * Email address of person
     */
    public function getEmailAddress(): ?string
    {
        return $this->emailAddress;
    }

    /**
     * Sets Email Address.
     * Email address of person
     *
     * @maps EmailAddress
     */
    public function setEmailAddress(?string $emailAddress): void
    {
        $this->emailAddress = $emailAddress;
    }

    /**
     * Returns First Name.
     * First name of person
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * Sets First Name.
     * First name of person
     *
     * @maps FirstName
     */
    public function setFirstName(?string $firstName): void
    {
        $this->firstName = $firstName;
    }

    /**
     * Returns Include in Emails.
     * boolean to indicate whether contact should be included on emails with invoices etc.
     */
    public function getIncludeInEmails(): ?bool
    {
        return $this->includeInEmails;
    }

    /**
     * Sets Include in Emails.
     * boolean to indicate whether contact should be included on emails with invoices etc.
     *
     * @maps IncludeInEmails
     */
    public function setIncludeInEmails(?bool $includeInEmails): void
    {
        $this->includeInEmails = $includeInEmails;
    }

    /**
     * Returns Last Name.
     * Last name of person
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
     * Sets Last Name.
     * Last name of person
     *
     * @maps LastName
     */
    public function setLastName(?string $lastName): void
    {
        $this->lastName = $lastName;
    }

    /**
     * Converts the ContactPerson object to a human-readable string representation.
     *
     * @return string The string representation of the ContactPerson object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ContactPerson',
            [
                'emailAddress' => $this->emailAddress,
                'firstName' => $this->firstName,
                'includeInEmails' => $this->includeInEmails,
                'lastName' => $this->lastName
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->emailAddress)) {
            $json['EmailAddress']    = $this->emailAddress;
        }
        if (isset($this->firstName)) {
            $json['FirstName']       = $this->firstName;
        }
        if (isset($this->includeInEmails)) {
            $json['IncludeInEmails'] = $this->includeInEmails;
        }
        if (isset($this->lastName)) {
            $json['LastName']        = $this->lastName;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
