<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

/**
 * The date when the organisation starts using Xero
 */
class ConversionDate implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $month;

    /**
     * @var int|null
     */
    private $year;

    /**
     * Returns Month.
     * The month the organisation starts using Xero. Value is an integer between 1 and 12
     */
    public function getMonth(): ?int
    {
        return $this->month;
    }

    /**
     * Sets Month.
     * The month the organisation starts using Xero. Value is an integer between 1 and 12
     *
     * @maps Month
     */
    public function setMonth(?int $month): void
    {
        $this->month = $month;
    }

    /**
     * Returns Year.
     * The year the organisation starts using Xero. Value is an integer greater than 2006
     */
    public function getYear(): ?int
    {
        return $this->year;
    }

    /**
     * Sets Year.
     * The year the organisation starts using Xero. Value is an integer greater than 2006
     *
     * @maps Year
     */
    public function setYear(?int $year): void
    {
        $this->year = $year;
    }

    /**
     * Converts the ConversionDate object to a human-readable string representation.
     *
     * @return string The string representation of the ConversionDate object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('ConversionDate', ['month' => $this->month, 'year' => $this->year]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->month)) {
            $json['Month'] = $this->month;
        }
        if (isset($this->year)) {
            $json['Year']  = $this->year;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
