<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class CreditNote implements \JsonSerializable
{
    /**
     * @var Allocation[]|null
     */
    private $allocations;

    /**
     * @var float|null
     */
    private $appliedAmount;

    /**
     * @var string|null
     */
    private $brandingThemeID;

    /**
     * @var float|null
     */
    private $cISDeduction;

    /**
     * @var float|null
     */
    private $cISRate;

    /**
     * @var Contact|null
     */
    private $contact;

    /**
     * @var string|null
     */
    private $creditNoteID;

    /**
     * @var string|null
     */
    private $creditNoteNumber;

    /**
     * @var string|null
     */
    private $currencyCode;

    /**
     * @var float|null
     */
    private $currencyRate;

    /**
     * @var string|null
     */
    private $date;

    /**
     * @var string|null
     */
    private $dueDate;

    /**
     * @var string|null
     */
    private $fullyPaidOnDate;

    /**
     * @var bool|null
     */
    private $hasAttachments = false;

    /**
     * @var bool|null
     */
    private $hasErrors = false;

    /**
     * @var string|null
     */
    private $lineAmountTypes;

    /**
     * @var LineItem[]|null
     */
    private $lineItems;

    /**
     * @var Payment[]|null
     */
    private $payments;

    /**
     * @var string|null
     */
    private $reference;

    /**
     * @var float|null
     */
    private $remainingCredit;

    /**
     * @var bool|null
     */
    private $sentToContact;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $statusAttributeString;

    /**
     * @var float|null
     */
    private $subTotal;

    /**
     * @var float|null
     */
    private $total;

    /**
     * @var float|null
     */
    private $totalTax;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var string|null
     */
    private $updatedDateUTC;

    /**
     * @var ValidationError[]|null
     */
    private $validationErrors;

    /**
     * @var ValidationError[]|null
     */
    private $warnings;

    /**
     * Returns Allocations.
     * See Allocations
     *
     * @return Allocation[]|null
     */
    public function getAllocations(): ?array
    {
        return $this->allocations;
    }

    /**
     * Sets Allocations.
     * See Allocations
     *
     * @maps Allocations
     *
     * @param Allocation[]|null $allocations
     */
    public function setAllocations(?array $allocations): void
    {
        $this->allocations = $allocations;
    }

    /**
     * Returns Applied Amount.
     * The amount of applied to an invoice
     */
    public function getAppliedAmount(): ?float
    {
        return $this->appliedAmount;
    }

    /**
     * Sets Applied Amount.
     * The amount of applied to an invoice
     *
     * @maps AppliedAmount
     */
    public function setAppliedAmount(?float $appliedAmount): void
    {
        $this->appliedAmount = $appliedAmount;
    }

    /**
     * Returns Branding Theme ID.
     * See BrandingThemes
     */
    public function getBrandingThemeID(): ?string
    {
        return $this->brandingThemeID;
    }

    /**
     * Sets Branding Theme ID.
     * See BrandingThemes
     *
     * @maps BrandingThemeID
     */
    public function setBrandingThemeID(?string $brandingThemeID): void
    {
        $this->brandingThemeID = $brandingThemeID;
    }

    /**
     * Returns C IS Deduction.
     * CIS deduction for UK contractors
     */
    public function getCISDeduction(): ?float
    {
        return $this->cISDeduction;
    }

    /**
     * Sets C IS Deduction.
     * CIS deduction for UK contractors
     *
     * @maps CISDeduction
     */
    public function setCISDeduction(?float $cISDeduction): void
    {
        $this->cISDeduction = $cISDeduction;
    }

    /**
     * Returns C IS Rate.
     * CIS Deduction rate for the organisation
     */
    public function getCISRate(): ?float
    {
        return $this->cISRate;
    }

    /**
     * Sets C IS Rate.
     * CIS Deduction rate for the organisation
     *
     * @maps CISRate
     */
    public function setCISRate(?float $cISRate): void
    {
        $this->cISRate = $cISRate;
    }

    /**
     * Returns Contact.
     */
    public function getContact(): ?Contact
    {
        return $this->contact;
    }

    /**
     * Sets Contact.
     *
     * @maps Contact
     */
    public function setContact(?Contact $contact): void
    {
        $this->contact = $contact;
    }

    /**
     * Returns Credit Note ID.
     * Xero generated unique identifier
     */
    public function getCreditNoteID(): ?string
    {
        return $this->creditNoteID;
    }

    /**
     * Sets Credit Note ID.
     * Xero generated unique identifier
     *
     * @maps CreditNoteID
     */
    public function setCreditNoteID(?string $creditNoteID): void
    {
        $this->creditNoteID = $creditNoteID;
    }

    /**
     * Returns Credit Note Number.
     * ACCRECCREDIT – Unique alpha numeric code identifying credit note (when missing will auto-generate
     * from your Organisation Invoice Settings)
     */
    public function getCreditNoteNumber(): ?string
    {
        return $this->creditNoteNumber;
    }

    /**
     * Sets Credit Note Number.
     * ACCRECCREDIT – Unique alpha numeric code identifying credit note (when missing will auto-generate
     * from your Organisation Invoice Settings)
     *
     * @maps CreditNoteNumber
     */
    public function setCreditNoteNumber(?string $creditNoteNumber): void
    {
        $this->creditNoteNumber = $creditNoteNumber;
    }

    /**
     * Returns Currency Code.
     * 3 letter alpha code for the currency – see list of currency codes
     */
    public function getCurrencyCode(): ?string
    {
        return $this->currencyCode;
    }

    /**
     * Sets Currency Code.
     * 3 letter alpha code for the currency – see list of currency codes
     *
     * @maps CurrencyCode
     * @factory \XeroAccountingAPILib\Models\CurrencyCodeEnum::checkValue
     */
    public function setCurrencyCode(?string $currencyCode): void
    {
        $this->currencyCode = $currencyCode;
    }

    /**
     * Returns Currency Rate.
     * The currency rate for a multicurrency invoice. If no rate is specified, the XE.com day rate is used
     */
    public function getCurrencyRate(): ?float
    {
        return $this->currencyRate;
    }

    /**
     * Sets Currency Rate.
     * The currency rate for a multicurrency invoice. If no rate is specified, the XE.com day rate is used
     *
     * @maps CurrencyRate
     */
    public function setCurrencyRate(?float $currencyRate): void
    {
        $this->currencyRate = $currencyRate;
    }

    /**
     * Returns Date.
     * The date the credit note is issued YYYY-MM-DD. If the Date element is not specified then it will
     * default to the current date based on the timezone setting of the organisation
     */
    public function getDate(): ?string
    {
        return $this->date;
    }

    /**
     * Sets Date.
     * The date the credit note is issued YYYY-MM-DD. If the Date element is not specified then it will
     * default to the current date based on the timezone setting of the organisation
     *
     * @maps Date
     */
    public function setDate(?string $date): void
    {
        $this->date = $date;
    }

    /**
     * Returns Due Date.
     * Date invoice is due – YYYY-MM-DD
     */
    public function getDueDate(): ?string
    {
        return $this->dueDate;
    }

    /**
     * Sets Due Date.
     * Date invoice is due – YYYY-MM-DD
     *
     * @maps DueDate
     */
    public function setDueDate(?string $dueDate): void
    {
        $this->dueDate = $dueDate;
    }

    /**
     * Returns Fully Paid on Date.
     * Date when credit note was fully paid(UTC format)
     */
    public function getFullyPaidOnDate(): ?string
    {
        return $this->fullyPaidOnDate;
    }

    /**
     * Sets Fully Paid on Date.
     * Date when credit note was fully paid(UTC format)
     *
     * @maps FullyPaidOnDate
     */
    public function setFullyPaidOnDate(?string $fullyPaidOnDate): void
    {
        $this->fullyPaidOnDate = $fullyPaidOnDate;
    }

    /**
     * Returns Has Attachments.
     * boolean to indicate if a credit note has an attachment
     */
    public function getHasAttachments(): ?bool
    {
        return $this->hasAttachments;
    }

    /**
     * Sets Has Attachments.
     * boolean to indicate if a credit note has an attachment
     *
     * @maps HasAttachments
     */
    public function setHasAttachments(?bool $hasAttachments): void
    {
        $this->hasAttachments = $hasAttachments;
    }

    /**
     * Returns Has Errors.
     * A boolean to indicate if a credit note has an validation errors
     */
    public function getHasErrors(): ?bool
    {
        return $this->hasErrors;
    }

    /**
     * Sets Has Errors.
     * A boolean to indicate if a credit note has an validation errors
     *
     * @maps HasErrors
     */
    public function setHasErrors(?bool $hasErrors): void
    {
        $this->hasErrors = $hasErrors;
    }

    /**
     * Returns Line Amount Types.
     * Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount
     * Types
     */
    public function getLineAmountTypes(): ?string
    {
        return $this->lineAmountTypes;
    }

    /**
     * Sets Line Amount Types.
     * Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount
     * Types
     *
     * @maps LineAmountTypes
     * @factory \XeroAccountingAPILib\Models\LineAmountTypesEnum::checkValue
     */
    public function setLineAmountTypes(?string $lineAmountTypes): void
    {
        $this->lineAmountTypes = $lineAmountTypes;
    }

    /**
     * Returns Line Items.
     * See Invoice Line Items
     *
     * @return LineItem[]|null
     */
    public function getLineItems(): ?array
    {
        return $this->lineItems;
    }

    /**
     * Sets Line Items.
     * See Invoice Line Items
     *
     * @maps LineItems
     *
     * @param LineItem[]|null $lineItems
     */
    public function setLineItems(?array $lineItems): void
    {
        $this->lineItems = $lineItems;
    }

    /**
     * Returns Payments.
     * See Payments
     *
     * @return Payment[]|null
     */
    public function getPayments(): ?array
    {
        return $this->payments;
    }

    /**
     * Sets Payments.
     * See Payments
     *
     * @maps Payments
     *
     * @param Payment[]|null $payments
     */
    public function setPayments(?array $payments): void
    {
        $this->payments = $payments;
    }

    /**
     * Returns Reference.
     * ACCRECCREDIT only – additional reference number
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     * ACCRECCREDIT only – additional reference number
     *
     * @maps Reference
     */
    public function setReference(?string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Returns Remaining Credit.
     * The remaining credit balance on the Credit Note
     */
    public function getRemainingCredit(): ?float
    {
        return $this->remainingCredit;
    }

    /**
     * Sets Remaining Credit.
     * The remaining credit balance on the Credit Note
     *
     * @maps RemainingCredit
     */
    public function setRemainingCredit(?float $remainingCredit): void
    {
        $this->remainingCredit = $remainingCredit;
    }

    /**
     * Returns Sent to Contact.
     * boolean to indicate if a credit note has been sent to a contact via  the Xero app (currently read
     * only)
     */
    public function getSentToContact(): ?bool
    {
        return $this->sentToContact;
    }

    /**
     * Sets Sent to Contact.
     * boolean to indicate if a credit note has been sent to a contact via  the Xero app (currently read
     * only)
     *
     * @maps SentToContact
     */
    public function setSentToContact(?bool $sentToContact): void
    {
        $this->sentToContact = $sentToContact;
    }

    /**
     * Returns Status.
     * See Credit Note Status Codes
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * See Credit Note Status Codes
     *
     * @maps Status
     * @factory \XeroAccountingAPILib\Models\Status7Enum::checkValue
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Status Attribute String.
     * A string to indicate if a invoice status
     */
    public function getStatusAttributeString(): ?string
    {
        return $this->statusAttributeString;
    }

    /**
     * Sets Status Attribute String.
     * A string to indicate if a invoice status
     *
     * @maps StatusAttributeString
     */
    public function setStatusAttributeString(?string $statusAttributeString): void
    {
        $this->statusAttributeString = $statusAttributeString;
    }

    /**
     * Returns Sub Total.
     * The subtotal of the credit note excluding taxes
     */
    public function getSubTotal(): ?float
    {
        return $this->subTotal;
    }

    /**
     * Sets Sub Total.
     * The subtotal of the credit note excluding taxes
     *
     * @maps SubTotal
     */
    public function setSubTotal(?float $subTotal): void
    {
        $this->subTotal = $subTotal;
    }

    /**
     * Returns Total.
     * The total of the Credit Note(subtotal + total tax)
     */
    public function getTotal(): ?float
    {
        return $this->total;
    }

    /**
     * Sets Total.
     * The total of the Credit Note(subtotal + total tax)
     *
     * @maps Total
     */
    public function setTotal(?float $total): void
    {
        $this->total = $total;
    }

    /**
     * Returns Total Tax.
     * The total tax on the credit note
     */
    public function getTotalTax(): ?float
    {
        return $this->totalTax;
    }

    /**
     * Sets Total Tax.
     * The total tax on the credit note
     *
     * @maps TotalTax
     */
    public function setTotalTax(?float $totalTax): void
    {
        $this->totalTax = $totalTax;
    }

    /**
     * Returns Type.
     * See Credit Note Types
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * See Credit Note Types
     *
     * @maps Type
     * @factory \XeroAccountingAPILib\Models\Type4Enum::checkValue
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Updated Date UTC.
     * UTC timestamp of last update to the credit note
     */
    public function getUpdatedDateUTC(): ?string
    {
        return $this->updatedDateUTC;
    }

    /**
     * Sets Updated Date UTC.
     * UTC timestamp of last update to the credit note
     *
     * @maps UpdatedDateUTC
     */
    public function setUpdatedDateUTC(?string $updatedDateUTC): void
    {
        $this->updatedDateUTC = $updatedDateUTC;
    }

    /**
     * Returns Validation Errors.
     * Displays array of validation error messages from the API
     *
     * @return ValidationError[]|null
     */
    public function getValidationErrors(): ?array
    {
        return $this->validationErrors;
    }

    /**
     * Sets Validation Errors.
     * Displays array of validation error messages from the API
     *
     * @maps ValidationErrors
     *
     * @param ValidationError[]|null $validationErrors
     */
    public function setValidationErrors(?array $validationErrors): void
    {
        $this->validationErrors = $validationErrors;
    }

    /**
     * Returns Warnings.
     * Displays array of warning messages from the API
     *
     * @return ValidationError[]|null
     */
    public function getWarnings(): ?array
    {
        return $this->warnings;
    }

    /**
     * Sets Warnings.
     * Displays array of warning messages from the API
     *
     * @maps Warnings
     *
     * @param ValidationError[]|null $warnings
     */
    public function setWarnings(?array $warnings): void
    {
        $this->warnings = $warnings;
    }

    /**
     * Converts the CreditNote object to a human-readable string representation.
     *
     * @return string The string representation of the CreditNote object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreditNote',
            [
                'allocations' => $this->allocations,
                'appliedAmount' => $this->appliedAmount,
                'brandingThemeID' => $this->brandingThemeID,
                'cISDeduction' => $this->cISDeduction,
                'cISRate' => $this->cISRate,
                'contact' => $this->contact,
                'creditNoteID' => $this->creditNoteID,
                'creditNoteNumber' => $this->creditNoteNumber,
                'currencyCode' => $this->currencyCode,
                'currencyRate' => $this->currencyRate,
                'date' => $this->date,
                'dueDate' => $this->dueDate,
                'fullyPaidOnDate' => $this->fullyPaidOnDate,
                'hasAttachments' => $this->hasAttachments,
                'hasErrors' => $this->hasErrors,
                'lineAmountTypes' => $this->lineAmountTypes,
                'lineItems' => $this->lineItems,
                'payments' => $this->payments,
                'reference' => $this->reference,
                'remainingCredit' => $this->remainingCredit,
                'sentToContact' => $this->sentToContact,
                'status' => $this->status,
                'statusAttributeString' => $this->statusAttributeString,
                'subTotal' => $this->subTotal,
                'total' => $this->total,
                'totalTax' => $this->totalTax,
                'type' => $this->type,
                'updatedDateUTC' => $this->updatedDateUTC,
                'validationErrors' => $this->validationErrors,
                'warnings' => $this->warnings
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->allocations)) {
            $json['Allocations']           = $this->allocations;
        }
        if (isset($this->appliedAmount)) {
            $json['AppliedAmount']         = $this->appliedAmount;
        }
        if (isset($this->brandingThemeID)) {
            $json['BrandingThemeID']       = $this->brandingThemeID;
        }
        if (isset($this->cISDeduction)) {
            $json['CISDeduction']          = $this->cISDeduction;
        }
        if (isset($this->cISRate)) {
            $json['CISRate']               = $this->cISRate;
        }
        if (isset($this->contact)) {
            $json['Contact']               = $this->contact;
        }
        if (isset($this->creditNoteID)) {
            $json['CreditNoteID']          = $this->creditNoteID;
        }
        if (isset($this->creditNoteNumber)) {
            $json['CreditNoteNumber']      = $this->creditNoteNumber;
        }
        if (isset($this->currencyCode)) {
            $json['CurrencyCode']          = CurrencyCodeEnum::checkValue($this->currencyCode);
        }
        if (isset($this->currencyRate)) {
            $json['CurrencyRate']          = $this->currencyRate;
        }
        if (isset($this->date)) {
            $json['Date']                  = $this->date;
        }
        if (isset($this->dueDate)) {
            $json['DueDate']               = $this->dueDate;
        }
        if (isset($this->fullyPaidOnDate)) {
            $json['FullyPaidOnDate']       = $this->fullyPaidOnDate;
        }
        if (isset($this->hasAttachments)) {
            $json['HasAttachments']        = $this->hasAttachments;
        }
        if (isset($this->hasErrors)) {
            $json['HasErrors']             = $this->hasErrors;
        }
        if (isset($this->lineAmountTypes)) {
            $json['LineAmountTypes']       = LineAmountTypesEnum::checkValue($this->lineAmountTypes);
        }
        if (isset($this->lineItems)) {
            $json['LineItems']             = $this->lineItems;
        }
        if (isset($this->payments)) {
            $json['Payments']              = $this->payments;
        }
        if (isset($this->reference)) {
            $json['Reference']             = $this->reference;
        }
        if (isset($this->remainingCredit)) {
            $json['RemainingCredit']       = $this->remainingCredit;
        }
        if (isset($this->sentToContact)) {
            $json['SentToContact']         = $this->sentToContact;
        }
        if (isset($this->status)) {
            $json['Status']                = Status7Enum::checkValue($this->status);
        }
        if (isset($this->statusAttributeString)) {
            $json['StatusAttributeString'] = $this->statusAttributeString;
        }
        if (isset($this->subTotal)) {
            $json['SubTotal']              = $this->subTotal;
        }
        if (isset($this->total)) {
            $json['Total']                 = $this->total;
        }
        if (isset($this->totalTax)) {
            $json['TotalTax']              = $this->totalTax;
        }
        if (isset($this->type)) {
            $json['Type']                  = Type4Enum::checkValue($this->type);
        }
        if (isset($this->updatedDateUTC)) {
            $json['UpdatedDateUTC']        = $this->updatedDateUTC;
        }
        if (isset($this->validationErrors)) {
            $json['ValidationErrors']      = $this->validationErrors;
        }
        if (isset($this->warnings)) {
            $json['Warnings']              = $this->warnings;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
