<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class Currencies implements \JsonSerializable
{
    /**
     * @var Currency[]|null
     */
    private $currencies;

    /**
     * Returns Currencies.
     *
     * @return Currency[]|null
     */
    public function getCurrencies(): ?array
    {
        return $this->currencies;
    }

    /**
     * Sets Currencies.
     *
     * @maps Currencies
     *
     * @param Currency[]|null $currencies
     */
    public function setCurrencies(?array $currencies): void
    {
        $this->currencies = $currencies;
    }

    /**
     * Converts the Currencies object to a human-readable string representation.
     *
     * @return string The string representation of the Currencies object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Currencies', ['currencies' => $this->currencies]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->currencies)) {
            $json['Currencies'] = $this->currencies;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
