<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * the payment terms
 */
class DueDateTypeEnum
{
    public const DAYSAFTERBILLDATE = 'DAYSAFTERBILLDATE';

    public const DAYSAFTERBILLMONTH = 'DAYSAFTERBILLMONTH';

    public const DAYSAFTERINVOICEDATE = 'DAYSAFTERINVOICEDATE';

    public const DAYSAFTERINVOICEMONTH = 'DAYSAFTERINVOICEMONTH';

    public const OFCURRENTMONTH = 'OFCURRENTMONTH';

    public const OFFOLLOWINGMONTH = 'OFFOLLOWINGMONTH';

    private const _ALL_VALUES = [
        self::DAYSAFTERBILLDATE,
        self::DAYSAFTERBILLMONTH,
        self::DAYSAFTERINVOICEDATE,
        self::DAYSAFTERINVOICEMONTH,
        self::OFCURRENTMONTH,
        self::OFFOLLOWINGMONTH
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for DueDateTypeEnum.");
    }
}
