<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class Employee implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $employeeID;

    /**
     * @var ExternalLink|null
     */
    private $externalLink;

    /**
     * @var string|null
     */
    private $firstName;

    /**
     * @var string|null
     */
    private $lastName;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $statusAttributeString;

    /**
     * @var string|null
     */
    private $updatedDateUTC;

    /**
     * @var ValidationError[]|null
     */
    private $validationErrors;

    /**
     * Returns Employee ID.
     * The Xero identifier for an employee e.g. 297c2dc5-cc47-4afd-8ec8-74990b8761e9
     */
    public function getEmployeeID(): ?string
    {
        return $this->employeeID;
    }

    /**
     * Sets Employee ID.
     * The Xero identifier for an employee e.g. 297c2dc5-cc47-4afd-8ec8-74990b8761e9
     *
     * @maps EmployeeID
     */
    public function setEmployeeID(?string $employeeID): void
    {
        $this->employeeID = $employeeID;
    }

    /**
     * Returns External Link.
     */
    public function getExternalLink(): ?ExternalLink
    {
        return $this->externalLink;
    }

    /**
     * Sets External Link.
     *
     * @maps ExternalLink
     */
    public function setExternalLink(?ExternalLink $externalLink): void
    {
        $this->externalLink = $externalLink;
    }

    /**
     * Returns First Name.
     * First name of an employee (max length = 255)
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * Sets First Name.
     * First name of an employee (max length = 255)
     *
     * @maps FirstName
     */
    public function setFirstName(?string $firstName): void
    {
        $this->firstName = $firstName;
    }

    /**
     * Returns Last Name.
     * Last name of an employee (max length = 255)
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
     * Sets Last Name.
     * Last name of an employee (max length = 255)
     *
     * @maps LastName
     */
    public function setLastName(?string $lastName): void
    {
        $this->lastName = $lastName;
    }

    /**
     * Returns Status.
     * Current status of an employee – see contact status types
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * Current status of an employee – see contact status types
     *
     * @maps Status
     * @factory \XeroAccountingAPILib\Models\Status10Enum::checkValue
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Status Attribute String.
     * A string to indicate if a invoice status
     */
    public function getStatusAttributeString(): ?string
    {
        return $this->statusAttributeString;
    }

    /**
     * Sets Status Attribute String.
     * A string to indicate if a invoice status
     *
     * @maps StatusAttributeString
     */
    public function setStatusAttributeString(?string $statusAttributeString): void
    {
        $this->statusAttributeString = $statusAttributeString;
    }

    /**
     * Returns Updated Date UTC.
     */
    public function getUpdatedDateUTC(): ?string
    {
        return $this->updatedDateUTC;
    }

    /**
     * Sets Updated Date UTC.
     *
     * @maps UpdatedDateUTC
     */
    public function setUpdatedDateUTC(?string $updatedDateUTC): void
    {
        $this->updatedDateUTC = $updatedDateUTC;
    }

    /**
     * Returns Validation Errors.
     * Displays array of validation error messages from the API
     *
     * @return ValidationError[]|null
     */
    public function getValidationErrors(): ?array
    {
        return $this->validationErrors;
    }

    /**
     * Sets Validation Errors.
     * Displays array of validation error messages from the API
     *
     * @maps ValidationErrors
     *
     * @param ValidationError[]|null $validationErrors
     */
    public function setValidationErrors(?array $validationErrors): void
    {
        $this->validationErrors = $validationErrors;
    }

    /**
     * Converts the Employee object to a human-readable string representation.
     *
     * @return string The string representation of the Employee object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Employee',
            [
                'employeeID' => $this->employeeID,
                'externalLink' => $this->externalLink,
                'firstName' => $this->firstName,
                'lastName' => $this->lastName,
                'status' => $this->status,
                'statusAttributeString' => $this->statusAttributeString,
                'updatedDateUTC' => $this->updatedDateUTC,
                'validationErrors' => $this->validationErrors
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->employeeID)) {
            $json['EmployeeID']            = $this->employeeID;
        }
        if (isset($this->externalLink)) {
            $json['ExternalLink']          = $this->externalLink;
        }
        if (isset($this->firstName)) {
            $json['FirstName']             = $this->firstName;
        }
        if (isset($this->lastName)) {
            $json['LastName']              = $this->lastName;
        }
        if (isset($this->status)) {
            $json['Status']                = Status10Enum::checkValue($this->status);
        }
        if (isset($this->statusAttributeString)) {
            $json['StatusAttributeString'] = $this->statusAttributeString;
        }
        if (isset($this->updatedDateUTC)) {
            $json['UpdatedDateUTC']        = $this->updatedDateUTC;
        }
        if (isset($this->validationErrors)) {
            $json['ValidationErrors']      = $this->validationErrors;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
