<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class ExpenseClaims implements \JsonSerializable
{
    /**
     * @var ExpenseClaim[]|null
     */
    private $expenseClaims;

    /**
     * Returns Expense Claims.
     *
     * @return ExpenseClaim[]|null
     */
    public function getExpenseClaims(): ?array
    {
        return $this->expenseClaims;
    }

    /**
     * Sets Expense Claims.
     *
     * @maps ExpenseClaims
     *
     * @param ExpenseClaim[]|null $expenseClaims
     */
    public function setExpenseClaims(?array $expenseClaims): void
    {
        $this->expenseClaims = $expenseClaims;
    }

    /**
     * Converts the ExpenseClaims object to a human-readable string representation.
     *
     * @return string The string representation of the ExpenseClaims object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('ExpenseClaims', ['expenseClaims' => $this->expenseClaims]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->expenseClaims)) {
            $json['ExpenseClaims'] = $this->expenseClaims;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
