<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class HistoryRecords implements \JsonSerializable
{
    /**
     * @var HistoryRecord[]|null
     */
    private $historyRecords;

    /**
     * Returns History Records.
     *
     * @return HistoryRecord[]|null
     */
    public function getHistoryRecords(): ?array
    {
        return $this->historyRecords;
    }

    /**
     * Sets History Records.
     *
     * @maps HistoryRecords
     *
     * @param HistoryRecord[]|null $historyRecords
     */
    public function setHistoryRecords(?array $historyRecords): void
    {
        $this->historyRecords = $historyRecords;
    }

    /**
     * Converts the HistoryRecords object to a human-readable string representation.
     *
     * @return string The string representation of the HistoryRecords object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('HistoryRecords', ['historyRecords' => $this->historyRecords]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->historyRecords)) {
            $json['HistoryRecords'] = $this->historyRecords;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
