<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

/**
 * A summary of the import from setup endpoint
 */
class ImportSummary implements \JsonSerializable
{
    /**
     * @var ImportSummaryAccounts|null
     */
    private $accounts;

    /**
     * @var ImportSummaryOrganisation|null
     */
    private $organisation;

    /**
     * Returns Accounts.
     * A summary of the accounts changes
     */
    public function getAccounts(): ?ImportSummaryAccounts
    {
        return $this->accounts;
    }

    /**
     * Sets Accounts.
     * A summary of the accounts changes
     *
     * @maps Accounts
     */
    public function setAccounts(?ImportSummaryAccounts $accounts): void
    {
        $this->accounts = $accounts;
    }

    /**
     * Returns Organisation.
     */
    public function getOrganisation(): ?ImportSummaryOrganisation
    {
        return $this->organisation;
    }

    /**
     * Sets Organisation.
     *
     * @maps Organisation
     */
    public function setOrganisation(?ImportSummaryOrganisation $organisation): void
    {
        $this->organisation = $organisation;
    }

    /**
     * Converts the ImportSummary object to a human-readable string representation.
     *
     * @return string The string representation of the ImportSummary object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ImportSummary',
            ['accounts' => $this->accounts, 'organisation' => $this->organisation]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->accounts)) {
            $json['Accounts']     = $this->accounts;
        }
        if (isset($this->organisation)) {
            $json['Organisation'] = $this->organisation;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
