<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class Item implements \JsonSerializable
{
    /**
     * @var string
     */
    private $code;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var string|null
     */
    private $inventoryAssetAccountCode;

    /**
     * @var bool|null
     */
    private $isPurchased;

    /**
     * @var bool|null
     */
    private $isSold;

    /**
     * @var bool|null
     */
    private $isTrackedAsInventory;

    /**
     * @var string|null
     */
    private $itemID;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $purchaseDescription;

    /**
     * @var Purchase|null
     */
    private $purchaseDetails;

    /**
     * @var float|null
     */
    private $quantityOnHand;

    /**
     * @var Purchase|null
     */
    private $salesDetails;

    /**
     * @var string|null
     */
    private $statusAttributeString;

    /**
     * @var float|null
     */
    private $totalCostPool;

    /**
     * @var string|null
     */
    private $updatedDateUTC;

    /**
     * @var ValidationError[]|null
     */
    private $validationErrors;

    /**
     * @param string $code
     */
    public function __construct(string $code)
    {
        $this->code = $code;
    }

    /**
     * Returns Code.
     * User defined item code (max length = 30)
     */
    public function getCode(): string
    {
        return $this->code;
    }

    /**
     * Sets Code.
     * User defined item code (max length = 30)
     *
     * @required
     * @maps Code
     */
    public function setCode(string $code): void
    {
        $this->code = $code;
    }

    /**
     * Returns Description.
     * The sales description of the item (max length = 4000)
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * The sales description of the item (max length = 4000)
     *
     * @maps Description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Inventory Asset Account Code.
     * The inventory asset account for the item. The account must be of type INVENTORY. The
     * COGSAccountCode in PurchaseDetails is also required to create a tracked item
     */
    public function getInventoryAssetAccountCode(): ?string
    {
        return $this->inventoryAssetAccountCode;
    }

    /**
     * Sets Inventory Asset Account Code.
     * The inventory asset account for the item. The account must be of type INVENTORY. The
     * COGSAccountCode in PurchaseDetails is also required to create a tracked item
     *
     * @maps InventoryAssetAccountCode
     */
    public function setInventoryAssetAccountCode(?string $inventoryAssetAccountCode): void
    {
        $this->inventoryAssetAccountCode = $inventoryAssetAccountCode;
    }

    /**
     * Returns Is Purchased.
     * Boolean value, defaults to true. When IsPurchased is true the item is available for purchase
     * transactions in the Xero UI. If IsPurchased is updated to false then PurchaseDescription and
     * PurchaseDetails values will be nulled.
     */
    public function getIsPurchased(): ?bool
    {
        return $this->isPurchased;
    }

    /**
     * Sets Is Purchased.
     * Boolean value, defaults to true. When IsPurchased is true the item is available for purchase
     * transactions in the Xero UI. If IsPurchased is updated to false then PurchaseDescription and
     * PurchaseDetails values will be nulled.
     *
     * @maps IsPurchased
     */
    public function setIsPurchased(?bool $isPurchased): void
    {
        $this->isPurchased = $isPurchased;
    }

    /**
     * Returns Is Sold.
     * Boolean value, defaults to true. When IsSold is true the item will be available on sales
     * transactions in the Xero UI. If IsSold is updated to false then Description and SalesDetails values
     * will be nulled.
     */
    public function getIsSold(): ?bool
    {
        return $this->isSold;
    }

    /**
     * Sets Is Sold.
     * Boolean value, defaults to true. When IsSold is true the item will be available on sales
     * transactions in the Xero UI. If IsSold is updated to false then Description and SalesDetails values
     * will be nulled.
     *
     * @maps IsSold
     */
    public function setIsSold(?bool $isSold): void
    {
        $this->isSold = $isSold;
    }

    /**
     * Returns Is Tracked as Inventory.
     * True for items that are tracked as inventory. An item will be tracked as inventory if the
     * InventoryAssetAccountCode and COGSAccountCode are set.
     */
    public function getIsTrackedAsInventory(): ?bool
    {
        return $this->isTrackedAsInventory;
    }

    /**
     * Sets Is Tracked as Inventory.
     * True for items that are tracked as inventory. An item will be tracked as inventory if the
     * InventoryAssetAccountCode and COGSAccountCode are set.
     *
     * @maps IsTrackedAsInventory
     */
    public function setIsTrackedAsInventory(?bool $isTrackedAsInventory): void
    {
        $this->isTrackedAsInventory = $isTrackedAsInventory;
    }

    /**
     * Returns Item ID.
     * The Xero identifier for an Item
     */
    public function getItemID(): ?string
    {
        return $this->itemID;
    }

    /**
     * Sets Item ID.
     * The Xero identifier for an Item
     *
     * @maps ItemID
     */
    public function setItemID(?string $itemID): void
    {
        $this->itemID = $itemID;
    }

    /**
     * Returns Name.
     * The name of the item (max length = 50)
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The name of the item (max length = 50)
     *
     * @maps Name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Purchase Description.
     * The purchase description of the item (max length = 4000)
     */
    public function getPurchaseDescription(): ?string
    {
        return $this->purchaseDescription;
    }

    /**
     * Sets Purchase Description.
     * The purchase description of the item (max length = 4000)
     *
     * @maps PurchaseDescription
     */
    public function setPurchaseDescription(?string $purchaseDescription): void
    {
        $this->purchaseDescription = $purchaseDescription;
    }

    /**
     * Returns Purchase Details.
     */
    public function getPurchaseDetails(): ?Purchase
    {
        return $this->purchaseDetails;
    }

    /**
     * Sets Purchase Details.
     *
     * @maps PurchaseDetails
     */
    public function setPurchaseDetails(?Purchase $purchaseDetails): void
    {
        $this->purchaseDetails = $purchaseDetails;
    }

    /**
     * Returns Quantity on Hand.
     * The quantity of the item on hand
     */
    public function getQuantityOnHand(): ?float
    {
        return $this->quantityOnHand;
    }

    /**
     * Sets Quantity on Hand.
     * The quantity of the item on hand
     *
     * @maps QuantityOnHand
     */
    public function setQuantityOnHand(?float $quantityOnHand): void
    {
        $this->quantityOnHand = $quantityOnHand;
    }

    /**
     * Returns Sales Details.
     */
    public function getSalesDetails(): ?Purchase
    {
        return $this->salesDetails;
    }

    /**
     * Sets Sales Details.
     *
     * @maps SalesDetails
     */
    public function setSalesDetails(?Purchase $salesDetails): void
    {
        $this->salesDetails = $salesDetails;
    }

    /**
     * Returns Status Attribute String.
     * Status of object
     */
    public function getStatusAttributeString(): ?string
    {
        return $this->statusAttributeString;
    }

    /**
     * Sets Status Attribute String.
     * Status of object
     *
     * @maps StatusAttributeString
     */
    public function setStatusAttributeString(?string $statusAttributeString): void
    {
        $this->statusAttributeString = $statusAttributeString;
    }

    /**
     * Returns Total Cost Pool.
     * The value of the item on hand. Calculated using average cost accounting.
     */
    public function getTotalCostPool(): ?float
    {
        return $this->totalCostPool;
    }

    /**
     * Sets Total Cost Pool.
     * The value of the item on hand. Calculated using average cost accounting.
     *
     * @maps TotalCostPool
     */
    public function setTotalCostPool(?float $totalCostPool): void
    {
        $this->totalCostPool = $totalCostPool;
    }

    /**
     * Returns Updated Date UTC.
     * Last modified date in UTC format
     */
    public function getUpdatedDateUTC(): ?string
    {
        return $this->updatedDateUTC;
    }

    /**
     * Sets Updated Date UTC.
     * Last modified date in UTC format
     *
     * @maps UpdatedDateUTC
     */
    public function setUpdatedDateUTC(?string $updatedDateUTC): void
    {
        $this->updatedDateUTC = $updatedDateUTC;
    }

    /**
     * Returns Validation Errors.
     * Displays array of validation error messages from the API
     *
     * @return ValidationError[]|null
     */
    public function getValidationErrors(): ?array
    {
        return $this->validationErrors;
    }

    /**
     * Sets Validation Errors.
     * Displays array of validation error messages from the API
     *
     * @maps ValidationErrors
     *
     * @param ValidationError[]|null $validationErrors
     */
    public function setValidationErrors(?array $validationErrors): void
    {
        $this->validationErrors = $validationErrors;
    }

    /**
     * Converts the Item object to a human-readable string representation.
     *
     * @return string The string representation of the Item object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Item',
            [
                'code' => $this->code,
                'description' => $this->description,
                'inventoryAssetAccountCode' => $this->inventoryAssetAccountCode,
                'isPurchased' => $this->isPurchased,
                'isSold' => $this->isSold,
                'isTrackedAsInventory' => $this->isTrackedAsInventory,
                'itemID' => $this->itemID,
                'name' => $this->name,
                'purchaseDescription' => $this->purchaseDescription,
                'purchaseDetails' => $this->purchaseDetails,
                'quantityOnHand' => $this->quantityOnHand,
                'salesDetails' => $this->salesDetails,
                'statusAttributeString' => $this->statusAttributeString,
                'totalCostPool' => $this->totalCostPool,
                'updatedDateUTC' => $this->updatedDateUTC,
                'validationErrors' => $this->validationErrors
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['Code']                          = $this->code;
        if (isset($this->description)) {
            $json['Description']               = $this->description;
        }
        if (isset($this->inventoryAssetAccountCode)) {
            $json['InventoryAssetAccountCode'] = $this->inventoryAssetAccountCode;
        }
        if (isset($this->isPurchased)) {
            $json['IsPurchased']               = $this->isPurchased;
        }
        if (isset($this->isSold)) {
            $json['IsSold']                    = $this->isSold;
        }
        if (isset($this->isTrackedAsInventory)) {
            $json['IsTrackedAsInventory']      = $this->isTrackedAsInventory;
        }
        if (isset($this->itemID)) {
            $json['ItemID']                    = $this->itemID;
        }
        if (isset($this->name)) {
            $json['Name']                      = $this->name;
        }
        if (isset($this->purchaseDescription)) {
            $json['PurchaseDescription']       = $this->purchaseDescription;
        }
        if (isset($this->purchaseDetails)) {
            $json['PurchaseDetails']           = $this->purchaseDetails;
        }
        if (isset($this->quantityOnHand)) {
            $json['QuantityOnHand']            = $this->quantityOnHand;
        }
        if (isset($this->salesDetails)) {
            $json['SalesDetails']              = $this->salesDetails;
        }
        if (isset($this->statusAttributeString)) {
            $json['StatusAttributeString']     = $this->statusAttributeString;
        }
        if (isset($this->totalCostPool)) {
            $json['TotalCostPool']             = $this->totalCostPool;
        }
        if (isset($this->updatedDateUTC)) {
            $json['UpdatedDateUTC']            = $this->updatedDateUTC;
        }
        if (isset($this->validationErrors)) {
            $json['ValidationErrors']          = $this->validationErrors;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
