<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class Journals implements \JsonSerializable
{
    /**
     * @var Journal[]|null
     */
    private $journals;

    /**
     * Returns Journals.
     *
     * @return Journal[]|null
     */
    public function getJournals(): ?array
    {
        return $this->journals;
    }

    /**
     * Sets Journals.
     *
     * @maps Journals
     *
     * @param Journal[]|null $journals
     */
    public function setJournals(?array $journals): void
    {
        $this->journals = $journals;
    }

    /**
     * Converts the Journals object to a human-readable string representation.
     *
     * @return string The string representation of the Journals object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Journals', ['journals' => $this->journals]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->journals)) {
            $json['Journals'] = $this->journals;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
