<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class Journal implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $createdDateUTC;

    /**
     * @var string|null
     */
    private $journalDate;

    /**
     * @var string|null
     */
    private $journalID;

    /**
     * @var JournalLine[]|null
     */
    private $journalLines;

    /**
     * @var int|null
     */
    private $journalNumber;

    /**
     * @var string|null
     */
    private $reference;

    /**
     * @var string|null
     */
    private $sourceID;

    /**
     * @var string|null
     */
    private $sourceType;

    /**
     * Returns Created Date UTC.
     * Created date UTC format
     */
    public function getCreatedDateUTC(): ?string
    {
        return $this->createdDateUTC;
    }

    /**
     * Sets Created Date UTC.
     * Created date UTC format
     *
     * @maps CreatedDateUTC
     */
    public function setCreatedDateUTC(?string $createdDateUTC): void
    {
        $this->createdDateUTC = $createdDateUTC;
    }

    /**
     * Returns Journal Date.
     * Date the journal was posted
     */
    public function getJournalDate(): ?string
    {
        return $this->journalDate;
    }

    /**
     * Sets Journal Date.
     * Date the journal was posted
     *
     * @maps JournalDate
     */
    public function setJournalDate(?string $journalDate): void
    {
        $this->journalDate = $journalDate;
    }

    /**
     * Returns Journal ID.
     * Xero identifier
     */
    public function getJournalID(): ?string
    {
        return $this->journalID;
    }

    /**
     * Sets Journal ID.
     * Xero identifier
     *
     * @maps JournalID
     */
    public function setJournalID(?string $journalID): void
    {
        $this->journalID = $journalID;
    }

    /**
     * Returns Journal Lines.
     * See JournalLines
     *
     * @return JournalLine[]|null
     */
    public function getJournalLines(): ?array
    {
        return $this->journalLines;
    }

    /**
     * Sets Journal Lines.
     * See JournalLines
     *
     * @maps JournalLines
     *
     * @param JournalLine[]|null $journalLines
     */
    public function setJournalLines(?array $journalLines): void
    {
        $this->journalLines = $journalLines;
    }

    /**
     * Returns Journal Number.
     * Xero generated journal number
     */
    public function getJournalNumber(): ?int
    {
        return $this->journalNumber;
    }

    /**
     * Sets Journal Number.
     * Xero generated journal number
     *
     * @maps JournalNumber
     */
    public function setJournalNumber(?int $journalNumber): void
    {
        $this->journalNumber = $journalNumber;
    }

    /**
     * Returns Reference.
     * reference field for additional indetifying information
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     * reference field for additional indetifying information
     *
     * @maps Reference
     */
    public function setReference(?string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Returns Source ID.
     * The identifier for the source transaction (e.g. InvoiceID)
     */
    public function getSourceID(): ?string
    {
        return $this->sourceID;
    }

    /**
     * Sets Source ID.
     * The identifier for the source transaction (e.g. InvoiceID)
     *
     * @maps SourceID
     */
    public function setSourceID(?string $sourceID): void
    {
        $this->sourceID = $sourceID;
    }

    /**
     * Returns Source Type.
     * The journal source type. The type of transaction that created the journal
     */
    public function getSourceType(): ?string
    {
        return $this->sourceType;
    }

    /**
     * Sets Source Type.
     * The journal source type. The type of transaction that created the journal
     *
     * @maps SourceType
     * @factory \XeroAccountingAPILib\Models\SourceTypeEnum::checkValue
     */
    public function setSourceType(?string $sourceType): void
    {
        $this->sourceType = $sourceType;
    }

    /**
     * Converts the Journal object to a human-readable string representation.
     *
     * @return string The string representation of the Journal object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Journal',
            [
                'createdDateUTC' => $this->createdDateUTC,
                'journalDate' => $this->journalDate,
                'journalID' => $this->journalID,
                'journalLines' => $this->journalLines,
                'journalNumber' => $this->journalNumber,
                'reference' => $this->reference,
                'sourceID' => $this->sourceID,
                'sourceType' => $this->sourceType
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->createdDateUTC)) {
            $json['CreatedDateUTC'] = $this->createdDateUTC;
        }
        if (isset($this->journalDate)) {
            $json['JournalDate']    = $this->journalDate;
        }
        if (isset($this->journalID)) {
            $json['JournalID']      = $this->journalID;
        }
        if (isset($this->journalLines)) {
            $json['JournalLines']   = $this->journalLines;
        }
        if (isset($this->journalNumber)) {
            $json['JournalNumber']  = $this->journalNumber;
        }
        if (isset($this->reference)) {
            $json['Reference']      = $this->reference;
        }
        if (isset($this->sourceID)) {
            $json['SourceID']       = $this->sourceID;
        }
        if (isset($this->sourceType)) {
            $json['SourceType']     = SourceTypeEnum::checkValue($this->sourceType);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
