<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class LineItem implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $accountCode;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var float|null
     */
    private $discountAmount;

    /**
     * @var float|null
     */
    private $discountRate;

    /**
     * @var string|null
     */
    private $itemCode;

    /**
     * @var float|null
     */
    private $lineAmount;

    /**
     * @var string|null
     */
    private $lineItemID;

    /**
     * @var float|null
     */
    private $quantity;

    /**
     * @var string|null
     */
    private $repeatingInvoiceID;

    /**
     * @var float|null
     */
    private $taxAmount;

    /**
     * @var string|null
     */
    private $taxType;

    /**
     * @var LineItemTracking[]|null
     */
    private $tracking;

    /**
     * @var float|null
     */
    private $unitAmount;

    /**
     * Returns Account Code.
     * See Accounts
     */
    public function getAccountCode(): ?string
    {
        return $this->accountCode;
    }

    /**
     * Sets Account Code.
     * See Accounts
     *
     * @maps AccountCode
     */
    public function setAccountCode(?string $accountCode): void
    {
        $this->accountCode = $accountCode;
    }

    /**
     * Returns Description.
     * Description needs to be at least 1 char long. A line item with just a description (i.e no unit
     * amount or quantity) can be created by specifying just a <Description> element that contains at least
     * 1 character
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * Description needs to be at least 1 char long. A line item with just a description (i.e no unit
     * amount or quantity) can be created by specifying just a <Description> element that contains at least
     * 1 character
     *
     * @maps Description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Discount Amount.
     * Discount amount being applied to a line item. Only supported on ACCREC invoices - ACCPAY invoices
     * and credit notes in Xero do not support discounts.
     */
    public function getDiscountAmount(): ?float
    {
        return $this->discountAmount;
    }

    /**
     * Sets Discount Amount.
     * Discount amount being applied to a line item. Only supported on ACCREC invoices - ACCPAY invoices
     * and credit notes in Xero do not support discounts.
     *
     * @maps DiscountAmount
     */
    public function setDiscountAmount(?float $discountAmount): void
    {
        $this->discountAmount = $discountAmount;
    }

    /**
     * Returns Discount Rate.
     * Percentage discount being applied to a line item (only supported on  ACCREC invoices – ACC PAY
     * invoices and credit notes in Xero do not support discounts
     */
    public function getDiscountRate(): ?float
    {
        return $this->discountRate;
    }

    /**
     * Sets Discount Rate.
     * Percentage discount being applied to a line item (only supported on  ACCREC invoices – ACC PAY
     * invoices and credit notes in Xero do not support discounts
     *
     * @maps DiscountRate
     */
    public function setDiscountRate(?float $discountRate): void
    {
        $this->discountRate = $discountRate;
    }

    /**
     * Returns Item Code.
     * See Items
     */
    public function getItemCode(): ?string
    {
        return $this->itemCode;
    }

    /**
     * Sets Item Code.
     * See Items
     *
     * @maps ItemCode
     */
    public function setItemCode(?string $itemCode): void
    {
        $this->itemCode = $itemCode;
    }

    /**
     * Returns Line Amount.
     * If you wish to omit either of the <Quantity> or <UnitAmount> you can provide a LineAmount and Xero
     * will calculate the missing amount for you. The line amount reflects the discounted price if a
     * DiscountRate has been used . i.e LineAmount = Quantity * Unit Amount * ((100 – DiscountRate)/100)
     */
    public function getLineAmount(): ?float
    {
        return $this->lineAmount;
    }

    /**
     * Sets Line Amount.
     * If you wish to omit either of the <Quantity> or <UnitAmount> you can provide a LineAmount and Xero
     * will calculate the missing amount for you. The line amount reflects the discounted price if a
     * DiscountRate has been used . i.e LineAmount = Quantity * Unit Amount * ((100 – DiscountRate)/100)
     *
     * @maps LineAmount
     */
    public function setLineAmount(?float $lineAmount): void
    {
        $this->lineAmount = $lineAmount;
    }

    /**
     * Returns Line Item ID.
     * LineItem unique ID
     */
    public function getLineItemID(): ?string
    {
        return $this->lineItemID;
    }

    /**
     * Sets Line Item ID.
     * LineItem unique ID
     *
     * @maps LineItemID
     */
    public function setLineItemID(?string $lineItemID): void
    {
        $this->lineItemID = $lineItemID;
    }

    /**
     * Returns Quantity.
     * LineItem Quantity
     */
    public function getQuantity(): ?float
    {
        return $this->quantity;
    }

    /**
     * Sets Quantity.
     * LineItem Quantity
     *
     * @maps Quantity
     */
    public function setQuantity(?float $quantity): void
    {
        $this->quantity = $quantity;
    }

    /**
     * Returns Repeating Invoice ID.
     * The Xero identifier for a Repeating Invoice
     */
    public function getRepeatingInvoiceID(): ?string
    {
        return $this->repeatingInvoiceID;
    }

    /**
     * Sets Repeating Invoice ID.
     * The Xero identifier for a Repeating Invoice
     *
     * @maps RepeatingInvoiceID
     */
    public function setRepeatingInvoiceID(?string $repeatingInvoiceID): void
    {
        $this->repeatingInvoiceID = $repeatingInvoiceID;
    }

    /**
     * Returns Tax Amount.
     * The tax amount is auto calculated as a percentage of the line amount (see below) based on the tax
     * rate. This value can be overriden if the calculated <TaxAmount> is not correct.
     */
    public function getTaxAmount(): ?float
    {
        return $this->taxAmount;
    }

    /**
     * Sets Tax Amount.
     * The tax amount is auto calculated as a percentage of the line amount (see below) based on the tax
     * rate. This value can be overriden if the calculated <TaxAmount> is not correct.
     *
     * @maps TaxAmount
     */
    public function setTaxAmount(?float $taxAmount): void
    {
        $this->taxAmount = $taxAmount;
    }

    /**
     * Returns Tax Type.
     * The tax type from TaxRates
     */
    public function getTaxType(): ?string
    {
        return $this->taxType;
    }

    /**
     * Sets Tax Type.
     * The tax type from TaxRates
     *
     * @maps TaxType
     */
    public function setTaxType(?string $taxType): void
    {
        $this->taxType = $taxType;
    }

    /**
     * Returns Tracking.
     * Optional Tracking Category – see Tracking.  Any LineItem can have a  maximum of 2 <TrackingCategory>
     * elements.
     *
     * @return LineItemTracking[]|null
     */
    public function getTracking(): ?array
    {
        return $this->tracking;
    }

    /**
     * Sets Tracking.
     * Optional Tracking Category – see Tracking.  Any LineItem can have a  maximum of 2 <TrackingCategory>
     * elements.
     *
     * @maps Tracking
     *
     * @param LineItemTracking[]|null $tracking
     */
    public function setTracking(?array $tracking): void
    {
        $this->tracking = $tracking;
    }

    /**
     * Returns Unit Amount.
     * LineItem Unit Amount
     */
    public function getUnitAmount(): ?float
    {
        return $this->unitAmount;
    }

    /**
     * Sets Unit Amount.
     * LineItem Unit Amount
     *
     * @maps UnitAmount
     */
    public function setUnitAmount(?float $unitAmount): void
    {
        $this->unitAmount = $unitAmount;
    }

    /**
     * Converts the LineItem object to a human-readable string representation.
     *
     * @return string The string representation of the LineItem object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'LineItem',
            [
                'accountCode' => $this->accountCode,
                'description' => $this->description,
                'discountAmount' => $this->discountAmount,
                'discountRate' => $this->discountRate,
                'itemCode' => $this->itemCode,
                'lineAmount' => $this->lineAmount,
                'lineItemID' => $this->lineItemID,
                'quantity' => $this->quantity,
                'repeatingInvoiceID' => $this->repeatingInvoiceID,
                'taxAmount' => $this->taxAmount,
                'taxType' => $this->taxType,
                'tracking' => $this->tracking,
                'unitAmount' => $this->unitAmount
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->accountCode)) {
            $json['AccountCode']        = $this->accountCode;
        }
        if (isset($this->description)) {
            $json['Description']        = $this->description;
        }
        if (isset($this->discountAmount)) {
            $json['DiscountAmount']     = $this->discountAmount;
        }
        if (isset($this->discountRate)) {
            $json['DiscountRate']       = $this->discountRate;
        }
        if (isset($this->itemCode)) {
            $json['ItemCode']           = $this->itemCode;
        }
        if (isset($this->lineAmount)) {
            $json['LineAmount']         = $this->lineAmount;
        }
        if (isset($this->lineItemID)) {
            $json['LineItemID']         = $this->lineItemID;
        }
        if (isset($this->quantity)) {
            $json['Quantity']           = $this->quantity;
        }
        if (isset($this->repeatingInvoiceID)) {
            $json['RepeatingInvoiceID'] = $this->repeatingInvoiceID;
        }
        if (isset($this->taxAmount)) {
            $json['TaxAmount']          = $this->taxAmount;
        }
        if (isset($this->taxType)) {
            $json['TaxType']            = $this->taxType;
        }
        if (isset($this->tracking)) {
            $json['Tracking']           = $this->tracking;
        }
        if (isset($this->unitAmount)) {
            $json['UnitAmount']         = $this->unitAmount;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
