<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class LineItemTracking implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $option;

    /**
     * @var string|null
     */
    private $trackingCategoryID;

    /**
     * @var string|null
     */
    private $trackingOptionID;

    /**
     * Returns Name.
     * The name of the tracking category
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The name of the tracking category
     *
     * @maps Name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Option.
     * See Tracking Options
     */
    public function getOption(): ?string
    {
        return $this->option;
    }

    /**
     * Sets Option.
     * See Tracking Options
     *
     * @maps Option
     */
    public function setOption(?string $option): void
    {
        $this->option = $option;
    }

    /**
     * Returns Tracking Category ID.
     * The Xero identifier for a tracking category
     */
    public function getTrackingCategoryID(): ?string
    {
        return $this->trackingCategoryID;
    }

    /**
     * Sets Tracking Category ID.
     * The Xero identifier for a tracking category
     *
     * @maps TrackingCategoryID
     */
    public function setTrackingCategoryID(?string $trackingCategoryID): void
    {
        $this->trackingCategoryID = $trackingCategoryID;
    }

    /**
     * Returns Tracking Option ID.
     * The Xero identifier for a tracking category option
     */
    public function getTrackingOptionID(): ?string
    {
        return $this->trackingOptionID;
    }

    /**
     * Sets Tracking Option ID.
     * The Xero identifier for a tracking category option
     *
     * @maps TrackingOptionID
     */
    public function setTrackingOptionID(?string $trackingOptionID): void
    {
        $this->trackingOptionID = $trackingOptionID;
    }

    /**
     * Converts the LineItemTracking object to a human-readable string representation.
     *
     * @return string The string representation of the LineItemTracking object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'LineItemTracking',
            [
                'name' => $this->name,
                'option' => $this->option,
                'trackingCategoryID' => $this->trackingCategoryID,
                'trackingOptionID' => $this->trackingOptionID
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->name)) {
            $json['Name']               = $this->name;
        }
        if (isset($this->option)) {
            $json['Option']             = $this->option;
        }
        if (isset($this->trackingCategoryID)) {
            $json['TrackingCategoryID'] = $this->trackingCategoryID;
        }
        if (isset($this->trackingOptionID)) {
            $json['TrackingOptionID']   = $this->trackingOptionID;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
