<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class LinkedTransaction implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $contactID;

    /**
     * @var string|null
     */
    private $linkedTransactionID;

    /**
     * @var string|null
     */
    private $sourceLineItemID;

    /**
     * @var string|null
     */
    private $sourceTransactionID;

    /**
     * @var string|null
     */
    private $sourceTransactionTypeCode;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $targetLineItemID;

    /**
     * @var string|null
     */
    private $targetTransactionID;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var string|null
     */
    private $updatedDateUTC;

    /**
     * @var ValidationError[]|null
     */
    private $validationErrors;

    /**
     * Returns Contact ID.
     * Filter by the combination of ContactID and Status. Get all the linked transactions that have been
     * assigned to a particular customer and have a particular status e.g. GET /LinkedTransactions?
     * ContactID=4bb34b03-3378-4bb2-a0ed-6345abf3224e&Status=APPROVED.
     */
    public function getContactID(): ?string
    {
        return $this->contactID;
    }

    /**
     * Sets Contact ID.
     * Filter by the combination of ContactID and Status. Get all the linked transactions that have been
     * assigned to a particular customer and have a particular status e.g. GET /LinkedTransactions?
     * ContactID=4bb34b03-3378-4bb2-a0ed-6345abf3224e&Status=APPROVED.
     *
     * @maps ContactID
     */
    public function setContactID(?string $contactID): void
    {
        $this->contactID = $contactID;
    }

    /**
     * Returns Linked Transaction ID.
     * The Xero identifier for an Linked Transaction e.g./LinkedTransactions/297c2dc5-cc47-4afd-8ec8-
     * 74990b8761e9
     */
    public function getLinkedTransactionID(): ?string
    {
        return $this->linkedTransactionID;
    }

    /**
     * Sets Linked Transaction ID.
     * The Xero identifier for an Linked Transaction e.g./LinkedTransactions/297c2dc5-cc47-4afd-8ec8-
     * 74990b8761e9
     *
     * @maps LinkedTransactionID
     */
    public function setLinkedTransactionID(?string $linkedTransactionID): void
    {
        $this->linkedTransactionID = $linkedTransactionID;
    }

    /**
     * Returns Source Line Item ID.
     * The line item identifier from the source transaction.
     */
    public function getSourceLineItemID(): ?string
    {
        return $this->sourceLineItemID;
    }

    /**
     * Sets Source Line Item ID.
     * The line item identifier from the source transaction.
     *
     * @maps SourceLineItemID
     */
    public function setSourceLineItemID(?string $sourceLineItemID): void
    {
        $this->sourceLineItemID = $sourceLineItemID;
    }

    /**
     * Returns Source Transaction ID.
     * Filter by the SourceTransactionID. Get all the linked transactions created from a particular ACCPAY
     * invoice
     */
    public function getSourceTransactionID(): ?string
    {
        return $this->sourceTransactionID;
    }

    /**
     * Sets Source Transaction ID.
     * Filter by the SourceTransactionID. Get all the linked transactions created from a particular ACCPAY
     * invoice
     *
     * @maps SourceTransactionID
     */
    public function setSourceTransactionID(?string $sourceTransactionID): void
    {
        $this->sourceTransactionID = $sourceTransactionID;
    }

    /**
     * Returns Source Transaction Type Code.
     * The Type of the source tranasction. This will be ACCPAY if the linked transaction was created from
     * an invoice and SPEND if it was created from a bank transaction.
     */
    public function getSourceTransactionTypeCode(): ?string
    {
        return $this->sourceTransactionTypeCode;
    }

    /**
     * Sets Source Transaction Type Code.
     * The Type of the source tranasction. This will be ACCPAY if the linked transaction was created from
     * an invoice and SPEND if it was created from a bank transaction.
     *
     * @maps SourceTransactionTypeCode
     * @factory \XeroAccountingAPILib\Models\SourceTransactionTypeCodeEnum::checkValue
     */
    public function setSourceTransactionTypeCode(?string $sourceTransactionTypeCode): void
    {
        $this->sourceTransactionTypeCode = $sourceTransactionTypeCode;
    }

    /**
     * Returns Status.
     * Filter by the combination of ContactID and Status. Get all the linked transactions that have been
     * assigned to a particular customer and have a particular status e.g. GET /LinkedTransactions?
     * ContactID=4bb34b03-3378-4bb2-a0ed-6345abf3224e&Status=APPROVED.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * Filter by the combination of ContactID and Status. Get all the linked transactions that have been
     * assigned to a particular customer and have a particular status e.g. GET /LinkedTransactions?
     * ContactID=4bb34b03-3378-4bb2-a0ed-6345abf3224e&Status=APPROVED.
     *
     * @maps Status
     * @factory \XeroAccountingAPILib\Models\Status15Enum::checkValue
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Target Line Item ID.
     * The line item identifier from the target transaction. It is possible  to link multiple billable
     * expenses to the same TargetLineItemID.
     */
    public function getTargetLineItemID(): ?string
    {
        return $this->targetLineItemID;
    }

    /**
     * Sets Target Line Item ID.
     * The line item identifier from the target transaction. It is possible  to link multiple billable
     * expenses to the same TargetLineItemID.
     *
     * @maps TargetLineItemID
     */
    public function setTargetLineItemID(?string $targetLineItemID): void
    {
        $this->targetLineItemID = $targetLineItemID;
    }

    /**
     * Returns Target Transaction ID.
     * Filter by the TargetTransactionID. Get all the linked transactions  allocated to a particular ACCREC
     * invoice
     */
    public function getTargetTransactionID(): ?string
    {
        return $this->targetTransactionID;
    }

    /**
     * Sets Target Transaction ID.
     * Filter by the TargetTransactionID. Get all the linked transactions  allocated to a particular ACCREC
     * invoice
     *
     * @maps TargetTransactionID
     */
    public function setTargetTransactionID(?string $targetTransactionID): void
    {
        $this->targetTransactionID = $targetTransactionID;
    }

    /**
     * Returns Type.
     * This will always be BILLABLEEXPENSE. More types may be added in future.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * This will always be BILLABLEEXPENSE. More types may be added in future.
     *
     * @maps Type
     * @factory \XeroAccountingAPILib\Models\Type7Enum::checkValue
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Updated Date UTC.
     * The last modified date in UTC format
     */
    public function getUpdatedDateUTC(): ?string
    {
        return $this->updatedDateUTC;
    }

    /**
     * Sets Updated Date UTC.
     * The last modified date in UTC format
     *
     * @maps UpdatedDateUTC
     */
    public function setUpdatedDateUTC(?string $updatedDateUTC): void
    {
        $this->updatedDateUTC = $updatedDateUTC;
    }

    /**
     * Returns Validation Errors.
     * Displays array of validation error messages from the API
     *
     * @return ValidationError[]|null
     */
    public function getValidationErrors(): ?array
    {
        return $this->validationErrors;
    }

    /**
     * Sets Validation Errors.
     * Displays array of validation error messages from the API
     *
     * @maps ValidationErrors
     *
     * @param ValidationError[]|null $validationErrors
     */
    public function setValidationErrors(?array $validationErrors): void
    {
        $this->validationErrors = $validationErrors;
    }

    /**
     * Converts the LinkedTransaction object to a human-readable string representation.
     *
     * @return string The string representation of the LinkedTransaction object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'LinkedTransaction',
            [
                'contactID' => $this->contactID,
                'linkedTransactionID' => $this->linkedTransactionID,
                'sourceLineItemID' => $this->sourceLineItemID,
                'sourceTransactionID' => $this->sourceTransactionID,
                'sourceTransactionTypeCode' => $this->sourceTransactionTypeCode,
                'status' => $this->status,
                'targetLineItemID' => $this->targetLineItemID,
                'targetTransactionID' => $this->targetTransactionID,
                'type' => $this->type,
                'updatedDateUTC' => $this->updatedDateUTC,
                'validationErrors' => $this->validationErrors
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->contactID)) {
            $json['ContactID']                 = $this->contactID;
        }
        if (isset($this->linkedTransactionID)) {
            $json['LinkedTransactionID']       = $this->linkedTransactionID;
        }
        if (isset($this->sourceLineItemID)) {
            $json['SourceLineItemID']          = $this->sourceLineItemID;
        }
        if (isset($this->sourceTransactionID)) {
            $json['SourceTransactionID']       = $this->sourceTransactionID;
        }
        if (isset($this->sourceTransactionTypeCode)) {
            $json['SourceTransactionTypeCode'] =
                SourceTransactionTypeCodeEnum::checkValue(
                    $this->sourceTransactionTypeCode
                );
        }
        if (isset($this->status)) {
            $json['Status']                    = Status15Enum::checkValue($this->status);
        }
        if (isset($this->targetLineItemID)) {
            $json['TargetLineItemID']          = $this->targetLineItemID;
        }
        if (isset($this->targetTransactionID)) {
            $json['TargetTransactionID']       = $this->targetTransactionID;
        }
        if (isset($this->type)) {
            $json['Type']                      = Type7Enum::checkValue($this->type);
        }
        if (isset($this->updatedDateUTC)) {
            $json['UpdatedDateUTC']            = $this->updatedDateUTC;
        }
        if (isset($this->validationErrors)) {
            $json['ValidationErrors']          = $this->validationErrors;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
