<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class LinkedTransactions implements \JsonSerializable
{
    /**
     * @var LinkedTransaction[]|null
     */
    private $linkedTransactions;

    /**
     * Returns Linked Transactions.
     *
     * @return LinkedTransaction[]|null
     */
    public function getLinkedTransactions(): ?array
    {
        return $this->linkedTransactions;
    }

    /**
     * Sets Linked Transactions.
     *
     * @maps LinkedTransactions
     *
     * @param LinkedTransaction[]|null $linkedTransactions
     */
    public function setLinkedTransactions(?array $linkedTransactions): void
    {
        $this->linkedTransactions = $linkedTransactions;
    }

    /**
     * Converts the LinkedTransactions object to a human-readable string representation.
     *
     * @return string The string representation of the LinkedTransactions object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('LinkedTransactions', ['linkedTransactions' => $this->linkedTransactions]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->linkedTransactions)) {
            $json['LinkedTransactions'] = $this->linkedTransactions;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
