<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class ManualJournalLine implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $accountCode;

    /**
     * @var string|null
     */
    private $accountID;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var bool|null
     */
    private $isBlank;

    /**
     * @var float|null
     */
    private $lineAmount;

    /**
     * @var float|null
     */
    private $taxAmount;

    /**
     * @var string|null
     */
    private $taxType;

    /**
     * @var TrackingCategory[]|null
     */
    private $tracking;

    /**
     * Returns Account Code.
     * See Accounts
     */
    public function getAccountCode(): ?string
    {
        return $this->accountCode;
    }

    /**
     * Sets Account Code.
     * See Accounts
     *
     * @maps AccountCode
     */
    public function setAccountCode(?string $accountCode): void
    {
        $this->accountCode = $accountCode;
    }

    /**
     * Returns Account ID.
     * See Accounts
     */
    public function getAccountID(): ?string
    {
        return $this->accountID;
    }

    /**
     * Sets Account ID.
     * See Accounts
     *
     * @maps AccountID
     */
    public function setAccountID(?string $accountID): void
    {
        $this->accountID = $accountID;
    }

    /**
     * Returns Description.
     * Description for journal line
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * Description for journal line
     *
     * @maps Description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Is Blank.
     * is the line blank
     */
    public function getIsBlank(): ?bool
    {
        return $this->isBlank;
    }

    /**
     * Sets Is Blank.
     * is the line blank
     *
     * @maps IsBlank
     */
    public function setIsBlank(?bool $isBlank): void
    {
        $this->isBlank = $isBlank;
    }

    /**
     * Returns Line Amount.
     * total for line. Debits are positive, credits are negative value
     */
    public function getLineAmount(): ?float
    {
        return $this->lineAmount;
    }

    /**
     * Sets Line Amount.
     * total for line. Debits are positive, credits are negative value
     *
     * @maps LineAmount
     */
    public function setLineAmount(?float $lineAmount): void
    {
        $this->lineAmount = $lineAmount;
    }

    /**
     * Returns Tax Amount.
     * The calculated tax amount based on the TaxType and LineAmount
     */
    public function getTaxAmount(): ?float
    {
        return $this->taxAmount;
    }

    /**
     * Sets Tax Amount.
     * The calculated tax amount based on the TaxType and LineAmount
     *
     * @maps TaxAmount
     */
    public function setTaxAmount(?float $taxAmount): void
    {
        $this->taxAmount = $taxAmount;
    }

    /**
     * Returns Tax Type.
     * The tax type from TaxRates
     */
    public function getTaxType(): ?string
    {
        return $this->taxType;
    }

    /**
     * Sets Tax Type.
     * The tax type from TaxRates
     *
     * @maps TaxType
     */
    public function setTaxType(?string $taxType): void
    {
        $this->taxType = $taxType;
    }

    /**
     * Returns Tracking.
     * Optional Tracking Category – see Tracking. Any JournalLine can have a maximum of 2
     * <TrackingCategory> elements.
     *
     * @return TrackingCategory[]|null
     */
    public function getTracking(): ?array
    {
        return $this->tracking;
    }

    /**
     * Sets Tracking.
     * Optional Tracking Category – see Tracking. Any JournalLine can have a maximum of 2
     * <TrackingCategory> elements.
     *
     * @maps Tracking
     *
     * @param TrackingCategory[]|null $tracking
     */
    public function setTracking(?array $tracking): void
    {
        $this->tracking = $tracking;
    }

    /**
     * Converts the ManualJournalLine object to a human-readable string representation.
     *
     * @return string The string representation of the ManualJournalLine object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ManualJournalLine',
            [
                'accountCode' => $this->accountCode,
                'accountID' => $this->accountID,
                'description' => $this->description,
                'isBlank' => $this->isBlank,
                'lineAmount' => $this->lineAmount,
                'taxAmount' => $this->taxAmount,
                'taxType' => $this->taxType,
                'tracking' => $this->tracking
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->accountCode)) {
            $json['AccountCode'] = $this->accountCode;
        }
        if (isset($this->accountID)) {
            $json['AccountID']   = $this->accountID;
        }
        if (isset($this->description)) {
            $json['Description'] = $this->description;
        }
        if (isset($this->isBlank)) {
            $json['IsBlank']     = $this->isBlank;
        }
        if (isset($this->lineAmount)) {
            $json['LineAmount']  = $this->lineAmount;
        }
        if (isset($this->taxAmount)) {
            $json['TaxAmount']   = $this->taxAmount;
        }
        if (isset($this->taxType)) {
            $json['TaxType']     = $this->taxType;
        }
        if (isset($this->tracking)) {
            $json['Tracking']    = $this->tracking;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
