<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * OAuth 2 scopes supported by the API
 */
class OAuthScopeEnum
{
    /**
     * Grant read-write access to attachments
     */
    public const ACCOUNTING_ATTACHMENTS = 'accounting.attachments';

    /**
     * Grant read-only access to attachments
     */
    public const ACCOUNTING_ATTACHMENTS_READ = 'accounting.attachments.read';

    /**
     * Grant read-write access to contacts and contact groups
     */
    public const ACCOUNTING_CONTACTS = 'accounting.contacts';

    /**
     * Grant read-only access to contacts and contact groups
     */
    public const ACCOUNTING_CONTACTS_READ = 'accounting.contacts.read';

    /**
     * Grant read-only access to journals
     */
    public const ACCOUNTING_JOURNALS_READ = 'accounting.journals.read';

    /**
     * Grant read-only access to accounting reports
     */
    public const ACCOUNTING_REPORTS_READ = 'accounting.reports.read';

    /**
     * Grant read-only access to 1099 reports
     */
    public const ACCOUNTING_REPORTS_TENNINETYNINE_READ = 'accounting.reports.tenninetynine.read';

    /**
     * Grant read-write access to organisation and account settings
     */
    public const ACCOUNTING_SETTINGS = 'accounting.settings';

    /**
     * Grant read-only access to organisation and account settings
     */
    public const ACCOUNTING_SETTINGS_READ = 'accounting.settings.read';

    /**
     * Grant read-write access to bank transactions, credit notes, invoices, repeating invoices
     */
    public const ACCOUNTING_TRANSACTIONS = 'accounting.transactions';

    /**
     * Grant read-only access to invoices
     */
    public const ACCOUNTING_TRANSACTIONS_READ = 'accounting.transactions.read';

    /**
     * Grant read-write access to assets
     */
    public const ASSETS = 'assets';

    /**
     * Grant read-only access to fixed assets
     */
    public const ASSETS_READ = 'assets.read';

    /**
     * Grant read-write access to bankfeeds
     */
    public const BANKFEEDS = 'bankfeeds';

    /**
     * Grant read-only access to your email
     */
    public const EMAIL = 'email';

    /**
     * Grant read-write access to files and folders
     */
    public const FILES = 'files';

    /**
     * Grant read-only access to files and folders
     */
    public const FILES_READ = 'files.read';

    /**
     * Grant read-only access to your open id
     */
    public const OPENID = 'openid';

    /**
     * Grant read-write access to payment services
     */
    public const PAYMENTSERVICES = 'paymentservices';

    /**
     * Grant read-write access to payroll
     */
    public const PAYROLL = 'payroll';

    /**
     * Grant read-write access to payroll employees
     */
    public const PAYROLL_EMPLOYEES = 'payroll.employees';

    /**
     * Grant read-only access to payroll employees
     */
    public const PAYROLL_EMPLOYEES_READ = 'payroll.employees.read';

    /**
     * Grant read-write access to payroll leaveapplications
     */
    public const PAYROLL_LEAVEAPPLICATIONS = 'payroll.leaveapplications';

    /**
     * Grant read-only access to payroll leaveapplications
     */
    public const PAYROLL_LEAVEAPPLICATIONS_READ = 'payroll.leaveapplications.read';

    /**
     * Grant read-write access to payroll payitems
     */
    public const PAYROLL_PAYITEMS = 'payroll.payitems';

    /**
     * Grant read-only access to payroll payitems
     */
    public const PAYROLL_PAYITEMS_READ = 'payroll.payitems.read';

    /**
     * Grant read-write access to payroll calendars
     */
    public const PAYROLL_PAYROLLCALENDARS = 'payroll.payrollcalendars';

    /**
     * Grant read-only access to payroll calendars
     */
    public const PAYROLL_PAYROLLCALENDARS_READ = 'payroll.payrollcalendars.read';

    /**
     * Grant read-write access to payroll payruns
     */
    public const PAYROLL_PAYRUNS = 'payroll.payruns';

    /**
     * Grant read-only access to payroll payruns
     */
    public const PAYROLL_PAYRUNS_READ = 'payroll.payruns.read';

    /**
     * Grant read-write access to payroll payslips
     */
    public const PAYROLL_PAYSLIP = 'payroll.payslip';

    /**
     * Grant read-only access to payroll payslips
     */
    public const PAYROLL_PAYSLIP_READ = 'payroll.payslip.read';

    /**
     * Grant read-only access to payroll
     */
    public const PAYROLL_READ = 'payroll.read';

    /**
     * Grant read-only access to payroll settings
     */
    public const PAYROLL_SETTINGS_READ = 'payroll.settings.read';

    /**
     * Grant read-only access to payroll superfundproducts
     */
    public const PAYROLL_SUPERFUNDPRODUCTS_READ = 'payroll.superfundproducts.read';

    /**
     * Grant read-write access to payroll superfunds
     */
    public const PAYROLL_SUPERFUNDS = 'payroll.superfunds';

    /**
     * Grant read-only access to payroll superfunds
     */
    public const PAYROLL_SUPERFUNDS_READ = 'payroll.superfunds.read';

    /**
     * Grant read-write access to payroll timesheets
     */
    public const PAYROLL_TIMESHEETS = 'payroll.timesheets';

    /**
     * Grant read-only access to payroll timesheets
     */
    public const PAYROLL_TIMESHEETS_READ = 'payroll.timesheets.read';

    /**
     * your profile information
     */
    public const PROFILE = 'profile';

    /**
     * Grant read-write access to projects
     */
    public const PROJECTS = 'projects';

    /**
     * Grant read-only access to projects
     */
    public const PROJECTS_READ = 'projects.read';

    private const _ALL_VALUES = [
        self::ACCOUNTING_ATTACHMENTS,
        self::ACCOUNTING_ATTACHMENTS_READ,
        self::ACCOUNTING_CONTACTS,
        self::ACCOUNTING_CONTACTS_READ,
        self::ACCOUNTING_JOURNALS_READ,
        self::ACCOUNTING_REPORTS_READ,
        self::ACCOUNTING_REPORTS_TENNINETYNINE_READ,
        self::ACCOUNTING_SETTINGS,
        self::ACCOUNTING_SETTINGS_READ,
        self::ACCOUNTING_TRANSACTIONS,
        self::ACCOUNTING_TRANSACTIONS_READ,
        self::ASSETS,
        self::ASSETS_READ,
        self::BANKFEEDS,
        self::EMAIL,
        self::FILES,
        self::FILES_READ,
        self::OPENID,
        self::PAYMENTSERVICES,
        self::PAYROLL,
        self::PAYROLL_EMPLOYEES,
        self::PAYROLL_EMPLOYEES_READ,
        self::PAYROLL_LEAVEAPPLICATIONS,
        self::PAYROLL_LEAVEAPPLICATIONS_READ,
        self::PAYROLL_PAYITEMS,
        self::PAYROLL_PAYITEMS_READ,
        self::PAYROLL_PAYROLLCALENDARS,
        self::PAYROLL_PAYROLLCALENDARS_READ,
        self::PAYROLL_PAYRUNS,
        self::PAYROLL_PAYRUNS_READ,
        self::PAYROLL_PAYSLIP,
        self::PAYROLL_PAYSLIP_READ,
        self::PAYROLL_READ,
        self::PAYROLL_SETTINGS_READ,
        self::PAYROLL_SUPERFUNDPRODUCTS_READ,
        self::PAYROLL_SUPERFUNDS,
        self::PAYROLL_SUPERFUNDS_READ,
        self::PAYROLL_TIMESHEETS,
        self::PAYROLL_TIMESHEETS_READ,
        self::PROFILE,
        self::PROJECTS,
        self::PROJECTS_READ
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for OAuthScopeEnum.");
    }
}
