<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class Organisation implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $aPIKey;

    /**
     * @var AddressForOrganisation[]|null
     */
    private $addresses;

    /**
     * @var string|null
     */
    private $baseCurrency;

    /**
     * @var string|null
     */
    private $class;

    /**
     * @var string|null
     */
    private $countryCode;

    /**
     * @var string|null
     */
    private $createdDateUTC;

    /**
     * @var string|null
     */
    private $defaultPurchasesTax;

    /**
     * @var string|null
     */
    private $defaultSalesTax;

    /**
     * @var string|null
     */
    private $edition;

    /**
     * @var string|null
     */
    private $employerIdentificationNumber;

    /**
     * @var string|null
     */
    private $endOfYearLockDate;

    /**
     * @var ExternalLink[]|null
     */
    private $externalLinks;

    /**
     * @var int|null
     */
    private $financialYearEndDay;

    /**
     * @var int|null
     */
    private $financialYearEndMonth;

    /**
     * @var bool|null
     */
    private $isDemoCompany;

    /**
     * @var string|null
     */
    private $legalName;

    /**
     * @var string|null
     */
    private $lineOfBusiness;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $organisationEntityType;

    /**
     * @var string|null
     */
    private $organisationID;

    /**
     * @var string|null
     */
    private $organisationStatus;

    /**
     * @var string|null
     */
    private $organisationType;

    /**
     * @var PaymentTerm|null
     */
    private $paymentTerms;

    /**
     * @var bool|null
     */
    private $paysTax;

    /**
     * @var string|null
     */
    private $periodLockDate;

    /**
     * @var Phone[]|null
     */
    private $phones;

    /**
     * @var string|null
     */
    private $registrationNumber;

    /**
     * @var string|null
     */
    private $salesTaxBasis;

    /**
     * @var string|null
     */
    private $salesTaxPeriod;

    /**
     * @var string|null
     */
    private $shortCode;

    /**
     * @var string|null
     */
    private $taxNumber;

    /**
     * @var string|null
     */
    private $timezone;

    /**
     * @var string|null
     */
    private $version;

    /**
     * Returns A PI Key.
     * Display a unique key used for Xero-to-Xero transactions
     */
    public function getAPIKey(): ?string
    {
        return $this->aPIKey;
    }

    /**
     * Sets A PI Key.
     * Display a unique key used for Xero-to-Xero transactions
     *
     * @maps APIKey
     */
    public function setAPIKey(?string $aPIKey): void
    {
        $this->aPIKey = $aPIKey;
    }

    /**
     * Returns Addresses.
     * Address details for organisation – see Addresses
     *
     * @return AddressForOrganisation[]|null
     */
    public function getAddresses(): ?array
    {
        return $this->addresses;
    }

    /**
     * Sets Addresses.
     * Address details for organisation – see Addresses
     *
     * @maps Addresses
     *
     * @param AddressForOrganisation[]|null $addresses
     */
    public function setAddresses(?array $addresses): void
    {
        $this->addresses = $addresses;
    }

    /**
     * Returns Base Currency.
     * 3 letter alpha code for the currency – see list of currency codes
     */
    public function getBaseCurrency(): ?string
    {
        return $this->baseCurrency;
    }

    /**
     * Sets Base Currency.
     * 3 letter alpha code for the currency – see list of currency codes
     *
     * @maps BaseCurrency
     * @factory \XeroAccountingAPILib\Models\CurrencyCodeEnum::checkValue
     */
    public function setBaseCurrency(?string $baseCurrency): void
    {
        $this->baseCurrency = $baseCurrency;
    }

    /**
     * Returns Class.
     * Organisation Classes describe which plan the Xero organisation is on (e.g. DEMO, TRIAL, PREMIUM)
     */
    public function getClass(): ?string
    {
        return $this->class;
    }

    /**
     * Sets Class.
     * Organisation Classes describe which plan the Xero organisation is on (e.g. DEMO, TRIAL, PREMIUM)
     *
     * @maps Class
     * @factory \XeroAccountingAPILib\Models\Class1Enum::checkValue
     */
    public function setClass(?string $class): void
    {
        $this->class = $class;
    }

    /**
     * Returns Country Code.
     */
    public function getCountryCode(): ?string
    {
        return $this->countryCode;
    }

    /**
     * Sets Country Code.
     *
     * @maps CountryCode
     * @factory \XeroAccountingAPILib\Models\CountryCodeEnum::checkValue
     */
    public function setCountryCode(?string $countryCode): void
    {
        $this->countryCode = $countryCode;
    }

    /**
     * Returns Created Date UTC.
     * Timestamp when the organisation was created in Xero
     */
    public function getCreatedDateUTC(): ?string
    {
        return $this->createdDateUTC;
    }

    /**
     * Sets Created Date UTC.
     * Timestamp when the organisation was created in Xero
     *
     * @maps CreatedDateUTC
     */
    public function setCreatedDateUTC(?string $createdDateUTC): void
    {
        $this->createdDateUTC = $createdDateUTC;
    }

    /**
     * Returns Default Purchases Tax.
     * The default for LineAmountTypes on purchase transactions
     */
    public function getDefaultPurchasesTax(): ?string
    {
        return $this->defaultPurchasesTax;
    }

    /**
     * Sets Default Purchases Tax.
     * The default for LineAmountTypes on purchase transactions
     *
     * @maps DefaultPurchasesTax
     */
    public function setDefaultPurchasesTax(?string $defaultPurchasesTax): void
    {
        $this->defaultPurchasesTax = $defaultPurchasesTax;
    }

    /**
     * Returns Default Sales Tax.
     * The default for LineAmountTypes on sales transactions
     */
    public function getDefaultSalesTax(): ?string
    {
        return $this->defaultSalesTax;
    }

    /**
     * Sets Default Sales Tax.
     * The default for LineAmountTypes on sales transactions
     *
     * @maps DefaultSalesTax
     */
    public function setDefaultSalesTax(?string $defaultSalesTax): void
    {
        $this->defaultSalesTax = $defaultSalesTax;
    }

    /**
     * Returns Edition.
     * BUSINESS or PARTNER. Partner edition organisations are sold exclusively through accounting partners
     * and have restricted functionality (e.g. no access to invoicing)
     */
    public function getEdition(): ?string
    {
        return $this->edition;
    }

    /**
     * Sets Edition.
     * BUSINESS or PARTNER. Partner edition organisations are sold exclusively through accounting partners
     * and have restricted functionality (e.g. no access to invoicing)
     *
     * @maps Edition
     * @factory \XeroAccountingAPILib\Models\EditionEnum::checkValue
     */
    public function setEdition(?string $edition): void
    {
        $this->edition = $edition;
    }

    /**
     * Returns Employer Identification Number.
     * Shown if set. US Only.
     */
    public function getEmployerIdentificationNumber(): ?string
    {
        return $this->employerIdentificationNumber;
    }

    /**
     * Sets Employer Identification Number.
     * Shown if set. US Only.
     *
     * @maps EmployerIdentificationNumber
     */
    public function setEmployerIdentificationNumber(?string $employerIdentificationNumber): void
    {
        $this->employerIdentificationNumber = $employerIdentificationNumber;
    }

    /**
     * Returns End of Year Lock Date.
     * Shown if set. See lock dates
     */
    public function getEndOfYearLockDate(): ?string
    {
        return $this->endOfYearLockDate;
    }

    /**
     * Sets End of Year Lock Date.
     * Shown if set. See lock dates
     *
     * @maps EndOfYearLockDate
     */
    public function setEndOfYearLockDate(?string $endOfYearLockDate): void
    {
        $this->endOfYearLockDate = $endOfYearLockDate;
    }

    /**
     * Returns External Links.
     * Organisation profile links for popular services such as Facebook,Twitter, GooglePlus and LinkedIn.
     * You can also add link to your website here. Shown if Organisation settings  is updated in Xero. See
     * ExternalLinks below
     *
     * @return ExternalLink[]|null
     */
    public function getExternalLinks(): ?array
    {
        return $this->externalLinks;
    }

    /**
     * Sets External Links.
     * Organisation profile links for popular services such as Facebook,Twitter, GooglePlus and LinkedIn.
     * You can also add link to your website here. Shown if Organisation settings  is updated in Xero. See
     * ExternalLinks below
     *
     * @maps ExternalLinks
     *
     * @param ExternalLink[]|null $externalLinks
     */
    public function setExternalLinks(?array $externalLinks): void
    {
        $this->externalLinks = $externalLinks;
    }

    /**
     * Returns Financial Year End Day.
     * Calendar day e.g. 0-31
     */
    public function getFinancialYearEndDay(): ?int
    {
        return $this->financialYearEndDay;
    }

    /**
     * Sets Financial Year End Day.
     * Calendar day e.g. 0-31
     *
     * @maps FinancialYearEndDay
     */
    public function setFinancialYearEndDay(?int $financialYearEndDay): void
    {
        $this->financialYearEndDay = $financialYearEndDay;
    }

    /**
     * Returns Financial Year End Month.
     * Calendar Month e.g. 1-12
     */
    public function getFinancialYearEndMonth(): ?int
    {
        return $this->financialYearEndMonth;
    }

    /**
     * Sets Financial Year End Month.
     * Calendar Month e.g. 1-12
     *
     * @maps FinancialYearEndMonth
     */
    public function setFinancialYearEndMonth(?int $financialYearEndMonth): void
    {
        $this->financialYearEndMonth = $financialYearEndMonth;
    }

    /**
     * Returns Is Demo Company.
     * Boolean to describe if organisation is a demo company.
     */
    public function getIsDemoCompany(): ?bool
    {
        return $this->isDemoCompany;
    }

    /**
     * Sets Is Demo Company.
     * Boolean to describe if organisation is a demo company.
     *
     * @maps IsDemoCompany
     */
    public function setIsDemoCompany(?bool $isDemoCompany): void
    {
        $this->isDemoCompany = $isDemoCompany;
    }

    /**
     * Returns Legal Name.
     * Organisation name shown on Reports
     */
    public function getLegalName(): ?string
    {
        return $this->legalName;
    }

    /**
     * Sets Legal Name.
     * Organisation name shown on Reports
     *
     * @maps LegalName
     */
    public function setLegalName(?string $legalName): void
    {
        $this->legalName = $legalName;
    }

    /**
     * Returns Line of Business.
     * Description of business type as defined in Organisation settings
     */
    public function getLineOfBusiness(): ?string
    {
        return $this->lineOfBusiness;
    }

    /**
     * Sets Line of Business.
     * Description of business type as defined in Organisation settings
     *
     * @maps LineOfBusiness
     */
    public function setLineOfBusiness(?string $lineOfBusiness): void
    {
        $this->lineOfBusiness = $lineOfBusiness;
    }

    /**
     * Returns Name.
     * Display name of organisation shown in Xero
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * Display name of organisation shown in Xero
     *
     * @maps Name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Organisation Entity Type.
     * Organisation Entity Type
     */
    public function getOrganisationEntityType(): ?string
    {
        return $this->organisationEntityType;
    }

    /**
     * Sets Organisation Entity Type.
     * Organisation Entity Type
     *
     * @maps OrganisationEntityType
     * @factory \XeroAccountingAPILib\Models\OrganisationEntityTypeEnum::checkValue
     */
    public function setOrganisationEntityType(?string $organisationEntityType): void
    {
        $this->organisationEntityType = $organisationEntityType;
    }

    /**
     * Returns Organisation ID.
     * Unique Xero identifier
     */
    public function getOrganisationID(): ?string
    {
        return $this->organisationID;
    }

    /**
     * Sets Organisation ID.
     * Unique Xero identifier
     *
     * @maps OrganisationID
     */
    public function setOrganisationID(?string $organisationID): void
    {
        $this->organisationID = $organisationID;
    }

    /**
     * Returns Organisation Status.
     * Will be set to ACTIVE if you can connect to organisation via the Xero API
     */
    public function getOrganisationStatus(): ?string
    {
        return $this->organisationStatus;
    }

    /**
     * Sets Organisation Status.
     * Will be set to ACTIVE if you can connect to organisation via the Xero API
     *
     * @maps OrganisationStatus
     */
    public function setOrganisationStatus(?string $organisationStatus): void
    {
        $this->organisationStatus = $organisationStatus;
    }

    /**
     * Returns Organisation Type.
     * Organisation Type
     */
    public function getOrganisationType(): ?string
    {
        return $this->organisationType;
    }

    /**
     * Sets Organisation Type.
     * Organisation Type
     *
     * @maps OrganisationType
     * @factory \XeroAccountingAPILib\Models\OrganisationTypeEnum::checkValue
     */
    public function setOrganisationType(?string $organisationType): void
    {
        $this->organisationType = $organisationType;
    }

    /**
     * Returns Payment Terms.
     */
    public function getPaymentTerms(): ?PaymentTerm
    {
        return $this->paymentTerms;
    }

    /**
     * Sets Payment Terms.
     *
     * @maps PaymentTerms
     */
    public function setPaymentTerms(?PaymentTerm $paymentTerms): void
    {
        $this->paymentTerms = $paymentTerms;
    }

    /**
     * Returns Pays Tax.
     * Boolean to describe if organisation is registered with a local tax authority i.e. true, false
     */
    public function getPaysTax(): ?bool
    {
        return $this->paysTax;
    }

    /**
     * Sets Pays Tax.
     * Boolean to describe if organisation is registered with a local tax authority i.e. true, false
     *
     * @maps PaysTax
     */
    public function setPaysTax(?bool $paysTax): void
    {
        $this->paysTax = $paysTax;
    }

    /**
     * Returns Period Lock Date.
     * Shown if set. See lock dates
     */
    public function getPeriodLockDate(): ?string
    {
        return $this->periodLockDate;
    }

    /**
     * Sets Period Lock Date.
     * Shown if set. See lock dates
     *
     * @maps PeriodLockDate
     */
    public function setPeriodLockDate(?string $periodLockDate): void
    {
        $this->periodLockDate = $periodLockDate;
    }

    /**
     * Returns Phones.
     * Phones details for organisation – see Phones
     *
     * @return Phone[]|null
     */
    public function getPhones(): ?array
    {
        return $this->phones;
    }

    /**
     * Sets Phones.
     * Phones details for organisation – see Phones
     *
     * @maps Phones
     *
     * @param Phone[]|null $phones
     */
    public function setPhones(?array $phones): void
    {
        $this->phones = $phones;
    }

    /**
     * Returns Registration Number.
     * Shows for New Zealand, Australian and UK organisations
     */
    public function getRegistrationNumber(): ?string
    {
        return $this->registrationNumber;
    }

    /**
     * Sets Registration Number.
     * Shows for New Zealand, Australian and UK organisations
     *
     * @maps RegistrationNumber
     */
    public function setRegistrationNumber(?string $registrationNumber): void
    {
        $this->registrationNumber = $registrationNumber;
    }

    /**
     * Returns Sales Tax Basis.
     * The accounting basis used for tax returns. See Sales Tax Basis
     */
    public function getSalesTaxBasis(): ?string
    {
        return $this->salesTaxBasis;
    }

    /**
     * Sets Sales Tax Basis.
     * The accounting basis used for tax returns. See Sales Tax Basis
     *
     * @maps SalesTaxBasis
     * @factory \XeroAccountingAPILib\Models\SalesTaxBasisEnum::checkValue
     */
    public function setSalesTaxBasis(?string $salesTaxBasis): void
    {
        $this->salesTaxBasis = $salesTaxBasis;
    }

    /**
     * Returns Sales Tax Period.
     * The frequency with which tax returns are processed. See Sales Tax Period
     */
    public function getSalesTaxPeriod(): ?string
    {
        return $this->salesTaxPeriod;
    }

    /**
     * Sets Sales Tax Period.
     * The frequency with which tax returns are processed. See Sales Tax Period
     *
     * @maps SalesTaxPeriod
     * @factory \XeroAccountingAPILib\Models\SalesTaxPeriodEnum::checkValue
     */
    public function setSalesTaxPeriod(?string $salesTaxPeriod): void
    {
        $this->salesTaxPeriod = $salesTaxPeriod;
    }

    /**
     * Returns Short Code.
     * A unique identifier for the organisation. Potential uses.
     */
    public function getShortCode(): ?string
    {
        return $this->shortCode;
    }

    /**
     * Sets Short Code.
     * A unique identifier for the organisation. Potential uses.
     *
     * @maps ShortCode
     */
    public function setShortCode(?string $shortCode): void
    {
        $this->shortCode = $shortCode;
    }

    /**
     * Returns Tax Number.
     * Shown if set. Displays in the Xero UI as Tax File Number (AU), GST Number (NZ), VAT Number (UK) and
     * Tax ID Number (US & Global).
     */
    public function getTaxNumber(): ?string
    {
        return $this->taxNumber;
    }

    /**
     * Sets Tax Number.
     * Shown if set. Displays in the Xero UI as Tax File Number (AU), GST Number (NZ), VAT Number (UK) and
     * Tax ID Number (US & Global).
     *
     * @maps TaxNumber
     */
    public function setTaxNumber(?string $taxNumber): void
    {
        $this->taxNumber = $taxNumber;
    }

    /**
     * Returns Timezone.
     * Timezone specifications
     */
    public function getTimezone(): ?string
    {
        return $this->timezone;
    }

    /**
     * Sets Timezone.
     * Timezone specifications
     *
     * @maps Timezone
     * @factory \XeroAccountingAPILib\Models\TimeZoneEnum::checkValue
     */
    public function setTimezone(?string $timezone): void
    {
        $this->timezone = $timezone;
    }

    /**
     * Returns Version.
     * See Version Types
     */
    public function getVersion(): ?string
    {
        return $this->version;
    }

    /**
     * Sets Version.
     * See Version Types
     *
     * @maps Version
     * @factory \XeroAccountingAPILib\Models\VersionEnum::checkValue
     */
    public function setVersion(?string $version): void
    {
        $this->version = $version;
    }

    /**
     * Converts the Organisation object to a human-readable string representation.
     *
     * @return string The string representation of the Organisation object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Organisation',
            [
                'aPIKey' => $this->aPIKey,
                'addresses' => $this->addresses,
                'baseCurrency' => $this->baseCurrency,
                'class' => $this->class,
                'countryCode' => $this->countryCode,
                'createdDateUTC' => $this->createdDateUTC,
                'defaultPurchasesTax' => $this->defaultPurchasesTax,
                'defaultSalesTax' => $this->defaultSalesTax,
                'edition' => $this->edition,
                'employerIdentificationNumber' => $this->employerIdentificationNumber,
                'endOfYearLockDate' => $this->endOfYearLockDate,
                'externalLinks' => $this->externalLinks,
                'financialYearEndDay' => $this->financialYearEndDay,
                'financialYearEndMonth' => $this->financialYearEndMonth,
                'isDemoCompany' => $this->isDemoCompany,
                'legalName' => $this->legalName,
                'lineOfBusiness' => $this->lineOfBusiness,
                'name' => $this->name,
                'organisationEntityType' => $this->organisationEntityType,
                'organisationID' => $this->organisationID,
                'organisationStatus' => $this->organisationStatus,
                'organisationType' => $this->organisationType,
                'paymentTerms' => $this->paymentTerms,
                'paysTax' => $this->paysTax,
                'periodLockDate' => $this->periodLockDate,
                'phones' => $this->phones,
                'registrationNumber' => $this->registrationNumber,
                'salesTaxBasis' => $this->salesTaxBasis,
                'salesTaxPeriod' => $this->salesTaxPeriod,
                'shortCode' => $this->shortCode,
                'taxNumber' => $this->taxNumber,
                'timezone' => $this->timezone,
                'version' => $this->version
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->aPIKey)) {
            $json['APIKey']                       = $this->aPIKey;
        }
        if (isset($this->addresses)) {
            $json['Addresses']                    = $this->addresses;
        }
        if (isset($this->baseCurrency)) {
            $json['BaseCurrency']                 = CurrencyCodeEnum::checkValue($this->baseCurrency);
        }
        if (isset($this->class)) {
            $json['Class']                        = Class1Enum::checkValue($this->class);
        }
        if (isset($this->countryCode)) {
            $json['CountryCode']                  = CountryCodeEnum::checkValue($this->countryCode);
        }
        if (isset($this->createdDateUTC)) {
            $json['CreatedDateUTC']               = $this->createdDateUTC;
        }
        if (isset($this->defaultPurchasesTax)) {
            $json['DefaultPurchasesTax']          = $this->defaultPurchasesTax;
        }
        if (isset($this->defaultSalesTax)) {
            $json['DefaultSalesTax']              = $this->defaultSalesTax;
        }
        if (isset($this->edition)) {
            $json['Edition']                      = EditionEnum::checkValue($this->edition);
        }
        if (isset($this->employerIdentificationNumber)) {
            $json['EmployerIdentificationNumber'] = $this->employerIdentificationNumber;
        }
        if (isset($this->endOfYearLockDate)) {
            $json['EndOfYearLockDate']            = $this->endOfYearLockDate;
        }
        if (isset($this->externalLinks)) {
            $json['ExternalLinks']                = $this->externalLinks;
        }
        if (isset($this->financialYearEndDay)) {
            $json['FinancialYearEndDay']          = $this->financialYearEndDay;
        }
        if (isset($this->financialYearEndMonth)) {
            $json['FinancialYearEndMonth']        = $this->financialYearEndMonth;
        }
        if (isset($this->isDemoCompany)) {
            $json['IsDemoCompany']                = $this->isDemoCompany;
        }
        if (isset($this->legalName)) {
            $json['LegalName']                    = $this->legalName;
        }
        if (isset($this->lineOfBusiness)) {
            $json['LineOfBusiness']               = $this->lineOfBusiness;
        }
        if (isset($this->name)) {
            $json['Name']                         = $this->name;
        }
        if (isset($this->organisationEntityType)) {
            $json['OrganisationEntityType']       =
                OrganisationEntityTypeEnum::checkValue(
                    $this->organisationEntityType
                );
        }
        if (isset($this->organisationID)) {
            $json['OrganisationID']               = $this->organisationID;
        }
        if (isset($this->organisationStatus)) {
            $json['OrganisationStatus']           = $this->organisationStatus;
        }
        if (isset($this->organisationType)) {
            $json['OrganisationType']             = OrganisationTypeEnum::checkValue($this->organisationType);
        }
        if (isset($this->paymentTerms)) {
            $json['PaymentTerms']                 = $this->paymentTerms;
        }
        if (isset($this->paysTax)) {
            $json['PaysTax']                      = $this->paysTax;
        }
        if (isset($this->periodLockDate)) {
            $json['PeriodLockDate']               = $this->periodLockDate;
        }
        if (isset($this->phones)) {
            $json['Phones']                       = $this->phones;
        }
        if (isset($this->registrationNumber)) {
            $json['RegistrationNumber']           = $this->registrationNumber;
        }
        if (isset($this->salesTaxBasis)) {
            $json['SalesTaxBasis']                = SalesTaxBasisEnum::checkValue($this->salesTaxBasis);
        }
        if (isset($this->salesTaxPeriod)) {
            $json['SalesTaxPeriod']               = SalesTaxPeriodEnum::checkValue($this->salesTaxPeriod);
        }
        if (isset($this->shortCode)) {
            $json['ShortCode']                    = $this->shortCode;
        }
        if (isset($this->taxNumber)) {
            $json['TaxNumber']                    = $this->taxNumber;
        }
        if (isset($this->timezone)) {
            $json['Timezone']                     = TimeZoneEnum::checkValue($this->timezone);
        }
        if (isset($this->version)) {
            $json['Version']                      = VersionEnum::checkValue($this->version);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
