<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class Organisations implements \JsonSerializable
{
    /**
     * @var Organisation[]|null
     */
    private $organisations;

    /**
     * Returns Organisations.
     *
     * @return Organisation[]|null
     */
    public function getOrganisations(): ?array
    {
        return $this->organisations;
    }

    /**
     * Sets Organisations.
     *
     * @maps Organisations
     *
     * @param Organisation[]|null $organisations
     */
    public function setOrganisations(?array $organisations): void
    {
        $this->organisations = $organisations;
    }

    /**
     * Converts the Organisations object to a human-readable string representation.
     *
     * @return string The string representation of the Organisations object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Organisations', ['organisations' => $this->organisations]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->organisations)) {
            $json['Organisations'] = $this->organisations;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
