<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class PaymentTerm implements \JsonSerializable
{
    /**
     * @var Bill|null
     */
    private $bills;

    /**
     * @var Bill|null
     */
    private $sales;

    /**
     * Returns Bills.
     */
    public function getBills(): ?Bill
    {
        return $this->bills;
    }

    /**
     * Sets Bills.
     *
     * @maps Bills
     */
    public function setBills(?Bill $bills): void
    {
        $this->bills = $bills;
    }

    /**
     * Returns Sales.
     */
    public function getSales(): ?Bill
    {
        return $this->sales;
    }

    /**
     * Sets Sales.
     *
     * @maps Sales
     */
    public function setSales(?Bill $sales): void
    {
        $this->sales = $sales;
    }

    /**
     * Converts the PaymentTerm object to a human-readable string representation.
     *
     * @return string The string representation of the PaymentTerm object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('PaymentTerm', ['bills' => $this->bills, 'sales' => $this->sales]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->bills)) {
            $json['Bills'] = $this->bills;
        }
        if (isset($this->sales)) {
            $json['Sales'] = $this->sales;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
