<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class Phone implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $phoneAreaCode;

    /**
     * @var string|null
     */
    private $phoneCountryCode;

    /**
     * @var string|null
     */
    private $phoneNumber;

    /**
     * @var string|null
     */
    private $phoneType;

    /**
     * Returns Phone Area Code.
     * max length = 10
     */
    public function getPhoneAreaCode(): ?string
    {
        return $this->phoneAreaCode;
    }

    /**
     * Sets Phone Area Code.
     * max length = 10
     *
     * @maps PhoneAreaCode
     */
    public function setPhoneAreaCode(?string $phoneAreaCode): void
    {
        $this->phoneAreaCode = $phoneAreaCode;
    }

    /**
     * Returns Phone Country Code.
     * max length = 20
     */
    public function getPhoneCountryCode(): ?string
    {
        return $this->phoneCountryCode;
    }

    /**
     * Sets Phone Country Code.
     * max length = 20
     *
     * @maps PhoneCountryCode
     */
    public function setPhoneCountryCode(?string $phoneCountryCode): void
    {
        $this->phoneCountryCode = $phoneCountryCode;
    }

    /**
     * Returns Phone Number.
     * max length = 50
     */
    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    /**
     * Sets Phone Number.
     * max length = 50
     *
     * @maps PhoneNumber
     */
    public function setPhoneNumber(?string $phoneNumber): void
    {
        $this->phoneNumber = $phoneNumber;
    }

    /**
     * Returns Phone Type.
     */
    public function getPhoneType(): ?string
    {
        return $this->phoneType;
    }

    /**
     * Sets Phone Type.
     *
     * @maps PhoneType
     * @factory \XeroAccountingAPILib\Models\PhoneTypeEnum::checkValue
     */
    public function setPhoneType(?string $phoneType): void
    {
        $this->phoneType = $phoneType;
    }

    /**
     * Converts the Phone object to a human-readable string representation.
     *
     * @return string The string representation of the Phone object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Phone',
            [
                'phoneAreaCode' => $this->phoneAreaCode,
                'phoneCountryCode' => $this->phoneCountryCode,
                'phoneNumber' => $this->phoneNumber,
                'phoneType' => $this->phoneType
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->phoneAreaCode)) {
            $json['PhoneAreaCode']    = $this->phoneAreaCode;
        }
        if (isset($this->phoneCountryCode)) {
            $json['PhoneCountryCode'] = $this->phoneCountryCode;
        }
        if (isset($this->phoneNumber)) {
            $json['PhoneNumber']      = $this->phoneNumber;
        }
        if (isset($this->phoneType)) {
            $json['PhoneType']        = PhoneTypeEnum::checkValue($this->phoneType);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
