<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class Prepayments implements \JsonSerializable
{
    /**
     * @var Prepayment[]|null
     */
    private $prepayments;

    /**
     * Returns Prepayments.
     *
     * @return Prepayment[]|null
     */
    public function getPrepayments(): ?array
    {
        return $this->prepayments;
    }

    /**
     * Sets Prepayments.
     *
     * @maps Prepayments
     *
     * @param Prepayment[]|null $prepayments
     */
    public function setPrepayments(?array $prepayments): void
    {
        $this->prepayments = $prepayments;
    }

    /**
     * Converts the Prepayments object to a human-readable string representation.
     *
     * @return string The string representation of the Prepayments object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Prepayments', ['prepayments' => $this->prepayments]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->prepayments)) {
            $json['Prepayments'] = $this->prepayments;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
