<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class PurchaseOrder implements \JsonSerializable
{
    /**
     * @var Attachment[]|null
     */
    private $attachments;

    /**
     * @var string|null
     */
    private $attentionTo;

    /**
     * @var string|null
     */
    private $brandingThemeID;

    /**
     * @var Contact|null
     */
    private $contact;

    /**
     * @var string|null
     */
    private $currencyCode;

    /**
     * @var float|null
     */
    private $currencyRate;

    /**
     * @var string|null
     */
    private $date;

    /**
     * @var string|null
     */
    private $deliveryAddress;

    /**
     * @var string|null
     */
    private $deliveryDate;

    /**
     * @var string|null
     */
    private $deliveryInstructions;

    /**
     * @var string|null
     */
    private $expectedArrivalDate;

    /**
     * @var bool|null
     */
    private $hasAttachments = false;

    /**
     * @var string|null
     */
    private $lineAmountTypes;

    /**
     * @var LineItem[]|null
     */
    private $lineItems;

    /**
     * @var string|null
     */
    private $purchaseOrderID;

    /**
     * @var string|null
     */
    private $purchaseOrderNumber;

    /**
     * @var string|null
     */
    private $reference;

    /**
     * @var bool|null
     */
    private $sentToContact;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $statusAttributeString;

    /**
     * @var float|null
     */
    private $subTotal;

    /**
     * @var string|null
     */
    private $telephone;

    /**
     * @var float|null
     */
    private $total;

    /**
     * @var float|null
     */
    private $totalDiscount;

    /**
     * @var float|null
     */
    private $totalTax;

    /**
     * @var string|null
     */
    private $updatedDateUTC;

    /**
     * @var ValidationError[]|null
     */
    private $validationErrors;

    /**
     * @var ValidationError[]|null
     */
    private $warnings;

    /**
     * Returns Attachments.
     * Displays array of attachments from the API
     *
     * @return Attachment[]|null
     */
    public function getAttachments(): ?array
    {
        return $this->attachments;
    }

    /**
     * Sets Attachments.
     * Displays array of attachments from the API
     *
     * @maps Attachments
     *
     * @param Attachment[]|null $attachments
     */
    public function setAttachments(?array $attachments): void
    {
        $this->attachments = $attachments;
    }

    /**
     * Returns Attention To.
     * The person that the delivery is going to
     */
    public function getAttentionTo(): ?string
    {
        return $this->attentionTo;
    }

    /**
     * Sets Attention To.
     * The person that the delivery is going to
     *
     * @maps AttentionTo
     */
    public function setAttentionTo(?string $attentionTo): void
    {
        $this->attentionTo = $attentionTo;
    }

    /**
     * Returns Branding Theme ID.
     * See BrandingThemes
     */
    public function getBrandingThemeID(): ?string
    {
        return $this->brandingThemeID;
    }

    /**
     * Sets Branding Theme ID.
     * See BrandingThemes
     *
     * @maps BrandingThemeID
     */
    public function setBrandingThemeID(?string $brandingThemeID): void
    {
        $this->brandingThemeID = $brandingThemeID;
    }

    /**
     * Returns Contact.
     */
    public function getContact(): ?Contact
    {
        return $this->contact;
    }

    /**
     * Sets Contact.
     *
     * @maps Contact
     */
    public function setContact(?Contact $contact): void
    {
        $this->contact = $contact;
    }

    /**
     * Returns Currency Code.
     * 3 letter alpha code for the currency – see list of currency codes
     */
    public function getCurrencyCode(): ?string
    {
        return $this->currencyCode;
    }

    /**
     * Sets Currency Code.
     * 3 letter alpha code for the currency – see list of currency codes
     *
     * @maps CurrencyCode
     * @factory \XeroAccountingAPILib\Models\CurrencyCodeEnum::checkValue
     */
    public function setCurrencyCode(?string $currencyCode): void
    {
        $this->currencyCode = $currencyCode;
    }

    /**
     * Returns Currency Rate.
     * The currency rate for a multicurrency purchase order. If no rate is specified, the XE.com day rate
     * is used.
     */
    public function getCurrencyRate(): ?float
    {
        return $this->currencyRate;
    }

    /**
     * Sets Currency Rate.
     * The currency rate for a multicurrency purchase order. If no rate is specified, the XE.com day rate
     * is used.
     *
     * @maps CurrencyRate
     */
    public function setCurrencyRate(?float $currencyRate): void
    {
        $this->currencyRate = $currencyRate;
    }

    /**
     * Returns Date.
     * Date purchase order was issued – YYYY-MM-DD. If the Date element is not specified then it will
     * default to the current date based on the timezone setting of the organisation
     */
    public function getDate(): ?string
    {
        return $this->date;
    }

    /**
     * Sets Date.
     * Date purchase order was issued – YYYY-MM-DD. If the Date element is not specified then it will
     * default to the current date based on the timezone setting of the organisation
     *
     * @maps Date
     */
    public function setDate(?string $date): void
    {
        $this->date = $date;
    }

    /**
     * Returns Delivery Address.
     * The address the goods are to be delivered to
     */
    public function getDeliveryAddress(): ?string
    {
        return $this->deliveryAddress;
    }

    /**
     * Sets Delivery Address.
     * The address the goods are to be delivered to
     *
     * @maps DeliveryAddress
     */
    public function setDeliveryAddress(?string $deliveryAddress): void
    {
        $this->deliveryAddress = $deliveryAddress;
    }

    /**
     * Returns Delivery Date.
     * Date the goods are to be delivered – YYYY-MM-DD
     */
    public function getDeliveryDate(): ?string
    {
        return $this->deliveryDate;
    }

    /**
     * Sets Delivery Date.
     * Date the goods are to be delivered – YYYY-MM-DD
     *
     * @maps DeliveryDate
     */
    public function setDeliveryDate(?string $deliveryDate): void
    {
        $this->deliveryDate = $deliveryDate;
    }

    /**
     * Returns Delivery Instructions.
     * A free text feild for instructions (500 characters max)
     */
    public function getDeliveryInstructions(): ?string
    {
        return $this->deliveryInstructions;
    }

    /**
     * Sets Delivery Instructions.
     * A free text feild for instructions (500 characters max)
     *
     * @maps DeliveryInstructions
     */
    public function setDeliveryInstructions(?string $deliveryInstructions): void
    {
        $this->deliveryInstructions = $deliveryInstructions;
    }

    /**
     * Returns Expected Arrival Date.
     * The date the goods are expected to arrive.
     */
    public function getExpectedArrivalDate(): ?string
    {
        return $this->expectedArrivalDate;
    }

    /**
     * Sets Expected Arrival Date.
     * The date the goods are expected to arrive.
     *
     * @maps ExpectedArrivalDate
     */
    public function setExpectedArrivalDate(?string $expectedArrivalDate): void
    {
        $this->expectedArrivalDate = $expectedArrivalDate;
    }

    /**
     * Returns Has Attachments.
     * boolean to indicate if a purchase order has an attachment
     */
    public function getHasAttachments(): ?bool
    {
        return $this->hasAttachments;
    }

    /**
     * Sets Has Attachments.
     * boolean to indicate if a purchase order has an attachment
     *
     * @maps HasAttachments
     */
    public function setHasAttachments(?bool $hasAttachments): void
    {
        $this->hasAttachments = $hasAttachments;
    }

    /**
     * Returns Line Amount Types.
     * Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount
     * Types
     */
    public function getLineAmountTypes(): ?string
    {
        return $this->lineAmountTypes;
    }

    /**
     * Sets Line Amount Types.
     * Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount
     * Types
     *
     * @maps LineAmountTypes
     * @factory \XeroAccountingAPILib\Models\LineAmountTypesEnum::checkValue
     */
    public function setLineAmountTypes(?string $lineAmountTypes): void
    {
        $this->lineAmountTypes = $lineAmountTypes;
    }

    /**
     * Returns Line Items.
     * See LineItems
     *
     * @return LineItem[]|null
     */
    public function getLineItems(): ?array
    {
        return $this->lineItems;
    }

    /**
     * Sets Line Items.
     * See LineItems
     *
     * @maps LineItems
     *
     * @param LineItem[]|null $lineItems
     */
    public function setLineItems(?array $lineItems): void
    {
        $this->lineItems = $lineItems;
    }

    /**
     * Returns Purchase Order ID.
     * Xero generated unique identifier for purchase order
     */
    public function getPurchaseOrderID(): ?string
    {
        return $this->purchaseOrderID;
    }

    /**
     * Sets Purchase Order ID.
     * Xero generated unique identifier for purchase order
     *
     * @maps PurchaseOrderID
     */
    public function setPurchaseOrderID(?string $purchaseOrderID): void
    {
        $this->purchaseOrderID = $purchaseOrderID;
    }

    /**
     * Returns Purchase Order Number.
     * Unique alpha numeric code identifying purchase order (when missing will auto-generate from your
     * Organisation Invoice Settings)
     */
    public function getPurchaseOrderNumber(): ?string
    {
        return $this->purchaseOrderNumber;
    }

    /**
     * Sets Purchase Order Number.
     * Unique alpha numeric code identifying purchase order (when missing will auto-generate from your
     * Organisation Invoice Settings)
     *
     * @maps PurchaseOrderNumber
     */
    public function setPurchaseOrderNumber(?string $purchaseOrderNumber): void
    {
        $this->purchaseOrderNumber = $purchaseOrderNumber;
    }

    /**
     * Returns Reference.
     * Additional reference number
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     * Additional reference number
     *
     * @maps Reference
     */
    public function setReference(?string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Returns Sent to Contact.
     * Boolean to set whether the purchase order should be marked as “sent”. This can be set only on
     * purchase orders that have been approved or billed
     */
    public function getSentToContact(): ?bool
    {
        return $this->sentToContact;
    }

    /**
     * Sets Sent to Contact.
     * Boolean to set whether the purchase order should be marked as “sent”. This can be set only on
     * purchase orders that have been approved or billed
     *
     * @maps SentToContact
     */
    public function setSentToContact(?bool $sentToContact): void
    {
        $this->sentToContact = $sentToContact;
    }

    /**
     * Returns Status.
     * See Purchase Order Status Codes
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * See Purchase Order Status Codes
     *
     * @maps Status
     * @factory \XeroAccountingAPILib\Models\Status17Enum::checkValue
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Status Attribute String.
     * A string to indicate if a invoice status
     */
    public function getStatusAttributeString(): ?string
    {
        return $this->statusAttributeString;
    }

    /**
     * Sets Status Attribute String.
     * A string to indicate if a invoice status
     *
     * @maps StatusAttributeString
     */
    public function setStatusAttributeString(?string $statusAttributeString): void
    {
        $this->statusAttributeString = $statusAttributeString;
    }

    /**
     * Returns Sub Total.
     * Total of purchase order excluding taxes
     */
    public function getSubTotal(): ?float
    {
        return $this->subTotal;
    }

    /**
     * Sets Sub Total.
     * Total of purchase order excluding taxes
     *
     * @maps SubTotal
     */
    public function setSubTotal(?float $subTotal): void
    {
        $this->subTotal = $subTotal;
    }

    /**
     * Returns Telephone.
     * The phone number for the person accepting the delivery
     */
    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    /**
     * Sets Telephone.
     * The phone number for the person accepting the delivery
     *
     * @maps Telephone
     */
    public function setTelephone(?string $telephone): void
    {
        $this->telephone = $telephone;
    }

    /**
     * Returns Total.
     * Total of Purchase Order tax inclusive (i.e. SubTotal + TotalTax)
     */
    public function getTotal(): ?float
    {
        return $this->total;
    }

    /**
     * Sets Total.
     * Total of Purchase Order tax inclusive (i.e. SubTotal + TotalTax)
     *
     * @maps Total
     */
    public function setTotal(?float $total): void
    {
        $this->total = $total;
    }

    /**
     * Returns Total Discount.
     * Total of discounts applied on the purchase order line items
     */
    public function getTotalDiscount(): ?float
    {
        return $this->totalDiscount;
    }

    /**
     * Sets Total Discount.
     * Total of discounts applied on the purchase order line items
     *
     * @maps TotalDiscount
     */
    public function setTotalDiscount(?float $totalDiscount): void
    {
        $this->totalDiscount = $totalDiscount;
    }

    /**
     * Returns Total Tax.
     * Total tax on purchase order
     */
    public function getTotalTax(): ?float
    {
        return $this->totalTax;
    }

    /**
     * Sets Total Tax.
     * Total tax on purchase order
     *
     * @maps TotalTax
     */
    public function setTotalTax(?float $totalTax): void
    {
        $this->totalTax = $totalTax;
    }

    /**
     * Returns Updated Date UTC.
     * Last modified date UTC format
     */
    public function getUpdatedDateUTC(): ?string
    {
        return $this->updatedDateUTC;
    }

    /**
     * Sets Updated Date UTC.
     * Last modified date UTC format
     *
     * @maps UpdatedDateUTC
     */
    public function setUpdatedDateUTC(?string $updatedDateUTC): void
    {
        $this->updatedDateUTC = $updatedDateUTC;
    }

    /**
     * Returns Validation Errors.
     * Displays array of validation error messages from the API
     *
     * @return ValidationError[]|null
     */
    public function getValidationErrors(): ?array
    {
        return $this->validationErrors;
    }

    /**
     * Sets Validation Errors.
     * Displays array of validation error messages from the API
     *
     * @maps ValidationErrors
     *
     * @param ValidationError[]|null $validationErrors
     */
    public function setValidationErrors(?array $validationErrors): void
    {
        $this->validationErrors = $validationErrors;
    }

    /**
     * Returns Warnings.
     * Displays array of warning messages from the API
     *
     * @return ValidationError[]|null
     */
    public function getWarnings(): ?array
    {
        return $this->warnings;
    }

    /**
     * Sets Warnings.
     * Displays array of warning messages from the API
     *
     * @maps Warnings
     *
     * @param ValidationError[]|null $warnings
     */
    public function setWarnings(?array $warnings): void
    {
        $this->warnings = $warnings;
    }

    /**
     * Converts the PurchaseOrder object to a human-readable string representation.
     *
     * @return string The string representation of the PurchaseOrder object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PurchaseOrder',
            [
                'attachments' => $this->attachments,
                'attentionTo' => $this->attentionTo,
                'brandingThemeID' => $this->brandingThemeID,
                'contact' => $this->contact,
                'currencyCode' => $this->currencyCode,
                'currencyRate' => $this->currencyRate,
                'date' => $this->date,
                'deliveryAddress' => $this->deliveryAddress,
                'deliveryDate' => $this->deliveryDate,
                'deliveryInstructions' => $this->deliveryInstructions,
                'expectedArrivalDate' => $this->expectedArrivalDate,
                'hasAttachments' => $this->hasAttachments,
                'lineAmountTypes' => $this->lineAmountTypes,
                'lineItems' => $this->lineItems,
                'purchaseOrderID' => $this->purchaseOrderID,
                'purchaseOrderNumber' => $this->purchaseOrderNumber,
                'reference' => $this->reference,
                'sentToContact' => $this->sentToContact,
                'status' => $this->status,
                'statusAttributeString' => $this->statusAttributeString,
                'subTotal' => $this->subTotal,
                'telephone' => $this->telephone,
                'total' => $this->total,
                'totalDiscount' => $this->totalDiscount,
                'totalTax' => $this->totalTax,
                'updatedDateUTC' => $this->updatedDateUTC,
                'validationErrors' => $this->validationErrors,
                'warnings' => $this->warnings
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->attachments)) {
            $json['Attachments']           = $this->attachments;
        }
        if (isset($this->attentionTo)) {
            $json['AttentionTo']           = $this->attentionTo;
        }
        if (isset($this->brandingThemeID)) {
            $json['BrandingThemeID']       = $this->brandingThemeID;
        }
        if (isset($this->contact)) {
            $json['Contact']               = $this->contact;
        }
        if (isset($this->currencyCode)) {
            $json['CurrencyCode']          = CurrencyCodeEnum::checkValue($this->currencyCode);
        }
        if (isset($this->currencyRate)) {
            $json['CurrencyRate']          = $this->currencyRate;
        }
        if (isset($this->date)) {
            $json['Date']                  = $this->date;
        }
        if (isset($this->deliveryAddress)) {
            $json['DeliveryAddress']       = $this->deliveryAddress;
        }
        if (isset($this->deliveryDate)) {
            $json['DeliveryDate']          = $this->deliveryDate;
        }
        if (isset($this->deliveryInstructions)) {
            $json['DeliveryInstructions']  = $this->deliveryInstructions;
        }
        if (isset($this->expectedArrivalDate)) {
            $json['ExpectedArrivalDate']   = $this->expectedArrivalDate;
        }
        if (isset($this->hasAttachments)) {
            $json['HasAttachments']        = $this->hasAttachments;
        }
        if (isset($this->lineAmountTypes)) {
            $json['LineAmountTypes']       = LineAmountTypesEnum::checkValue($this->lineAmountTypes);
        }
        if (isset($this->lineItems)) {
            $json['LineItems']             = $this->lineItems;
        }
        if (isset($this->purchaseOrderID)) {
            $json['PurchaseOrderID']       = $this->purchaseOrderID;
        }
        if (isset($this->purchaseOrderNumber)) {
            $json['PurchaseOrderNumber']   = $this->purchaseOrderNumber;
        }
        if (isset($this->reference)) {
            $json['Reference']             = $this->reference;
        }
        if (isset($this->sentToContact)) {
            $json['SentToContact']         = $this->sentToContact;
        }
        if (isset($this->status)) {
            $json['Status']                = Status17Enum::checkValue($this->status);
        }
        if (isset($this->statusAttributeString)) {
            $json['StatusAttributeString'] = $this->statusAttributeString;
        }
        if (isset($this->subTotal)) {
            $json['SubTotal']              = $this->subTotal;
        }
        if (isset($this->telephone)) {
            $json['Telephone']             = $this->telephone;
        }
        if (isset($this->total)) {
            $json['Total']                 = $this->total;
        }
        if (isset($this->totalDiscount)) {
            $json['TotalDiscount']         = $this->totalDiscount;
        }
        if (isset($this->totalTax)) {
            $json['TotalTax']              = $this->totalTax;
        }
        if (isset($this->updatedDateUTC)) {
            $json['UpdatedDateUTC']        = $this->updatedDateUTC;
        }
        if (isset($this->validationErrors)) {
            $json['ValidationErrors']      = $this->validationErrors;
        }
        if (isset($this->warnings)) {
            $json['Warnings']              = $this->warnings;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
