<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class Purchase implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $accountCode;

    /**
     * @var string|null
     */
    private $cOGSAccountCode;

    /**
     * @var string|null
     */
    private $taxType;

    /**
     * @var float|null
     */
    private $unitPrice;

    /**
     * Returns Account Code.
     * Default account code to be used for purchased/sale. Not applicable to the purchase details of
     * tracked items
     */
    public function getAccountCode(): ?string
    {
        return $this->accountCode;
    }

    /**
     * Sets Account Code.
     * Default account code to be used for purchased/sale. Not applicable to the purchase details of
     * tracked items
     *
     * @maps AccountCode
     */
    public function setAccountCode(?string $accountCode): void
    {
        $this->accountCode = $accountCode;
    }

    /**
     * Returns C OGS Account Code.
     * Cost of goods sold account. Only applicable to the purchase details of tracked items.
     */
    public function getCOGSAccountCode(): ?string
    {
        return $this->cOGSAccountCode;
    }

    /**
     * Sets C OGS Account Code.
     * Cost of goods sold account. Only applicable to the purchase details of tracked items.
     *
     * @maps COGSAccountCode
     */
    public function setCOGSAccountCode(?string $cOGSAccountCode): void
    {
        $this->cOGSAccountCode = $cOGSAccountCode;
    }

    /**
     * Returns Tax Type.
     * The tax type from TaxRates
     */
    public function getTaxType(): ?string
    {
        return $this->taxType;
    }

    /**
     * Sets Tax Type.
     * The tax type from TaxRates
     *
     * @maps TaxType
     */
    public function setTaxType(?string $taxType): void
    {
        $this->taxType = $taxType;
    }

    /**
     * Returns Unit Price.
     * Unit Price of the item. By default UnitPrice is rounded to two decimal places. You can use 4 decimal
     * places by adding the unitdp=4 querystring parameter to your request.
     */
    public function getUnitPrice(): ?float
    {
        return $this->unitPrice;
    }

    /**
     * Sets Unit Price.
     * Unit Price of the item. By default UnitPrice is rounded to two decimal places. You can use 4 decimal
     * places by adding the unitdp=4 querystring parameter to your request.
     *
     * @maps UnitPrice
     */
    public function setUnitPrice(?float $unitPrice): void
    {
        $this->unitPrice = $unitPrice;
    }

    /**
     * Converts the Purchase object to a human-readable string representation.
     *
     * @return string The string representation of the Purchase object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Purchase',
            [
                'accountCode' => $this->accountCode,
                'cOGSAccountCode' => $this->cOGSAccountCode,
                'taxType' => $this->taxType,
                'unitPrice' => $this->unitPrice
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->accountCode)) {
            $json['AccountCode']     = $this->accountCode;
        }
        if (isset($this->cOGSAccountCode)) {
            $json['COGSAccountCode'] = $this->cOGSAccountCode;
        }
        if (isset($this->taxType)) {
            $json['TaxType']         = $this->taxType;
        }
        if (isset($this->unitPrice)) {
            $json['UnitPrice']       = $this->unitPrice;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
