<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class Quotes implements \JsonSerializable
{
    /**
     * @var Quote[]|null
     */
    private $quotes;

    /**
     * Returns Quotes.
     *
     * @return Quote[]|null
     */
    public function getQuotes(): ?array
    {
        return $this->quotes;
    }

    /**
     * Sets Quotes.
     *
     * @maps Quotes
     *
     * @param Quote[]|null $quotes
     */
    public function setQuotes(?array $quotes): void
    {
        $this->quotes = $quotes;
    }

    /**
     * Converts the Quotes object to a human-readable string representation.
     *
     * @return string The string representation of the Quotes object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Quotes', ['quotes' => $this->quotes]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->quotes)) {
            $json['Quotes'] = $this->quotes;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
