<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class Quote implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $brandingThemeID;

    /**
     * @var Contact|null
     */
    private $contact;

    /**
     * @var string|null
     */
    private $currencyCode;

    /**
     * @var float|null
     */
    private $currencyRate;

    /**
     * @var string|null
     */
    private $date;

    /**
     * @var string|null
     */
    private $dateString;

    /**
     * @var string|null
     */
    private $expiryDate;

    /**
     * @var string|null
     */
    private $expiryDateString;

    /**
     * @var string|null
     */
    private $lineAmountTypes;

    /**
     * @var LineItem[]|null
     */
    private $lineItems;

    /**
     * @var string|null
     */
    private $quoteID;

    /**
     * @var string|null
     */
    private $quoteNumber;

    /**
     * @var string|null
     */
    private $reference;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $statusAttributeString;

    /**
     * @var float|null
     */
    private $subTotal;

    /**
     * @var string|null
     */
    private $summary;

    /**
     * @var string|null
     */
    private $terms;

    /**
     * @var string|null
     */
    private $title;

    /**
     * @var float|null
     */
    private $total;

    /**
     * @var float|null
     */
    private $totalDiscount;

    /**
     * @var float|null
     */
    private $totalTax;

    /**
     * @var string|null
     */
    private $updatedDateUTC;

    /**
     * @var ValidationError[]|null
     */
    private $validationErrors;

    /**
     * Returns Branding Theme ID.
     * See BrandingThemes
     */
    public function getBrandingThemeID(): ?string
    {
        return $this->brandingThemeID;
    }

    /**
     * Sets Branding Theme ID.
     * See BrandingThemes
     *
     * @maps BrandingThemeID
     */
    public function setBrandingThemeID(?string $brandingThemeID): void
    {
        $this->brandingThemeID = $brandingThemeID;
    }

    /**
     * Returns Contact.
     */
    public function getContact(): ?Contact
    {
        return $this->contact;
    }

    /**
     * Sets Contact.
     *
     * @maps Contact
     */
    public function setContact(?Contact $contact): void
    {
        $this->contact = $contact;
    }

    /**
     * Returns Currency Code.
     * 3 letter alpha code for the currency – see list of currency codes
     */
    public function getCurrencyCode(): ?string
    {
        return $this->currencyCode;
    }

    /**
     * Sets Currency Code.
     * 3 letter alpha code for the currency – see list of currency codes
     *
     * @maps CurrencyCode
     * @factory \XeroAccountingAPILib\Models\CurrencyCodeEnum::checkValue
     */
    public function setCurrencyCode(?string $currencyCode): void
    {
        $this->currencyCode = $currencyCode;
    }

    /**
     * Returns Currency Rate.
     * The currency rate for a multicurrency quote
     */
    public function getCurrencyRate(): ?float
    {
        return $this->currencyRate;
    }

    /**
     * Sets Currency Rate.
     * The currency rate for a multicurrency quote
     *
     * @maps CurrencyRate
     */
    public function setCurrencyRate(?float $currencyRate): void
    {
        $this->currencyRate = $currencyRate;
    }

    /**
     * Returns Date.
     * Date quote was issued – YYYY-MM-DD. If the Date element is not specified it will default to the
     * current date based on the timezone setting of the organisation
     */
    public function getDate(): ?string
    {
        return $this->date;
    }

    /**
     * Sets Date.
     * Date quote was issued – YYYY-MM-DD. If the Date element is not specified it will default to the
     * current date based on the timezone setting of the organisation
     *
     * @maps Date
     */
    public function setDate(?string $date): void
    {
        $this->date = $date;
    }

    /**
     * Returns Date String.
     * Date the quote was issued (YYYY-MM-DD)
     */
    public function getDateString(): ?string
    {
        return $this->dateString;
    }

    /**
     * Sets Date String.
     * Date the quote was issued (YYYY-MM-DD)
     *
     * @maps DateString
     */
    public function setDateString(?string $dateString): void
    {
        $this->dateString = $dateString;
    }

    /**
     * Returns Expiry Date.
     * Date the quote expires – YYYY-MM-DD.
     */
    public function getExpiryDate(): ?string
    {
        return $this->expiryDate;
    }

    /**
     * Sets Expiry Date.
     * Date the quote expires – YYYY-MM-DD.
     *
     * @maps ExpiryDate
     */
    public function setExpiryDate(?string $expiryDate): void
    {
        $this->expiryDate = $expiryDate;
    }

    /**
     * Returns Expiry Date String.
     * Date the quote expires – YYYY-MM-DD.
     */
    public function getExpiryDateString(): ?string
    {
        return $this->expiryDateString;
    }

    /**
     * Sets Expiry Date String.
     * Date the quote expires – YYYY-MM-DD.
     *
     * @maps ExpiryDateString
     */
    public function setExpiryDateString(?string $expiryDateString): void
    {
        $this->expiryDateString = $expiryDateString;
    }

    /**
     * Returns Line Amount Types.
     * Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount
     * Types
     */
    public function getLineAmountTypes(): ?string
    {
        return $this->lineAmountTypes;
    }

    /**
     * Sets Line Amount Types.
     * Line amounts are exclusive of tax by default if you don’t specify this element. See Line Amount
     * Types
     *
     * @maps LineAmountTypes
     * @factory \XeroAccountingAPILib\Models\QuoteLineAmountTypesEnum::checkValue
     */
    public function setLineAmountTypes(?string $lineAmountTypes): void
    {
        $this->lineAmountTypes = $lineAmountTypes;
    }

    /**
     * Returns Line Items.
     * See LineItems
     *
     * @return LineItem[]|null
     */
    public function getLineItems(): ?array
    {
        return $this->lineItems;
    }

    /**
     * Sets Line Items.
     * See LineItems
     *
     * @maps LineItems
     *
     * @param LineItem[]|null $lineItems
     */
    public function setLineItems(?array $lineItems): void
    {
        $this->lineItems = $lineItems;
    }

    /**
     * Returns Quote ID.
     * QuoteID GUID is automatically generated and is returned after create or GET.
     */
    public function getQuoteID(): ?string
    {
        return $this->quoteID;
    }

    /**
     * Sets Quote ID.
     * QuoteID GUID is automatically generated and is returned after create or GET.
     *
     * @maps QuoteID
     */
    public function setQuoteID(?string $quoteID): void
    {
        $this->quoteID = $quoteID;
    }

    /**
     * Returns Quote Number.
     * Unique alpha numeric code identifying a quote (Max Length = 255)
     */
    public function getQuoteNumber(): ?string
    {
        return $this->quoteNumber;
    }

    /**
     * Sets Quote Number.
     * Unique alpha numeric code identifying a quote (Max Length = 255)
     *
     * @maps QuoteNumber
     */
    public function setQuoteNumber(?string $quoteNumber): void
    {
        $this->quoteNumber = $quoteNumber;
    }

    /**
     * Returns Reference.
     * Additional reference number
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     * Additional reference number
     *
     * @maps Reference
     */
    public function setReference(?string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Returns Status.
     * The status of the quote.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * The status of the quote.
     *
     * @maps Status
     * @factory \XeroAccountingAPILib\Models\QuoteStatusCodesEnum::checkValue
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Status Attribute String.
     * A string to indicate if a invoice status
     */
    public function getStatusAttributeString(): ?string
    {
        return $this->statusAttributeString;
    }

    /**
     * Sets Status Attribute String.
     * A string to indicate if a invoice status
     *
     * @maps StatusAttributeString
     */
    public function setStatusAttributeString(?string $statusAttributeString): void
    {
        $this->statusAttributeString = $statusAttributeString;
    }

    /**
     * Returns Sub Total.
     * Total of quote excluding taxes.
     */
    public function getSubTotal(): ?float
    {
        return $this->subTotal;
    }

    /**
     * Sets Sub Total.
     * Total of quote excluding taxes.
     *
     * @maps SubTotal
     */
    public function setSubTotal(?float $subTotal): void
    {
        $this->subTotal = $subTotal;
    }

    /**
     * Returns Summary.
     * Summary text for the quote
     */
    public function getSummary(): ?string
    {
        return $this->summary;
    }

    /**
     * Sets Summary.
     * Summary text for the quote
     *
     * @maps Summary
     */
    public function setSummary(?string $summary): void
    {
        $this->summary = $summary;
    }

    /**
     * Returns Terms.
     * Terms of the quote
     */
    public function getTerms(): ?string
    {
        return $this->terms;
    }

    /**
     * Sets Terms.
     * Terms of the quote
     *
     * @maps Terms
     */
    public function setTerms(?string $terms): void
    {
        $this->terms = $terms;
    }

    /**
     * Returns Title.
     * Title text for the quote
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * Sets Title.
     * Title text for the quote
     *
     * @maps Title
     */
    public function setTitle(?string $title): void
    {
        $this->title = $title;
    }

    /**
     * Returns Total.
     * Total of Quote tax inclusive (i.e. SubTotal + TotalTax). This will be ignored if it doesn’t equal
     * the sum of the LineAmounts
     */
    public function getTotal(): ?float
    {
        return $this->total;
    }

    /**
     * Sets Total.
     * Total of Quote tax inclusive (i.e. SubTotal + TotalTax). This will be ignored if it doesn’t equal
     * the sum of the LineAmounts
     *
     * @maps Total
     */
    public function setTotal(?float $total): void
    {
        $this->total = $total;
    }

    /**
     * Returns Total Discount.
     * Total of discounts applied on the quote line items
     */
    public function getTotalDiscount(): ?float
    {
        return $this->totalDiscount;
    }

    /**
     * Sets Total Discount.
     * Total of discounts applied on the quote line items
     *
     * @maps TotalDiscount
     */
    public function setTotalDiscount(?float $totalDiscount): void
    {
        $this->totalDiscount = $totalDiscount;
    }

    /**
     * Returns Total Tax.
     * Total tax on quote
     */
    public function getTotalTax(): ?float
    {
        return $this->totalTax;
    }

    /**
     * Sets Total Tax.
     * Total tax on quote
     *
     * @maps TotalTax
     */
    public function setTotalTax(?float $totalTax): void
    {
        $this->totalTax = $totalTax;
    }

    /**
     * Returns Updated Date UTC.
     * Last modified date UTC format
     */
    public function getUpdatedDateUTC(): ?string
    {
        return $this->updatedDateUTC;
    }

    /**
     * Sets Updated Date UTC.
     * Last modified date UTC format
     *
     * @maps UpdatedDateUTC
     */
    public function setUpdatedDateUTC(?string $updatedDateUTC): void
    {
        $this->updatedDateUTC = $updatedDateUTC;
    }

    /**
     * Returns Validation Errors.
     * Displays array of validation error messages from the API
     *
     * @return ValidationError[]|null
     */
    public function getValidationErrors(): ?array
    {
        return $this->validationErrors;
    }

    /**
     * Sets Validation Errors.
     * Displays array of validation error messages from the API
     *
     * @maps ValidationErrors
     *
     * @param ValidationError[]|null $validationErrors
     */
    public function setValidationErrors(?array $validationErrors): void
    {
        $this->validationErrors = $validationErrors;
    }

    /**
     * Converts the Quote object to a human-readable string representation.
     *
     * @return string The string representation of the Quote object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Quote',
            [
                'brandingThemeID' => $this->brandingThemeID,
                'contact' => $this->contact,
                'currencyCode' => $this->currencyCode,
                'currencyRate' => $this->currencyRate,
                'date' => $this->date,
                'dateString' => $this->dateString,
                'expiryDate' => $this->expiryDate,
                'expiryDateString' => $this->expiryDateString,
                'lineAmountTypes' => $this->lineAmountTypes,
                'lineItems' => $this->lineItems,
                'quoteID' => $this->quoteID,
                'quoteNumber' => $this->quoteNumber,
                'reference' => $this->reference,
                'status' => $this->status,
                'statusAttributeString' => $this->statusAttributeString,
                'subTotal' => $this->subTotal,
                'summary' => $this->summary,
                'terms' => $this->terms,
                'title' => $this->title,
                'total' => $this->total,
                'totalDiscount' => $this->totalDiscount,
                'totalTax' => $this->totalTax,
                'updatedDateUTC' => $this->updatedDateUTC,
                'validationErrors' => $this->validationErrors
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->brandingThemeID)) {
            $json['BrandingThemeID']       = $this->brandingThemeID;
        }
        if (isset($this->contact)) {
            $json['Contact']               = $this->contact;
        }
        if (isset($this->currencyCode)) {
            $json['CurrencyCode']          = CurrencyCodeEnum::checkValue($this->currencyCode);
        }
        if (isset($this->currencyRate)) {
            $json['CurrencyRate']          = $this->currencyRate;
        }
        if (isset($this->date)) {
            $json['Date']                  = $this->date;
        }
        if (isset($this->dateString)) {
            $json['DateString']            = $this->dateString;
        }
        if (isset($this->expiryDate)) {
            $json['ExpiryDate']            = $this->expiryDate;
        }
        if (isset($this->expiryDateString)) {
            $json['ExpiryDateString']      = $this->expiryDateString;
        }
        if (isset($this->lineAmountTypes)) {
            $json['LineAmountTypes']       = QuoteLineAmountTypesEnum::checkValue($this->lineAmountTypes);
        }
        if (isset($this->lineItems)) {
            $json['LineItems']             = $this->lineItems;
        }
        if (isset($this->quoteID)) {
            $json['QuoteID']               = $this->quoteID;
        }
        if (isset($this->quoteNumber)) {
            $json['QuoteNumber']           = $this->quoteNumber;
        }
        if (isset($this->reference)) {
            $json['Reference']             = $this->reference;
        }
        if (isset($this->status)) {
            $json['Status']                = QuoteStatusCodesEnum::checkValue($this->status);
        }
        if (isset($this->statusAttributeString)) {
            $json['StatusAttributeString'] = $this->statusAttributeString;
        }
        if (isset($this->subTotal)) {
            $json['SubTotal']              = $this->subTotal;
        }
        if (isset($this->summary)) {
            $json['Summary']               = $this->summary;
        }
        if (isset($this->terms)) {
            $json['Terms']                 = $this->terms;
        }
        if (isset($this->title)) {
            $json['Title']                 = $this->title;
        }
        if (isset($this->total)) {
            $json['Total']                 = $this->total;
        }
        if (isset($this->totalDiscount)) {
            $json['TotalDiscount']         = $this->totalDiscount;
        }
        if (isset($this->totalTax)) {
            $json['TotalTax']              = $this->totalTax;
        }
        if (isset($this->updatedDateUTC)) {
            $json['UpdatedDateUTC']        = $this->updatedDateUTC;
        }
        if (isset($this->validationErrors)) {
            $json['ValidationErrors']      = $this->validationErrors;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
