<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class Receipts implements \JsonSerializable
{
    /**
     * @var Receipt[]|null
     */
    private $receipts;

    /**
     * Returns Receipts.
     *
     * @return Receipt[]|null
     */
    public function getReceipts(): ?array
    {
        return $this->receipts;
    }

    /**
     * Sets Receipts.
     *
     * @maps Receipts
     *
     * @param Receipt[]|null $receipts
     */
    public function setReceipts(?array $receipts): void
    {
        $this->receipts = $receipts;
    }

    /**
     * Converts the Receipts object to a human-readable string representation.
     *
     * @return string The string representation of the Receipts object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Receipts', ['receipts' => $this->receipts]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->receipts)) {
            $json['Receipts'] = $this->receipts;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
