<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class ReportRow implements \JsonSerializable
{
    /**
     * @var ReportCell[]|null
     */
    private $cells;

    /**
     * @var string|null
     */
    private $rowType;

    /**
     * @var string|null
     */
    private $title;

    /**
     * Returns Cells.
     *
     * @return ReportCell[]|null
     */
    public function getCells(): ?array
    {
        return $this->cells;
    }

    /**
     * Sets Cells.
     *
     * @maps Cells
     *
     * @param ReportCell[]|null $cells
     */
    public function setCells(?array $cells): void
    {
        $this->cells = $cells;
    }

    /**
     * Returns Row Type.
     */
    public function getRowType(): ?string
    {
        return $this->rowType;
    }

    /**
     * Sets Row Type.
     *
     * @maps RowType
     * @factory \XeroAccountingAPILib\Models\RowTypeEnum::checkValue
     */
    public function setRowType(?string $rowType): void
    {
        $this->rowType = $rowType;
    }

    /**
     * Returns Title.
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * Sets Title.
     *
     * @maps Title
     */
    public function setTitle(?string $title): void
    {
        $this->title = $title;
    }

    /**
     * Converts the ReportRow object to a human-readable string representation.
     *
     * @return string The string representation of the ReportRow object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ReportRow',
            ['cells' => $this->cells, 'rowType' => $this->rowType, 'title' => $this->title]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->cells)) {
            $json['Cells']   = $this->cells;
        }
        if (isset($this->rowType)) {
            $json['RowType'] = RowTypeEnum::checkValue($this->rowType);
        }
        if (isset($this->title)) {
            $json['Title']   = $this->title;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
