<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class ReportWithRows implements \JsonSerializable
{
    /**
     * @var ReportWithRow[]|null
     */
    private $reports;

    /**
     * Returns Reports.
     *
     * @return ReportWithRow[]|null
     */
    public function getReports(): ?array
    {
        return $this->reports;
    }

    /**
     * Sets Reports.
     *
     * @maps Reports
     *
     * @param ReportWithRow[]|null $reports
     */
    public function setReports(?array $reports): void
    {
        $this->reports = $reports;
    }

    /**
     * Converts the ReportWithRows object to a human-readable string representation.
     *
     * @return string The string representation of the ReportWithRows object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('ReportWithRows', ['reports' => $this->reports]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->reports)) {
            $json['Reports'] = $this->reports;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
