<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class ReportCell implements \JsonSerializable
{
    /**
     * @var ReportAttribute[]|null
     */
    private $attributes;

    /**
     * @var string|null
     */
    private $value;

    /**
     * Returns Attributes.
     *
     * @return ReportAttribute[]|null
     */
    public function getAttributes(): ?array
    {
        return $this->attributes;
    }

    /**
     * Sets Attributes.
     *
     * @maps Attributes
     *
     * @param ReportAttribute[]|null $attributes
     */
    public function setAttributes(?array $attributes): void
    {
        $this->attributes = $attributes;
    }

    /**
     * Returns Value.
     */
    public function getValue(): ?string
    {
        return $this->value;
    }

    /**
     * Sets Value.
     *
     * @maps Value
     */
    public function setValue(?string $value): void
    {
        $this->value = $value;
    }

    /**
     * Converts the ReportCell object to a human-readable string representation.
     *
     * @return string The string representation of the ReportCell object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('ReportCell', ['attributes' => $this->attributes, 'value' => $this->value]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->attributes)) {
            $json['Attributes'] = $this->attributes;
        }
        if (isset($this->value)) {
            $json['Value']      = $this->value;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
