<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * See ReportTaxTypes
 */
class ReportTaxTypeEnum
{
    public const AVALARA = 'AVALARA';

    public const BASEXCLUDED = 'BASEXCLUDED';

    public const CAPITALSALESOUTPUT = 'CAPITALSALESOUTPUT';

    public const CAPITALEXPENSESINPUT = 'CAPITALEXPENSESINPUT';

    public const ECOUTPUT = 'ECOUTPUT';

    public const ECOUTPUTSERVICES = 'ECOUTPUTSERVICES';

    public const ECINPUT = 'ECINPUT';

    public const ECACQUISITIONS = 'ECACQUISITIONS';

    public const EXEMPTEXPENSES = 'EXEMPTEXPENSES';

    public const EXEMPTINPUT = 'EXEMPTINPUT';

    public const EXEMPTOUTPUT = 'EXEMPTOUTPUT';

    public const GSTONIMPORTS = 'GSTONIMPORTS';

    public const INPUT = 'INPUT';

    public const INPUTTAXED = 'INPUTTAXED';

    public const MOSSSALES = 'MOSSSALES';

    public const NONE = 'NONE';

    public const NONEOUTPUT = 'NONEOUTPUT';

    public const OUTPUT = 'OUTPUT';

    public const PURCHASESINPUT = 'PURCHASESINPUT';

    public const SALESOUTPUT = 'SALESOUTPUT';

    public const EXEMPTCAPITAL = 'EXEMPTCAPITAL';

    public const EXEMPTEXPORT = 'EXEMPTEXPORT';

    public const CAPITALEXINPUT = 'CAPITALEXINPUT';

    public const GSTONCAPIMPORTS = 'GSTONCAPIMPORTS';

    public const GSTONCAPITALIMPORTS = 'GSTONCAPITALIMPORTS';

    public const REVERSECHARGES = 'REVERSECHARGES';

    public const PAYMENTS = 'PAYMENTS';

    public const INVOICE = 'INVOICE';

    public const CASH = 'CASH';

    public const ACCRUAL = 'ACCRUAL';

    public const FLATRATECASH = 'FLATRATECASH';

    public const FLATRATEACCRUAL = 'FLATRATEACCRUAL';

    public const ACCRUALS = 'ACCRUALS';

    public const TXCA = 'TXCA';

    public const SRCAS = 'SRCAS';

    public const DSOUTPUT = 'DSOUTPUT';

    public const BLINPUT2 = 'BLINPUT2';

    public const EPINPUT = 'EPINPUT';

    public const IMINPUT2 = 'IMINPUT2';

    public const MEINPUT = 'MEINPUT';

    public const IGDSINPUT2 = 'IGDSINPUT2';

    public const ESN33OUTPUT = 'ESN33OUTPUT';

    public const OPINPUT = 'OPINPUT';

    public const OSOUTPUT = 'OSOUTPUT';

    public const TXN33INPUT = 'TXN33INPUT';

    public const TXESSINPUT = 'TXESSINPUT';

    public const TXREINPUT = 'TXREINPUT';

    public const TXPETINPUT = 'TXPETINPUT';

    public const NRINPUT = 'NRINPUT';

    public const ES33OUTPUT = 'ES33OUTPUT';

    public const ZERORATEDINPUT = 'ZERORATEDINPUT';

    public const ZERORATEDOUTPUT = 'ZERORATEDOUTPUT';

    public const DRCHARGESUPPLY = 'DRCHARGESUPPLY';

    public const DRCHARGE = 'DRCHARGE';

    public const CAPINPUT = 'CAPINPUT';

    public const CAPIMPORTS = 'CAPIMPORTS';

    public const IMINPUT = 'IMINPUT';

    public const INPUT2 = 'INPUT2';

    public const CIUINPUT = 'CIUINPUT';

    public const SRINPUT = 'SRINPUT';

    public const OUTPUT2 = 'OUTPUT2';

    public const SROUTPUT = 'SROUTPUT';

    public const CAPOUTPUT = 'CAPOUTPUT';

    public const SROUTPUT2 = 'SROUTPUT2';

    public const CIUOUTPUT = 'CIUOUTPUT';

    public const ZROUTPUT = 'ZROUTPUT';

    public const ZREXPORT = 'ZREXPORT';

    public const ACC28PLUS = 'ACC28PLUS';

    public const ACCUPTO28 = 'ACCUPTO28';

    public const OTHEROUTPUT = 'OTHEROUTPUT';

    public const SHOUTPUT = 'SHOUTPUT';

    public const ZRINPUT = 'ZRINPUT';

    public const BADDEBT = 'BADDEBT';

    public const OTHERINPUT = 'OTHERINPUT';

    private const _ALL_VALUES = [
        self::AVALARA,
        self::BASEXCLUDED,
        self::CAPITALSALESOUTPUT,
        self::CAPITALEXPENSESINPUT,
        self::ECOUTPUT,
        self::ECOUTPUTSERVICES,
        self::ECINPUT,
        self::ECACQUISITIONS,
        self::EXEMPTEXPENSES,
        self::EXEMPTINPUT,
        self::EXEMPTOUTPUT,
        self::GSTONIMPORTS,
        self::INPUT,
        self::INPUTTAXED,
        self::MOSSSALES,
        self::NONE,
        self::NONEOUTPUT,
        self::OUTPUT,
        self::PURCHASESINPUT,
        self::SALESOUTPUT,
        self::EXEMPTCAPITAL,
        self::EXEMPTEXPORT,
        self::CAPITALEXINPUT,
        self::GSTONCAPIMPORTS,
        self::GSTONCAPITALIMPORTS,
        self::REVERSECHARGES,
        self::PAYMENTS,
        self::INVOICE,
        self::CASH,
        self::ACCRUAL,
        self::FLATRATECASH,
        self::FLATRATEACCRUAL,
        self::ACCRUALS,
        self::TXCA,
        self::SRCAS,
        self::DSOUTPUT,
        self::BLINPUT2,
        self::EPINPUT,
        self::IMINPUT2,
        self::MEINPUT,
        self::IGDSINPUT2,
        self::ESN33OUTPUT,
        self::OPINPUT,
        self::OSOUTPUT,
        self::TXN33INPUT,
        self::TXESSINPUT,
        self::TXREINPUT,
        self::TXPETINPUT,
        self::NRINPUT,
        self::ES33OUTPUT,
        self::ZERORATEDINPUT,
        self::ZERORATEDOUTPUT,
        self::DRCHARGESUPPLY,
        self::DRCHARGE,
        self::CAPINPUT,
        self::CAPIMPORTS,
        self::IMINPUT,
        self::INPUT2,
        self::CIUINPUT,
        self::SRINPUT,
        self::OUTPUT2,
        self::SROUTPUT,
        self::CAPOUTPUT,
        self::SROUTPUT2,
        self::CIUOUTPUT,
        self::ZROUTPUT,
        self::ZREXPORT,
        self::ACC28PLUS,
        self::ACCUPTO28,
        self::OTHEROUTPUT,
        self::SHOUTPUT,
        self::ZRINPUT,
        self::BADDEBT,
        self::OTHERINPUT
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for ReportTaxTypeEnum.");
    }
}
