<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class ReportFields implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $description;

    /**
     * @var string|null
     */
    private $fieldID;

    /**
     * @var string|null
     */
    private $value;

    /**
     * Returns Description.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * @maps Description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Field ID.
     */
    public function getFieldID(): ?string
    {
        return $this->fieldID;
    }

    /**
     * Sets Field ID.
     *
     * @maps FieldID
     */
    public function setFieldID(?string $fieldID): void
    {
        $this->fieldID = $fieldID;
    }

    /**
     * Returns Value.
     */
    public function getValue(): ?string
    {
        return $this->value;
    }

    /**
     * Sets Value.
     *
     * @maps Value
     */
    public function setValue(?string $value): void
    {
        $this->value = $value;
    }

    /**
     * Converts the ReportFields object to a human-readable string representation.
     *
     * @return string The string representation of the ReportFields object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ReportFields',
            ['description' => $this->description, 'fieldID' => $this->fieldID, 'value' => $this->value]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->description)) {
            $json['Description'] = $this->description;
        }
        if (isset($this->fieldID)) {
            $json['FieldID']     = $this->fieldID;
        }
        if (isset($this->value)) {
            $json['Value']       = $this->value;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
