<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class Report implements \JsonSerializable
{
    /**
     * @var TenNinetyNineContact[]|null
     */
    private $contacts;

    /**
     * @var string|null
     */
    private $reportDate;

    /**
     * @var string|null
     */
    private $reportID;

    /**
     * @var string|null
     */
    private $reportName;

    /**
     * @var string|null
     */
    private $reportTitle;

    /**
     * @var string|null
     */
    private $reportType;

    /**
     * @var string|null
     */
    private $updatedDateUTC;

    /**
     * Returns Contacts.
     *
     * @return TenNinetyNineContact[]|null
     */
    public function getContacts(): ?array
    {
        return $this->contacts;
    }

    /**
     * Sets Contacts.
     *
     * @maps Contacts
     *
     * @param TenNinetyNineContact[]|null $contacts
     */
    public function setContacts(?array $contacts): void
    {
        $this->contacts = $contacts;
    }

    /**
     * Returns Report Date.
     * Date of report
     */
    public function getReportDate(): ?string
    {
        return $this->reportDate;
    }

    /**
     * Sets Report Date.
     * Date of report
     *
     * @maps ReportDate
     */
    public function setReportDate(?string $reportDate): void
    {
        $this->reportDate = $reportDate;
    }

    /**
     * Returns Report ID.
     * See Prepayment Types
     */
    public function getReportID(): ?string
    {
        return $this->reportID;
    }

    /**
     * Sets Report ID.
     * See Prepayment Types
     *
     * @maps ReportID
     */
    public function setReportID(?string $reportID): void
    {
        $this->reportID = $reportID;
    }

    /**
     * Returns Report Name.
     * See Prepayment Types
     */
    public function getReportName(): ?string
    {
        return $this->reportName;
    }

    /**
     * Sets Report Name.
     * See Prepayment Types
     *
     * @maps ReportName
     */
    public function setReportName(?string $reportName): void
    {
        $this->reportName = $reportName;
    }

    /**
     * Returns Report Title.
     * See Prepayment Types
     */
    public function getReportTitle(): ?string
    {
        return $this->reportTitle;
    }

    /**
     * Sets Report Title.
     * See Prepayment Types
     *
     * @maps ReportTitle
     */
    public function setReportTitle(?string $reportTitle): void
    {
        $this->reportTitle = $reportTitle;
    }

    /**
     * Returns Report Type.
     * See Prepayment Types
     */
    public function getReportType(): ?string
    {
        return $this->reportType;
    }

    /**
     * Sets Report Type.
     * See Prepayment Types
     *
     * @maps ReportType
     * @factory \XeroAccountingAPILib\Models\ReportTypeEnum::checkValue
     */
    public function setReportType(?string $reportType): void
    {
        $this->reportType = $reportType;
    }

    /**
     * Returns Updated Date UTC.
     * Updated Date
     */
    public function getUpdatedDateUTC(): ?string
    {
        return $this->updatedDateUTC;
    }

    /**
     * Sets Updated Date UTC.
     * Updated Date
     *
     * @maps UpdatedDateUTC
     */
    public function setUpdatedDateUTC(?string $updatedDateUTC): void
    {
        $this->updatedDateUTC = $updatedDateUTC;
    }

    /**
     * Converts the Report object to a human-readable string representation.
     *
     * @return string The string representation of the Report object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Report',
            [
                'contacts' => $this->contacts,
                'reportDate' => $this->reportDate,
                'reportID' => $this->reportID,
                'reportName' => $this->reportName,
                'reportTitle' => $this->reportTitle,
                'reportType' => $this->reportType,
                'updatedDateUTC' => $this->updatedDateUTC
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->contacts)) {
            $json['Contacts']       = $this->contacts;
        }
        if (isset($this->reportDate)) {
            $json['ReportDate']     = $this->reportDate;
        }
        if (isset($this->reportID)) {
            $json['ReportID']       = $this->reportID;
        }
        if (isset($this->reportName)) {
            $json['ReportName']     = $this->reportName;
        }
        if (isset($this->reportTitle)) {
            $json['ReportTitle']    = $this->reportTitle;
        }
        if (isset($this->reportType)) {
            $json['ReportType']     = ReportTypeEnum::checkValue($this->reportType);
        }
        if (isset($this->updatedDateUTC)) {
            $json['UpdatedDateUTC'] = $this->updatedDateUTC;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
