<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * The frequency with which tax returns are processed. See Sales Tax Period
 */
class SalesTaxPeriodEnum
{
    public const MONTHLY = 'MONTHLY';

    public const QUARTERLY1 = 'QUARTERLY1';

    public const QUARTERLY2 = 'QUARTERLY2';

    public const QUARTERLY3 = 'QUARTERLY3';

    public const ANNUALLY = 'ANNUALLY';

    public const ONEMONTHS = 'ONEMONTHS';

    public const TWOMONTHS = 'TWOMONTHS';

    public const SIXMONTHS = 'SIXMONTHS';

    public const ENUM_1MONTHLY = '1MONTHLY';

    public const ENUM_2MONTHLY = '2MONTHLY';

    public const ENUM_3MONTHLY = '3MONTHLY';

    public const ENUM_6MONTHLY = '6MONTHLY';

    public const QUARTERLY = 'QUARTERLY';

    public const YEARLY = 'YEARLY';

    public const NONE = 'NONE';

    private const _ALL_VALUES = [
        self::MONTHLY,
        self::QUARTERLY1,
        self::QUARTERLY2,
        self::QUARTERLY3,
        self::ANNUALLY,
        self::ONEMONTHS,
        self::TWOMONTHS,
        self::SIXMONTHS,
        self::ENUM_1MONTHLY,
        self::ENUM_2MONTHLY,
        self::ENUM_3MONTHLY,
        self::ENUM_6MONTHLY,
        self::QUARTERLY,
        self::YEARLY,
        self::NONE
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for SalesTaxPeriodEnum.");
    }
}
