<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class Schedule implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $dueDate;

    /**
     * @var string|null
     */
    private $dueDateType;

    /**
     * @var string|null
     */
    private $endDate;

    /**
     * @var string|null
     */
    private $nextScheduledDate;

    /**
     * @var int|null
     */
    private $period;

    /**
     * @var string|null
     */
    private $startDate;

    /**
     * @var string|null
     */
    private $unit;

    /**
     * Returns Due Date.
     * Integer used with due date type e.g 20 (of following month), 31 (of current month)
     */
    public function getDueDate(): ?int
    {
        return $this->dueDate;
    }

    /**
     * Sets Due Date.
     * Integer used with due date type e.g 20 (of following month), 31 (of current month)
     *
     * @maps DueDate
     */
    public function setDueDate(?int $dueDate): void
    {
        $this->dueDate = $dueDate;
    }

    /**
     * Returns Due Date Type.
     * the payment terms
     */
    public function getDueDateType(): ?string
    {
        return $this->dueDateType;
    }

    /**
     * Sets Due Date Type.
     * the payment terms
     *
     * @maps DueDateType
     * @factory \XeroAccountingAPILib\Models\DueDateTypeEnum::checkValue
     */
    public function setDueDateType(?string $dueDateType): void
    {
        $this->dueDateType = $dueDateType;
    }

    /**
     * Returns End Date.
     * Invoice end date – only returned if the template has an end date set
     */
    public function getEndDate(): ?string
    {
        return $this->endDate;
    }

    /**
     * Sets End Date.
     * Invoice end date – only returned if the template has an end date set
     *
     * @maps EndDate
     */
    public function setEndDate(?string $endDate): void
    {
        $this->endDate = $endDate;
    }

    /**
     * Returns Next Scheduled Date.
     * The calendar date of the next invoice in the schedule to be generated
     */
    public function getNextScheduledDate(): ?string
    {
        return $this->nextScheduledDate;
    }

    /**
     * Sets Next Scheduled Date.
     * The calendar date of the next invoice in the schedule to be generated
     *
     * @maps NextScheduledDate
     */
    public function setNextScheduledDate(?string $nextScheduledDate): void
    {
        $this->nextScheduledDate = $nextScheduledDate;
    }

    /**
     * Returns Period.
     * Integer used with the unit e.g. 1 (every 1 week), 2 (every 2 months)
     */
    public function getPeriod(): ?int
    {
        return $this->period;
    }

    /**
     * Sets Period.
     * Integer used with the unit e.g. 1 (every 1 week), 2 (every 2 months)
     *
     * @maps Period
     */
    public function setPeriod(?int $period): void
    {
        $this->period = $period;
    }

    /**
     * Returns Start Date.
     * Date the first invoice of the current version of the repeating schedule was generated (changes when
     * repeating invoice is edited)
     */
    public function getStartDate(): ?string
    {
        return $this->startDate;
    }

    /**
     * Sets Start Date.
     * Date the first invoice of the current version of the repeating schedule was generated (changes when
     * repeating invoice is edited)
     *
     * @maps StartDate
     */
    public function setStartDate(?string $startDate): void
    {
        $this->startDate = $startDate;
    }

    /**
     * Returns Unit.
     * One of the following - WEEKLY or MONTHLY
     */
    public function getUnit(): ?string
    {
        return $this->unit;
    }

    /**
     * Sets Unit.
     * One of the following - WEEKLY or MONTHLY
     *
     * @maps Unit
     * @factory \XeroAccountingAPILib\Models\UnitEnum::checkValue
     */
    public function setUnit(?string $unit): void
    {
        $this->unit = $unit;
    }

    /**
     * Converts the Schedule object to a human-readable string representation.
     *
     * @return string The string representation of the Schedule object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Schedule',
            [
                'dueDate' => $this->dueDate,
                'dueDateType' => $this->dueDateType,
                'endDate' => $this->endDate,
                'nextScheduledDate' => $this->nextScheduledDate,
                'period' => $this->period,
                'startDate' => $this->startDate,
                'unit' => $this->unit
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->dueDate)) {
            $json['DueDate']           = $this->dueDate;
        }
        if (isset($this->dueDateType)) {
            $json['DueDateType']       = DueDateTypeEnum::checkValue($this->dueDateType);
        }
        if (isset($this->endDate)) {
            $json['EndDate']           = $this->endDate;
        }
        if (isset($this->nextScheduledDate)) {
            $json['NextScheduledDate'] = $this->nextScheduledDate;
        }
        if (isset($this->period)) {
            $json['Period']            = $this->period;
        }
        if (isset($this->startDate)) {
            $json['StartDate']         = $this->startDate;
        }
        if (isset($this->unit)) {
            $json['Unit']              = UnitEnum::checkValue($this->unit);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
