<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * If this is a system account then this element is returned. See System Account types. Note that non-
 * system accounts may have this element set as either “” or null.
 */
class SystemAccountEnum
{
    public const DEBTORS = 'DEBTORS';

    public const CREDITORS = 'CREDITORS';

    public const BANKCURRENCYGAIN = 'BANKCURRENCYGAIN';

    public const GST = 'GST';

    public const GSTONIMPORTS = 'GSTONIMPORTS';

    public const HISTORICAL = 'HISTORICAL';

    public const REALISEDCURRENCYGAIN = 'REALISEDCURRENCYGAIN';

    public const RETAINEDEARNINGS = 'RETAINEDEARNINGS';

    public const ROUNDING = 'ROUNDING';

    public const TRACKINGTRANSFERS = 'TRACKINGTRANSFERS';

    public const UNPAIDEXPCLM = 'UNPAIDEXPCLM';

    public const UNREALISEDCURRENCYGAIN = 'UNREALISEDCURRENCYGAIN';

    public const WAGEPAYABLES = 'WAGEPAYABLES';

    public const CISASSETS = 'CISASSETS';

    public const CISASSET = 'CISASSET';

    public const CISLABOUR = 'CISLABOUR';

    public const CISLABOUREXPENSE = 'CISLABOUREXPENSE';

    public const CISLABOURINCOME = 'CISLABOURINCOME';

    public const CISLIABILITY = 'CISLIABILITY';

    public const CISMATERIALS = 'CISMATERIALS';

    private const _ALL_VALUES = [
        self::DEBTORS,
        self::CREDITORS,
        self::BANKCURRENCYGAIN,
        self::GST,
        self::GSTONIMPORTS,
        self::HISTORICAL,
        self::REALISEDCURRENCYGAIN,
        self::RETAINEDEARNINGS,
        self::ROUNDING,
        self::TRACKINGTRANSFERS,
        self::UNPAIDEXPCLM,
        self::UNREALISEDCURRENCYGAIN,
        self::WAGEPAYABLES,
        self::CISASSETS,
        self::CISASSET,
        self::CISLABOUR,
        self::CISLABOUREXPENSE,
        self::CISLABOURINCOME,
        self::CISLIABILITY,
        self::CISMATERIALS
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for SystemAccountEnum.");
    }
}
