<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class TaxRates implements \JsonSerializable
{
    /**
     * @var TaxRate[]|null
     */
    private $taxRates;

    /**
     * Returns Tax Rates.
     *
     * @return TaxRate[]|null
     */
    public function getTaxRates(): ?array
    {
        return $this->taxRates;
    }

    /**
     * Sets Tax Rates.
     *
     * @maps TaxRates
     *
     * @param TaxRate[]|null $taxRates
     */
    public function setTaxRates(?array $taxRates): void
    {
        $this->taxRates = $taxRates;
    }

    /**
     * Converts the TaxRates object to a human-readable string representation.
     *
     * @return string The string representation of the TaxRates object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('TaxRates', ['taxRates' => $this->taxRates]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->taxRates)) {
            $json['TaxRates'] = $this->taxRates;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
