<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class TrackingOption implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $trackingCategoryID;

    /**
     * @var string|null
     */
    private $trackingOptionID;

    /**
     * Returns Name.
     * The name of the tracking option e.g. Marketing, East (max length = 100)
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The name of the tracking option e.g. Marketing, East (max length = 100)
     *
     * @maps Name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Status.
     * The status of a tracking option
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * The status of a tracking option
     *
     * @maps Status
     * @factory \XeroAccountingAPILib\Models\Status13Enum::checkValue
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Tracking Category ID.
     * Filter by a tracking category e.g. 297c2dc5-cc47-4afd-8ec8-74990b8761e9
     */
    public function getTrackingCategoryID(): ?string
    {
        return $this->trackingCategoryID;
    }

    /**
     * Sets Tracking Category ID.
     * Filter by a tracking category e.g. 297c2dc5-cc47-4afd-8ec8-74990b8761e9
     *
     * @maps TrackingCategoryID
     */
    public function setTrackingCategoryID(?string $trackingCategoryID): void
    {
        $this->trackingCategoryID = $trackingCategoryID;
    }

    /**
     * Returns Tracking Option ID.
     * The Xero identifier for a tracking option e.g. ae777a87-5ef3-4fa0-a4f0-d10e1f13073a
     */
    public function getTrackingOptionID(): ?string
    {
        return $this->trackingOptionID;
    }

    /**
     * Sets Tracking Option ID.
     * The Xero identifier for a tracking option e.g. ae777a87-5ef3-4fa0-a4f0-d10e1f13073a
     *
     * @maps TrackingOptionID
     */
    public function setTrackingOptionID(?string $trackingOptionID): void
    {
        $this->trackingOptionID = $trackingOptionID;
    }

    /**
     * Converts the TrackingOption object to a human-readable string representation.
     *
     * @return string The string representation of the TrackingOption object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'TrackingOption',
            [
                'name' => $this->name,
                'status' => $this->status,
                'trackingCategoryID' => $this->trackingCategoryID,
                'trackingOptionID' => $this->trackingOptionID
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->name)) {
            $json['Name']               = $this->name;
        }
        if (isset($this->status)) {
            $json['Status']             = Status13Enum::checkValue($this->status);
        }
        if (isset($this->trackingCategoryID)) {
            $json['TrackingCategoryID'] = $this->trackingCategoryID;
        }
        if (isset($this->trackingOptionID)) {
            $json['TrackingOptionID']   = $this->trackingOptionID;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
