<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class TrackingOptions implements \JsonSerializable
{
    /**
     * @var TrackingOption[]|null
     */
    private $options;

    /**
     * Returns Options.
     *
     * @return TrackingOption[]|null
     */
    public function getOptions(): ?array
    {
        return $this->options;
    }

    /**
     * Sets Options.
     *
     * @maps Options
     *
     * @param TrackingOption[]|null $options
     */
    public function setOptions(?array $options): void
    {
        $this->options = $options;
    }

    /**
     * Converts the TrackingOptions object to a human-readable string representation.
     *
     * @return string The string representation of the TrackingOptions object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('TrackingOptions', ['options' => $this->options]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->options)) {
            $json['Options'] = $this->options;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
