<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use stdClass;
use XeroAccountingAPILib\ApiHelper;

class TrackingCategory implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $name;

    /**
     * @var string|null
     */
    private $option;

    /**
     * @var TrackingOption[]|null
     */
    private $options;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $trackingCategoryID;

    /**
     * @var string|null
     */
    private $trackingOptionID;

    /**
     * Returns Name.
     * The name of the tracking category e.g. Department, Region (max length = 100)
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The name of the tracking category e.g. Department, Region (max length = 100)
     *
     * @maps Name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Option.
     * The option name of the tracking option e.g. East, West (max length = 100)
     */
    public function getOption(): ?string
    {
        return $this->option;
    }

    /**
     * Sets Option.
     * The option name of the tracking option e.g. East, West (max length = 100)
     *
     * @maps Option
     */
    public function setOption(?string $option): void
    {
        $this->option = $option;
    }

    /**
     * Returns Options.
     * See Tracking Options
     *
     * @return TrackingOption[]|null
     */
    public function getOptions(): ?array
    {
        return $this->options;
    }

    /**
     * Sets Options.
     * See Tracking Options
     *
     * @maps Options
     *
     * @param TrackingOption[]|null $options
     */
    public function setOptions(?array $options): void
    {
        $this->options = $options;
    }

    /**
     * Returns Status.
     * The status of a tracking category
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * The status of a tracking category
     *
     * @maps Status
     * @factory \XeroAccountingAPILib\Models\Status14Enum::checkValue
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Tracking Category ID.
     * The Xero identifier for a tracking category e.g. 297c2dc5-cc47-4afd-8ec8-74990b8761e9
     */
    public function getTrackingCategoryID(): ?string
    {
        return $this->trackingCategoryID;
    }

    /**
     * Sets Tracking Category ID.
     * The Xero identifier for a tracking category e.g. 297c2dc5-cc47-4afd-8ec8-74990b8761e9
     *
     * @maps TrackingCategoryID
     */
    public function setTrackingCategoryID(?string $trackingCategoryID): void
    {
        $this->trackingCategoryID = $trackingCategoryID;
    }

    /**
     * Returns Tracking Option ID.
     * The Xero identifier for a tracking option e.g. dc54c220-0140-495a-b925-3246adc0075f
     */
    public function getTrackingOptionID(): ?string
    {
        return $this->trackingOptionID;
    }

    /**
     * Sets Tracking Option ID.
     * The Xero identifier for a tracking option e.g. dc54c220-0140-495a-b925-3246adc0075f
     *
     * @maps TrackingOptionID
     */
    public function setTrackingOptionID(?string $trackingOptionID): void
    {
        $this->trackingOptionID = $trackingOptionID;
    }

    /**
     * Converts the TrackingCategory object to a human-readable string representation.
     *
     * @return string The string representation of the TrackingCategory object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'TrackingCategory',
            [
                'name' => $this->name,
                'option' => $this->option,
                'options' => $this->options,
                'status' => $this->status,
                'trackingCategoryID' => $this->trackingCategoryID,
                'trackingOptionID' => $this->trackingOptionID
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->name)) {
            $json['Name']               = $this->name;
        }
        if (isset($this->option)) {
            $json['Option']             = $this->option;
        }
        if (isset($this->options)) {
            $json['Options']            = $this->options;
        }
        if (isset($this->status)) {
            $json['Status']             = Status14Enum::checkValue($this->status);
        }
        if (isset($this->trackingCategoryID)) {
            $json['TrackingCategoryID'] = $this->trackingCategoryID;
        }
        if (isset($this->trackingOptionID)) {
            $json['TrackingOptionID']   = $this->trackingOptionID;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
