<?php

declare(strict_types=1);

/*
 * XeroAccountingAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace XeroAccountingAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * See Version Types
 */
class VersionEnum
{
    public const AU = 'AU';

    public const NZ = 'NZ';

    public const GLOBAL_ = 'GLOBAL';

    public const UK = 'UK';

    public const US = 'US';

    public const AUONRAMP = 'AUONRAMP';

    public const NZONRAMP = 'NZONRAMP';

    public const GLOBALONRAMP = 'GLOBALONRAMP';

    public const UKONRAMP = 'UKONRAMP';

    public const USONRAMP = 'USONRAMP';

    private const _ALL_VALUES = [
        self::AU,
        self::NZ,
        self::GLOBAL_,
        self::UK,
        self::US,
        self::AUONRAMP,
        self::NZONRAMP,
        self::GLOBALONRAMP,
        self::UKONRAMP,
        self::USONRAMP
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for VersionEnum.");
    }
}
